function report = detecdiv_catalog_run_index_job(projectRoot, dbFile)
% detecdiv_catalog_run_index_job  Background-safe wrapper around project indexing.

    report = detecdiv_catalog_index_projects(projectRoot, dbFile, ...
        'Verbose', false, ...
        'LoadProjectMetadata', true, ...
        'MarkMissingProjects', true);
end
