function recipe = detecdiv_python_recipe()
% detecdiv_python_recipe  Canonical DetecDiv Python environment recipe.
%
% Keep package versions and required imports here. Environment bootstrap
% code for Windows and WSL consumes this recipe so classifier packages do
% not each maintain their own installation procedure.

recipe = struct();
recipe.name = 'detecdiv_python';
recipe.windowsPythonVersion = '3.10';
recipe.wslPythonVersion = '3.12';

recipe.torch = struct( ...
    'version', '2.7.0', ...
    'torchvisionVersion', '0.22.0', ...
    'torchaudioVersion', '2.7.0', ...
    'preferredCudaIndex', 'cu128', ...
    'cpuIndex', 'cpu');

recipe.packages = struct( ...
    'zarr', 'zarr', ...
    'cellposeWindows', 'cellpose[gui]==4.2.1.1', ...
    'cellposeWsl', 'cellpose==4.2.1.1', ...
    'cellposeVersion', '4.2.1.1', ...
    'trackastra', 'trackastra[train]==0.5.3', ...
    'trackastraVersion', '0.5.3');

recipe.requiredImports = { ...
    'torch', 'zarr', 'cellpose', 'trackastra', ...
    'lightning', 'wandb', 'tensorboard', 'configargparse', 'kornia', 'git'};

recipe.wsl = struct( ...
    'defaultDistro', 'Ubuntu-24.04', ...
    'defaultRelativeEnvPath', ['venvs/' recipe.name]);
end
