function [conn, dbFile] = detecdiv_catalog_init(dbFile)
% detecdiv_catalog_init  Create/open the DetecDiv project catalog SQLite DB.
%
% Usage
%   conn = detecdiv_catalog_init()
%   conn = detecdiv_catalog_init(dbFile)
%   [conn, dbFile] = detecdiv_catalog_init(...)

    if nargin < 1 || isempty(dbFile)
        dbFile = localDefaultDbFile();
    end

    dbFile = localNormalizePath(dbFile);
    parentDir = fileparts(dbFile);
    if ~isempty(parentDir) && ~isfolder(parentDir)
        mkdir(parentDir);
    end

    mode = 'connect';
    if ~isfile(dbFile)
        mode = 'create';
    end

    conn = sqlite(dbFile, mode);
    try
        localExec(conn, 'PRAGMA journal_mode = WAL');
    catch
    end
    localExec(conn, 'PRAGMA synchronous = NORMAL');
    localExec(conn, 'PRAGMA foreign_keys = ON');

    localExec(conn, ['CREATE TABLE IF NOT EXISTS catalog_meta (' ...
        'meta_key TEXT PRIMARY KEY, ' ...
        'meta_value TEXT NOT NULL)']);

    localExec(conn, ['CREATE TABLE IF NOT EXISTS catalog_roots (' ...
        'id INTEGER PRIMARY KEY AUTOINCREMENT, ' ...
        'label TEXT, ' ...
        'root_type TEXT NOT NULL, ' ...
        'abs_path TEXT NOT NULL UNIQUE, ' ...
        'created_at TEXT NOT NULL, ' ...
        'updated_at TEXT NOT NULL)']);

    localExec(conn, ['CREATE TABLE IF NOT EXISTS catalog_projects (' ...
        'id INTEGER PRIMARY KEY AUTOINCREMENT, ' ...
        'root_id INTEGER NOT NULL, ' ...
        'name TEXT NOT NULL, ' ...
        'project_mat_abs TEXT NOT NULL UNIQUE, ' ...
        'project_dir_abs TEXT NOT NULL, ' ...
        'project_rel_from_root TEXT, ' ...
        'format_tag TEXT, ' ...
        'health_status TEXT NOT NULL DEFAULT ''ok'', ' ...
        'health_message TEXT, ' ...
        'last_seen_at TEXT NOT NULL, ' ...
        'last_scan_at TEXT NOT NULL, ' ...
        'project_mtime TEXT, ' ...
        'project_bytes INTEGER NOT NULL DEFAULT 0, ' ...
        'fov_count INTEGER NOT NULL DEFAULT 0, ' ...
        'roi_count INTEGER NOT NULL DEFAULT 0, ' ...
        'classifier_count INTEGER NOT NULL DEFAULT 0, ' ...
        'processor_count INTEGER NOT NULL DEFAULT 0, ' ...
        'pipeline_run_count INTEGER NOT NULL DEFAULT 0, ' ...
        'available_raw_count INTEGER NOT NULL DEFAULT 0, ' ...
        'missing_raw_count INTEGER NOT NULL DEFAULT 0, ' ...
        'raw_status TEXT NOT NULL DEFAULT ''unknown'', ' ...
        'metadata_json TEXT, ' ...
        'FOREIGN KEY(root_id) REFERENCES catalog_roots(id) ON DELETE CASCADE, ' ...
        'UNIQUE(root_id, project_rel_from_root))']);

    localExec(conn, ['CREATE TABLE IF NOT EXISTS catalog_project_raw_sources (' ...
        'id INTEGER PRIMARY KEY AUTOINCREMENT, ' ...
        'project_id INTEGER NOT NULL, ' ...
        'raw_kind TEXT NOT NULL, ' ...
        'channel_index INTEGER NOT NULL DEFAULT 1, ' ...
        'raw_abs_path TEXT NOT NULL, ' ...
        'raw_rel_from_root TEXT, ' ...
        'exists_flag INTEGER NOT NULL DEFAULT 0, ' ...
        'FOREIGN KEY(project_id) REFERENCES catalog_projects(id) ON DELETE CASCADE)']);

    localExec(conn, ['CREATE TABLE IF NOT EXISTS catalog_pipeline_runs (' ...
        'id INTEGER PRIMARY KEY AUTOINCREMENT, ' ...
        'project_id INTEGER NOT NULL, ' ...
        'run_id TEXT NOT NULL, ' ...
        'run_path_abs TEXT NOT NULL, ' ...
        'pipeline_id TEXT, ' ...
        'pipeline_path TEXT, ' ...
        'status TEXT NOT NULL, ' ...
        'created_at TEXT, ' ...
        'updated_at TEXT, ' ...
        'summary_json TEXT, ' ...
        'last_seen_at TEXT NOT NULL, ' ...
        'FOREIGN KEY(project_id) REFERENCES catalog_projects(id) ON DELETE CASCADE, ' ...
        'UNIQUE(project_id, run_path_abs))']);

    localExec(conn, 'CREATE INDEX IF NOT EXISTS idx_catalog_projects_root ON catalog_projects(root_id)');
    localExec(conn, 'CREATE INDEX IF NOT EXISTS idx_catalog_projects_health ON catalog_projects(health_status)');
    localExec(conn, 'CREATE INDEX IF NOT EXISTS idx_catalog_projects_raw_status ON catalog_projects(raw_status)');
    localExec(conn, 'CREATE INDEX IF NOT EXISTS idx_catalog_raw_sources_project ON catalog_project_raw_sources(project_id)');
    localExec(conn, 'CREATE INDEX IF NOT EXISTS idx_catalog_pipeline_runs_project ON catalog_pipeline_runs(project_id)');
    localExec(conn, 'CREATE INDEX IF NOT EXISTS idx_catalog_pipeline_runs_status ON catalog_pipeline_runs(status)');

    localSetMeta(conn, 'schema_version', '1');
    localSetMeta(conn, 'schema_name', 'detecdiv_catalog');
end

function dbFile = localDefaultDbFile()
    dbFile = fullfile(prefdir, 'detecdiv_catalog.sqlite');
end

function localSetMeta(conn, key, value)
    key = localSqlQuote(key);
    value = localSqlQuote(value);
    sql = sprintf(['INSERT INTO catalog_meta(meta_key, meta_value) VALUES (%s, %s) ' ...
        'ON CONFLICT(meta_key) DO UPDATE SET meta_value = excluded.meta_value'], key, value);
    localExec(conn, sql);
end

function localExec(conn, sql)
    exec(conn, sql);
end

function out = localNormalizePath(pathIn)
    out = char(string(pathIn));
    out = strrep(out, '/', filesep);
    if ispc
        out = strrep(out, '/', '\');
    else
        out = strrep(out, '\', '/');
    end
end

function txt = localSqlQuote(value)
    if nargin < 1 || isempty(value)
        txt = 'NULL';
        return;
    end

    txt = char(string(value));
    txt = strrep(txt, '''', '''''');
    txt = ['''' txt ''''];
end
