function spec = executionSpec(classif)
%CELLLATENTMODEL.EXECUTIONSPEC Classifier and pipeline contract.
if nargin < 1, classif = []; end
p = cellLatentModel.utils.defaultExecutionParam();
if ~isempty(classif)
    try
        if isprop(classif,'executionParam') && ...
                isstruct(classif.executionParam)
            p = cellLatentModel.utils.applyOverrides( ...
                p,classif.executionParam);
        end
    catch
    end
end
spec = struct();
spec.category = 'Tracking';
spec.defaultClasses = {'latent lineage link'};
spec.summary = ['Lineage inference from stable tracked masks using either ' ...
    'the legacy relation ensemble, the packaged temporal-lineage v002 model, ' ...
    'or a trained continuous cell-state checkpoint.'];
spec.staticKeys = { ...
    'backend','temporalVariant','frameIntervalMinutes', ...
    'causalSolverFeedback', ...
    'inputFamily','outputFamilyName','frameEnd','minLifetime', ...
    'maxBirthArea','minParentAge','maxParentCentroidDistance', ...
    'maxParentContourDistance','maxCandidates','trackingLoadGuard', ...
    'maxNewTracksPerFrame','globalSolver','motherRefractoryFrames', ...
    'youngMotherFrames','solverBeamSize','reviewGlobalReassignments', ...
    'overwriteOutputFamily','device','debug'};
spec.artifactKeys = {'modelSource','modelPath', ...
    'adaptiveMarkerModelSource','adaptiveMarkerModelPath'};
% These legacy/private path keys are declared only so generic pipeline
% serialization can scrub stale nodes. None is imported or shown as a
% static execution parameter.
spec.environmentKeys = {'pythonExecutable','repositoryRoot', ...
    'packagePath','modelPackage','cellLatentRepository'};
spec.requiresRuntimeClassifier = false;
spec.outputKeys = {'outputFamilyName'};
spec.inputKeys = {'trackChannelName','gfpChannelName', ...
    'brightfieldChannelName', ...
    'nucleusChannelName','budneckChannelName'};
spec.defaultImportKeys = [spec.staticKeys spec.outputKeys];
spec.defaults = p;
spec.labels = struct( ...
    'backend','Inference backend', ...
    'trackChannelName','Tracked-label channel', ...
    'gfpChannelName','Legacy GFP channel (optional)', ...
    'brightfieldChannelName','Brightfield channel (optional)', ...
    'nucleusChannelName','Division/nucleus fluorescence channel (optional)', ...
    'budneckChannelName','Bud-neck fluorescence channel (optional)', ...
    'temporalVariant','Temporal v002 variant', ...
    'frameIntervalMinutes','Frame interval (minutes)', ...
    'causalSolverFeedback','Causal solver feedback', ...
    'inputFamily','Input lineage family', ...
    'outputFamilyName','Output lineage family', ...
    'frameEnd','Last frame', ...
    'minLifetime','Minimum bud lifetime', ...
    'maxBirthArea','Maximum bud birth area', ...
    'minParentAge','Minimum mother age', ...
    'maxParentCentroidDistance','Maximum centroid distance', ...
    'maxParentContourDistance','Maximum contour distance', ...
    'maxCandidates','Maximum mother candidates', ...
    'trackingLoadGuard','Tracking-load guard', ...
    'maxNewTracksPerFrame','Maximum new track IDs per frame', ...
    'globalSolver','Global temporal solver', ...
    'motherRefractoryFrames','Mother refractory window (frames)', ...
    'youngMotherFrames','New-daughter maturation window (frames)', ...
    'solverBeamSize','Global solver beam size', ...
    'reviewGlobalReassignments','Review globally changed links', ...
    'overwriteOutputFamily','Overwrite output family', ...
    'adaptiveMarkerModelSource','Adaptive marker model source', ...
    'adaptiveMarkerModelPath','Adaptive marker checkpoint', ...
    'device','Inference device', ...
    'debug','Debug output');
spec.tips = struct( ...
    'backend',['legacy preserves the original Project47 relation ensemble; ' ...
        'temporal_lineage uses the package-bundled, checksum-verified v002 model; ' ...
        'continuous_cell_state uses a trained schema-6/7 continuous checkpoint.'], ...
    'trackChannelName','Indexed masks whose labels are stable track IDs.', ...
    'gfpChannelName',['Optional generic GFP stack used only by legacy. It is ' ...
        'never assigned a temporal or continuous biological role automatically.'], ...
    'brightfieldChannelName',['Explicit brightfield observation for ' ...
        'continuous_cell_state. Leave empty when unavailable; whether it is ' ...
        'consumed is declared by the trained checkpoint.'], ...
    'nucleusChannelName',['Explicit division-associated nucleus fluorescence for ' ...
        'temporal_lineage. It is evaluated before geometry; leave empty when the ' ...
        'marker is unavailable. Generic GFP is never assigned this role automatically.'], ...
    'budneckChannelName',['Explicit bud-neck fluorescence for temporal_lineage. ' ...
        'It is evaluated before geometry; leave empty when the marker is unavailable. ' ...
        'Generic GFP is never assigned this role automatically.'], ...
    'temporalVariant',['temporal_geometry is marker-free; all_observed evaluates ' ...
        'explicit division/nucleus and bud-neck fluorescence first, geometry second, ' ...
        'and temporal history across frames, with explicit missingness.'], ...
    'frameIntervalMinutes',['Physical acquisition interval used to sample temporal ' ...
        'features. It is mandatory and must be set explicitly for ' ...
        'continuous_cell_state.'], ...
    'causalSolverFeedback',['For continuous_cell_state, feed chronological ' ...
        'prefix-solver decisions back into the causal symbolic memory.'], ...
    'trackingLoadGuard','Routes turbulent frames to review before parent assignment.', ...
    'globalSolver','Decodes all mother-bud links jointly with hard biological constraints.', ...
    'motherRefractoryFrames','Forbids a mother from receiving two buds inside this inclusive window.', ...
    'youngMotherFrames','Forbids a newly born daughter from immediately becoming a mother.', ...
    'reviewGlobalReassignments','Keeps globally changed local predictions auditable before persistence.', ...
    'outputFamilyName',['New lineage family referencing the existing mask provider. ' ...
        'The historical GFP-named default is retained for legacy compatibility; ' ...
        'choose a temporal-specific name when using temporal_lineage.'], ...
    'modelSource',['Legacy accepts builtin or trained; continuous_cell_state ' ...
        'requires a trusted trained checkpoint.'], ...
    'modelPath',['Classifier-relative trained checkpoint; never a pipeline ' ...
        'static parameter.'], ...
    'adaptiveMarkerModelSource',['Optional learned residual that injects ' ...
        'spatio-temporal nucleus/bud-neck evidence into continuous linking.'], ...
    'adaptiveMarkerModelPath',['Classifier-relative adaptive marker ' ...
        'checkpoint; never a pipeline static parameter.']);
spec.choices = struct( ...
    'backend',{{'legacy','temporal_lineage','continuous_cell_state'}}, ...
    'temporalVariant',{{'temporal_geometry','all_observed'}}, ...
    'inputFamily',{{'<auto>'}}, ...
    'modelSource',{{'builtin','trained'}}, ...
    'adaptiveMarkerModelSource',{{'none','trained'}}, ...
    'device',{{'auto','cuda','cpu'}}, ...
    'trackingLoadGuard',{{true,false}}, ...
    'globalSolver',{{true,false}}, ...
    'causalSolverFeedback',{{true,false}}, ...
    'reviewGlobalReassignments',{{true,false}}, ...
    'overwriteOutputFamily',{{true,false}}, ...
    'debug',{{false,true}});
end
