function spec = executionSpec(classif)
%CELLLATENTMODEL.EXECUTIONSPEC Classifier and pipeline contract.
if nargin < 1, classif = []; end
p = cellLatentModel.utils.defaultExecutionParam();
if ~isempty(classif)
    try
        if isprop(classif,'executionParam') && ...
                isstruct(classif.executionParam)
            p = cellLatentModel.utils.applyOverrides( ...
                p,classif.executionParam);
        end
    catch
    end
end
spec = struct();
spec.category = 'Tracking';
spec.defaultClasses = {'latent lineage link'};
spec.summary = ['Multimodal latent relation model using tracked-mask ' ...
    'geometry and optional nuclear GFP observations.'];
spec.staticKeys = { ...
    'inputFamily','outputFamilyName','frameEnd','minLifetime', ...
    'maxBirthArea','minParentAge','maxParentCentroidDistance', ...
    'maxParentContourDistance','maxCandidates','trackingLoadGuard', ...
    'maxNewTracksPerFrame','globalSolver','motherRefractoryFrames', ...
    'youngMotherFrames','solverBeamSize','reviewGlobalReassignments', ...
    'overwriteOutputFamily','device','debug'};
spec.artifactKeys = {'modelSource','modelPath'};
spec.environmentKeys = {};
spec.requiresRuntimeClassifier = false;
spec.outputKeys = {'outputFamilyName'};
spec.defaultImportKeys = [spec.staticKeys spec.outputKeys];
spec.defaults = p;
spec.labels = struct( ...
    'trackChannelName','Tracked-label channel', ...
    'gfpChannelName','Nuclear GFP channel (optional)', ...
    'inputFamily','Input lineage family', ...
    'outputFamilyName','Output lineage family', ...
    'frameEnd','Last frame', ...
    'minLifetime','Minimum bud lifetime', ...
    'maxBirthArea','Maximum bud birth area', ...
    'minParentAge','Minimum mother age', ...
    'maxParentCentroidDistance','Maximum centroid distance', ...
    'maxParentContourDistance','Maximum contour distance', ...
    'maxCandidates','Maximum mother candidates', ...
    'trackingLoadGuard','Tracking-load guard', ...
    'maxNewTracksPerFrame','Maximum new track IDs per frame', ...
    'globalSolver','Global temporal solver', ...
    'motherRefractoryFrames','Mother refractory window (frames)', ...
    'youngMotherFrames','New-daughter maturation window (frames)', ...
    'solverBeamSize','Global solver beam size', ...
    'reviewGlobalReassignments','Review globally changed links', ...
    'overwriteOutputFamily','Overwrite output family', ...
    'device','Inference device', ...
    'debug','Debug output');
spec.tips = struct( ...
    'trackChannelName','Indexed masks whose labels are stable track IDs.', ...
    'gfpChannelName','Optional raw GFP stack; missing GFP is represented explicitly.', ...
    'trackingLoadGuard','Routes turbulent frames to review before parent assignment.', ...
    'globalSolver','Decodes all mother-bud links jointly with hard biological constraints.', ...
    'motherRefractoryFrames','Forbids a mother from receiving two buds inside this inclusive window.', ...
    'youngMotherFrames','Forbids a newly born daughter from immediately becoming a mother.', ...
    'reviewGlobalReassignments','Keeps globally changed local predictions auditable before persistence.', ...
    'outputFamilyName','New lineage family referencing the existing mask provider.', ...
    'modelSource','builtin uses the packaged Project47 checkpoint; trained uses the classifier artifact.', ...
    'modelPath','Classifier-relative checkpoint; never a pipeline static parameter.');
spec.choices = struct( ...
    'inputFamily',{{'<auto>'}}, ...
    'modelSource',{{'builtin','trained'}}, ...
    'device',{{'auto','cuda','cpu'}}, ...
    'trackingLoadGuard',{{true,false}}, ...
    'globalSolver',{{true,false}}, ...
    'reviewGlobalReassignments',{{true,false}}, ...
    'overwriteOutputFamily',{{true,false}}, ...
    'debug',{{false,true}});
end
