function result = exportBenchmarkSnapshot(classif, split, exportId, varargin)
%CELLLATENTMODEL.EXPORTBENCHMARKSNAPSHOT Freeze leak-free external eval data.
%
% This exporter deliberately produces two physically separate contracts:
%   inputs/inputs_manifest.json   inference-only raw images and frame-local
%                                 instance masks;
%   targets/targets_manifest.json scoring-only reviewed stable identities,
%                                 lifecycle events and parent/NULL labels.
%
% The top-level manifest links both contracts, their hashes, the immutable
% DetecDiv sources, the exact split and annotation approvals.  Nothing is
% written back to the classifier or its ROIs.

p = inputParser;
p.addParameter('ExternalRoot', ...
    'C:\Users\Gilles\SynologyDrive\Data\cell_latent_model', ...
    @(x) ischar(x) || isstring(x));
p.addParameter('InputMaskChannel', trainingText(classif, ...
    'instanceChannelName', ''), @(x) ischar(x) || isstring(x));
p.addParameter('BrightfieldChannel', trainingText(classif, ...
    'brightfieldChannelName', ''), @(x) ischar(x) || isstring(x));
p.addParameter('GroundTruthMaskChannel', trainingText(classif, ...
    'trackChannelName', ''), @(x) ischar(x) || isstring(x));
p.addParameter('GroundTruthFamily', trainingText(classif, ...
    'groundTruthFamily', ''), @(x) ischar(x) || isstring(x));
p.addParameter('Domain', trainingText(classif, ...
    'trainingDomain', 'detecdiv'), @(x) ischar(x) || isstring(x));
p.addParameter('LabelQuality', 'human_ground_truth', ...
    @(x) ischar(x) || isstring(x));
p.addParameter('Supersedes', '', @(x) ischar(x) || isstring(x));
p.addParameter('KnownExclusions', {}, @isTextCollection);
p.addParameter('AuditWarnings', {}, @isTextCollection);
% Unit tests are the only supported exception to the backed-up data root.
p.addParameter('AllowUnitTestRoot', false, ...
    @(x) islogical(x) && isscalar(x));
p.parse(varargin{:});
opts = p.Results;

exportId = validatedExportId(exportId);
externalRoot = canonicalPath(opts.ExternalRoot);
assertAllowedRoot(externalRoot, opts.AllowUnitTestRoot);
unitTestMode = opts.AllowUnitTestRoot && ...
    isPathWithin(externalRoot, canonicalPath(tempdir));
experimentsRoot = fullfile(externalRoot, 'experiments');
if ~isfolder(experimentsRoot), mkdir(experimentsRoot); end
experimentsRoot = canonicalPath(experimentsRoot);
if ~isPathWithin(experimentsRoot, externalRoot)
    error('cellLatentModel:BenchmarkPathEscapesRoot', ...
        'Experiments directory resolves outside the approved external root.');
end
finalDir = fullfile(experimentsRoot, exportId);
if isfolder(finalDir) || isfile(finalDir)
    error('cellLatentModel:ImmutableBenchmarkExists', ...
        ['Benchmark snapshot "%s" already exists. Completed snapshots ' ...
         'are immutable; choose the next vNNN export ID.'], finalDir);
end
stageDir = fullfile(experimentsRoot, sprintf('.%s.staging_%s', ...
    exportId, compactUuid()));
if isfolder(stageDir) || isfile(stageDir)
    error('cellLatentModel:BenchmarkStagingCollision', ...
        'Benchmark staging target already exists: %s', stageDir);
end

splitContract = normalizeSplit(classif, split);
roiIndices = [splitContract.train_indices, ...
    splitContract.validation_indices, splitContract.test_indices];
if isempty(roiIndices)
    error('cellLatentModel:EmptyBenchmarkSplit', ...
        'At least one ROI must be assigned to train, validation or test.');
end

inputMaskName = requiredText(opts.InputMaskChannel, ...
    'InputMaskChannel');
brightfieldName = requiredText(opts.BrightfieldChannel, ...
    'BrightfieldChannel');
gtMaskName = requiredText(opts.GroundTruthMaskChannel, ...
    'GroundTruthMaskChannel');
gtFamilyName = requiredText(opts.GroundTruthFamily, ...
    'GroundTruthFamily');
if strcmpi(inputMaskName, gtMaskName)
    error('cellLatentModel:BenchmarkInputTargetCollision', ...
        ['Inference masks "%s" are also the reviewed GT mask provider. ' ...
         'Select a distinct frame-local prediction/segmentation channel; ' ...
         'reviewed spatial masks must never enter the inference bundle.'], ...
        inputMaskName);
end
if strcmpi(brightfieldName, gtMaskName)
    error('cellLatentModel:BenchmarkInputTargetCollision', ...
        ['Brightfield input "%s" is also the reviewed GT mask provider. ' ...
         'Select a genuine raw image channel; reviewed labels must never ' ...
         'enter the inference bundle through a raw-image binding.'], ...
        brightfieldName);
end
if strcmpi(brightfieldName, inputMaskName)
    error('cellLatentModel:BenchmarkInputRoleCollision', ...
        ['Brightfield "%s" and frame-local masks must be distinct source ' ...
         'channels.'], brightfieldName);
end
assertSafeInputChannelName(inputMaskName, 'InputMaskChannel');
assertSafeInputChannelName(brightfieldName, 'BrightfieldChannel');
labelQuality = validatedLabelQuality(opts.LabelQuality);

approvals = cellLatentModel.assertGroundTruthReady(classif, roiIndices);
if numel(approvals) ~= numel(roiIndices) || ...
        any(strlength(string({approvals.approved_hash})) ~= 64)
    error('cellLatentModel:BenchmarkRequiresManagedApproval', ...
        ['Every exported ROI must have a current managed DetecDiv GT ' ...
         'approval. Legacy or unhashed GT cannot be frozen for scoring.']);
end

sourceBefore = sourceSnapshot(classif, roiIndices);
assertUniqueSourcePayloads(sourceBefore);
assertClassifierSnapshotMatches(classif, roiIndices, ...
    sourceBefore.classifier_files.path);
[repoRoot, gitCommit, worktreeStatus] = codeProvenance();
if ~unitTestMode && ~isempty(strtrim(worktreeStatus))
    error('cellLatentModel:BenchmarkDirtyCode', ...
        ['DetecDiv has uncommitted code changes. Commit or restore them ' ...
         'before creating a scientific benchmark snapshot.']);
end
createdAt = utcIso8601();
mkdir(stageDir);
stageCleanup = onCleanup(@() removeFolder(stageDir));
inputsDir = fullfile(stageDir, 'inputs');
targetsDir = fullfile(stageDir, 'targets');
mkdir(inputsDir);
mkdir(targetsDir);

inputRows = repmat(emptyInputRow(), numel(roiIndices), 1);
targetRows = repmat(emptyTargetRow(), numel(roiIndices), 1);
for i = 1:numel(roiIndices)
    roiIndex = roiIndices(i);
    roiObj = detachedDiskRoi(classif.roi(roiIndex), ...
        {inputMaskName, brightfieldName, gtMaskName});
    assertInputChannelRoles(roiObj, inputMaskName, brightfieldName);
    approval = approvalForIndex(approvals, roiIndex);
    frames = approvedFrames(approval, roiObj);
    partition = partitionForIndex(splitContract, roiIndex);

    inputMasks = readSinglePlaneStack(roiObj, inputMaskName, true);
    brightfield = readSinglePlaneStack(roiObj, brightfieldName, false);
    gtMaskLabels = readSinglePlaneStack(roiObj, gtMaskName, true);
    assertCompatibleStacks(inputMasks, brightfield, gtMaskLabels, ...
        roiObj.id);
    assertFramesAvailable(frames, size(inputMasks, 3), roiObj.id);
    inputMasks = canonicalFrameLocalLabels(inputMasks(:,:,frames));
    brightfield = single(brightfield(:,:,frames));
    gtMaskLabels = uint32(gtMaskLabels(:,:,frames));

    [model, ~] = roiObj.loadCellModel('MigrateLegacy', true);
    assertInferenceChannelsNotGroundTruth( ...
        model, inputMaskName, brightfieldName, roiObj.id);

    inputRel = sprintf('inputs/roi_%03d_inputs.h5', roiIndex);
    inputFile = fullfile(stageDir, strrep(inputRel, '/', filesep));
    writeStack(inputFile, '/frame_local_instance_masks', ...
        inputMasks, 'uint32');
    writeStack(inputFile, '/brightfield', brightfield, 'single');
    inputHash = fileSha256(inputFile);

    [stableIds, family] = cellLatentTracker.materializeStableTracks( ...
        gtMaskLabels, model, frames, gtMaskName);
    assertGroundTruthFamily(family, gtFamilyName, roiObj.id);
    parentage = annotationManager.validateParentage( ...
        model, family.family_id, 'Frames', frames);
    if ~parentage.valid
        error('cellLatentModel:InvalidBenchmarkParentage', ...
            'ROI %s has invalid reviewed parentage: %s', ...
            char(string(roiObj.id)), ...
            strjoin(cellstr(parentage.errors), ' '));
    end
    target = buildTargets(model, family, stableIds, frames, ...
        annotationManager.frameCount(roiObj), roiObj.id, ...
        approval.approved_hash);
    targetRel = sprintf('targets/roi_%03d_targets.h5', roiIndex);
    targetFile = fullfile(stageDir, strrep(targetRel, '/', filesep));
    writeTargetFile(targetFile, stableIds, target);
    targetHash = fileSha256(targetFile);

    inputRows(i) = struct( ...
        'roi_id', char(string(roiObj.id)), ...
        'partition', partition, ...
        'source_frames', frames, ...
        'frame_bounds', [frames(1) frames(end)], ...
        'payload_path', inputRel, ...
        'payload_sha256', inputHash, ...
        'payload_bytes', fileBytes(inputFile), ...
        'mask_channel', inputMaskName, ...
        'mask_dataset', '/frame_local_instance_masks', ...
        'mask_representation', 'canonical_frame_local_labels', ...
        'brightfield_channel', brightfieldName, ...
        'brightfield_dataset', '/brightfield');
    targetRows(i) = struct( ...
        'roi_id', char(string(roiObj.id)), ...
        'partition', partition, ...
        'source_frames', frames, ...
        'frame_bounds', [frames(1) frames(end)], ...
        'payload_path', targetRel, ...
        'payload_sha256', targetHash, ...
        'payload_bytes', fileBytes(targetFile), ...
        'relation_namespace', target.relation_namespace, ...
        'stable_id_dataset', '/stable_track_ids', ...
        'lifecycle_datasets', target.lifecycle_datasets, ...
        'relation_datasets', target.relation_datasets, ...
        'track_count', numel(target.track_ids), ...
        'parent_count', nnz(target.birth_class == uint8(2)), ...
        'null_count', nnz(target.birth_class == uint8(1)), ...
        'end_count', nnz(target.end_observed), ...
        'approval', approvalRecord(approval), ...
        'label_quality', labelQuality);
end

inputsManifest = struct( ...
    'schema_version', 1, ...
    'format', 'detecdiv_benchmark_inputs_v1', ...
    'export_id', exportId, ...
    'creation_time_utc', createdAt, ...
    'source_system', 'DetecDiv', ...
    'source_classifier', inferenceClassifierProvenance( ...
        classif, sourceBefore.classifier_files), ...
    'source_rois', inferenceRoiProvenance(sourceBefore.rois), ...
    'code', struct( ...
        'repository_id', 'DetecDiv', ...
        'repository_path_sha256', textSha256(normalizedPath(repoRoot)), ...
        'git_commit', gitCommit, ...
        'worktree_clean', isempty(strtrim(worktreeStatus)), ...
        'worktree_status_sha256', textSha256(worktreeStatus)), ...
    'contract', ['Inference-only BF/raw pixels and independently relabeled ' ...
        'frame-local instance masks. No reviewed annotations are present.'], ...
    'domain', char(string(opts.Domain)), ...
    'split', inputSplit(splitContract), ...
    'items', inputRows, ...
    'known_exclusions', {{'reviewed annotations', ...
        'persistent object IDs', 'family links', 'scoring events'}});
assertInferenceManifestClean(inputsManifest);
inputsManifestFile = fullfile(inputsDir, 'inputs_manifest.json');
writeJsonNew(inputsManifestFile, inputsManifest);
assertInferenceDirectoryClean(inputsDir);

parentagePolicy = parentageEventPolicy();
targetsManifest = struct( ...
    'schema_version', 1, ...
    'format', 'detecdiv_benchmark_targets_v1', ...
    'contract', ['Scoring-only human-reviewed stable identities, observed ' ...
        'birth/END events and mother/NULL parentage. Never load this ' ...
        'manifest during inference.'], ...
    'first_frame_policy', ...
        'NULL unless an explicit reviewed mother relation exists', ...
    'parentage_event_policy', parentagePolicy, ...
    'domain', char(string(opts.Domain)), ...
    'label_quality', labelQuality, ...
    'split', targetSplit(splitContract), ...
    'items', targetRows);
targetsManifestFile = fullfile(targetsDir, 'targets_manifest.json');
writeJsonNew(targetsManifestFile, targetsManifest);

sourceAfter = sourceSnapshot(classif, roiIndices);
assertSnapshotsEqual(sourceBefore, sourceAfter);
inputsRecord = manifestRecord(inputsManifestFile, stageDir);
targetsRecord = manifestRecord(targetsManifestFile, stageDir);
topManifest = struct( ...
    'schema_version', 1, ...
    'format', 'detecdiv_external_benchmark_snapshot_v1', ...
    'export_id', exportId, ...
    'creation_time_utc', createdAt, ...
    'supersedes', char(string(opts.Supersedes)), ...
    'source_system', 'DetecDiv', ...
    'source_classifier', struct( ...
        'id', char(string(classif.strid)), ...
        'path', normalizedPath(classif.path), ...
        'files', sourceBefore.classifier_files), ...
    'source_rois', sourceBefore.rois, ...
    'code', struct('repository', normalizedPath(repoRoot), ...
        'git_commit', gitCommit, 'worktree_status', worktreeStatus), ...
    'split_contract', topSplit(splitContract), ...
    'label_contract', struct( ...
        'quality', labelQuality, ...
        'authority', 'DetecDiv managed human-reviewed GT', ...
        'first_frame_policy', ...
            'NULL unless explicitly mother-linked by the reviewer', ...
        'parentage_event_policy', parentagePolicy, ...
        'inference_target_separation', 'physical_manifests_and_payloads'), ...
    'inputs_manifest', inputsRecord, ...
    'targets_manifest', targetsRecord, ...
    'known_exclusions', {textCollection(opts.KnownExclusions)}, ...
    'audit_warnings', {unique([textCollection(opts.AuditWarnings), ...
        dirtyWarning(worktreeStatus)], 'stable')});
topManifestFile = fullfile(stageDir, 'manifest.json');
writeJsonNew(topManifestFile, topManifest);

% Re-read every manifest and verify every declared hash before publication.
jsondecode(fileread(inputsManifestFile));
jsondecode(fileread(targetsManifestFile));
jsondecode(fileread(topManifestFile));
verifyPayloadRecords(stageDir, inputRows, targetRows);
assertSnapshotsEqual(sourceBefore, sourceSnapshot(classif, roiIndices));
cellLatentModel.utils.atomicPublishDirectory(stageDir, finalDir);
clear stageCleanup;

result = struct( ...
    'directory', finalDir, ...
    'manifest', fullfile(finalDir, 'manifest.json'), ...
    'inputs_manifest', fullfile(finalDir, 'inputs', ...
        'inputs_manifest.json'), ...
    'targets_manifest', fullfile(finalDir, 'targets', ...
        'targets_manifest.json'), ...
    'export_id', exportId);
end

function row = emptyInputRow()
row = struct('roi_id','','partition','','source_frames',[], ...
    'frame_bounds',[],'payload_path','','payload_sha256','', ...
    'payload_bytes',0,'mask_channel','','mask_dataset','', ...
    'mask_representation','','brightfield_channel','', ...
    'brightfield_dataset','');
end

function row = emptyTargetRow()
row = struct('roi_id','','partition','','source_frames',[], ...
    'frame_bounds',[],'payload_path','','payload_sha256','', ...
    'payload_bytes',0,'relation_namespace',struct(), ...
    'stable_id_dataset','','lifecycle_datasets',struct(), ...
    'relation_datasets',struct(),'track_count',0,'parent_count',0, ...
    'null_count',0,'end_count',0,'approval',struct(), ...
    'label_quality','');
end

function value = inferenceClassifierProvenance(classif, file)
value = struct( ...
    'id', char(string(classif.strid)), ...
    'snapshot_sha256', file.sha256, ...
    'snapshot_bytes', file.bytes);
end

function values = inferenceRoiProvenance(rois)
values = repmat(struct('roi_index',0,'roi_id','','roi_bbox',[], ...
    'source_sha256','','image_store_sha256',''), numel(rois), 1);
for i = 1:numel(rois)
    values(i) = struct( ...
        'roi_index', rois(i).roi_index, ...
        'roi_id', rois(i).roi_id, ...
        'roi_bbox', rois(i).roi_bbox, ...
        'source_sha256', rois(i).source_sha256, ...
        'image_store_sha256', rois(i).image_store_sha256);
end
end

function split = normalizeSplit(classif, raw)
if ~isstruct(raw) || ~isscalar(raw)
    error('cellLatentModel:InvalidBenchmarkSplit', ...
        'Split must be a scalar struct with train/validation/test indices.');
end
train = splitValues(raw, {'train'});
validation = splitValues(raw, {'validation','val'});
test = splitValues(raw, {'test'});
allIndices = [train validation test];
if any(allIndices < 1 | allIndices > numel(classif.roi)) || ...
        numel(unique(allIndices)) ~= numel(allIndices)
    error('cellLatentModel:InvalidBenchmarkSplit', ...
        ['Split ROI indices must be in range and each ROI must belong to ' ...
         'exactly one partition.']);
end
allIds = roiIds(classif, allIndices);
if any(cellfun(@isempty, allIds)) || ...
        numel(unique(lower(string(allIds)))) ~= numel(allIds)
    error('cellLatentModel:InvalidBenchmarkSplit', ...
        'Every exported ROI must have one non-empty unique stable ROI ID.');
end
allPaths = strings(1, numel(allIndices));
for i = 1:numel(allIndices)
    source = classif.roi(allIndices(i));
    roiId = char(string(source.id));
    imageStore = fullfile(source.path, ['im_' roiId '.h5']);
    if ~isfile(imageStore)
        error('cellLatentModel:InvalidBenchmarkSplit', ...
            ['ROI identity "%s" does not resolve to its authoritative ' ...
             'image store: %s. Aliases cannot cross benchmark partitions.'], ...
            roiId, imageStore);
    end
    allPaths(i) = lower(string(canonicalPath(imageStore)));
end
if numel(unique(allPaths)) ~= numel(allPaths)
    error('cellLatentModel:InvalidBenchmarkSplit', ...
        ['The same disk-backed ROI source appears more than once in the ' ...
         'split. A source cannot cross benchmark partitions under aliases.']);
end
split = struct( ...
    'train_indices', train, ...
    'validation_indices', validation, ...
    'test_indices', test, ...
    'train_ids', {roiIds(classif, train)}, ...
    'validation_ids', {roiIds(classif, validation)}, ...
    'test_ids', {roiIds(classif, test)});
end

function values = splitValues(raw, names)
values = [];
for i = 1:numel(names)
    if isfield(raw, names{i})
        values = raw.(names{i});
        break;
    end
end
if isempty(values), return; end
values = double(values(:).');
if any(~isfinite(values) | values ~= round(values))
    error('cellLatentModel:InvalidBenchmarkSplit', ...
        'Split ROI indices must be finite integers.');
end
values = round(values);
end

function ids = roiIds(classif, indices)
ids = cell(1, numel(indices));
for i = 1:numel(indices)
    ids{i} = char(string(classif.roi(indices(i)).id));
end
end

function partition = partitionForIndex(split, roiIndex)
if ismember(roiIndex, split.train_indices)
    partition = 'train';
elseif ismember(roiIndex, split.validation_indices)
    partition = 'validation';
elseif ismember(roiIndex, split.test_indices)
    partition = 'test';
else
    error('cellLatentModel:InvalidBenchmarkSplit', ...
        'ROI %d is not assigned to the benchmark split.', roiIndex);
end
end

function value = inputSplit(split)
value = struct('train', {split.train_ids}, ...
    'validation', {split.validation_ids}, 'test', {split.test_ids});
end

function value = targetSplit(split)
value = inputSplit(split);
end

function value = topSplit(split)
value = struct( ...
    'unit', 'whole_roi', ...
    'train', struct('indices', split.train_indices, ...
        'roi_ids', {split.train_ids}), ...
    'validation', struct('indices', split.validation_indices, ...
        'roi_ids', {split.validation_ids}), ...
    'test', struct('indices', split.test_indices, ...
        'roi_ids', {split.test_ids}), ...
    'overlap_allowed', false);
end

function roiObj = detachedDiskRoi(source, channels)
[h5File, exists] = source.getH5Filename();
if ~exists
    error('cellLatentModel:BenchmarkSourceNotMaterialized', ...
        'ROI %s has no disk-backed HDF5 source: %s', ...
        char(string(source.id)), h5File);
end
roiObj = roi(char(string(source.id)), source.value);
roiObj.path = char(string(source.path));
try
    roiObj.load('Channel', unique(channels, 'stable'), ...
        'Data', true, 'Silent');
catch ME
    error('cellLatentModel:BenchmarkChannelNotFound', ...
        'Cannot load required ROI %s benchmark channel(s): %s', ...
        char(string(source.id)), ME.message);
end
end

function stack = readSinglePlaneStack(roiObj, channelName, labels)
try
    index = roiObj.findChannelID(channelName, 'exact');
catch
    index = roiObj.findChannelID(channelName);
end

if numel(index) ~= 1
    error('cellLatentModel:BenchmarkChannelNotFound', ...
        ['ROI %s must contain exactly one image plane for channel "%s"; ' ...
         'found %d.'], char(string(roiObj.id)), channelName, numel(index));
end
stack = squeeze(roiObj.image(:,:,index,:));
if ismatrix(stack)
    stack = reshape(stack, size(stack,1), size(stack,2), 1);
end
if labels
    if any(~isfinite(double(stack(:))) | stack(:) < 0 | ...
            stack(:) ~= floor(stack(:)))
        error('cellLatentModel:InvalidBenchmarkMask', ...
            'ROI %s channel "%s" is not a non-negative integer mask.', ...
            char(string(roiObj.id)), channelName);
    end
    stack = uint32(stack);
else
    stack = single(stack);
end
end

function assertInputChannelRoles(roiObj, inputMaskName, brightfieldName)
maskIndexed = channelIndexedFlag(roiObj, inputMaskName);
rawIndexed = channelIndexedFlag(roiObj, brightfieldName);
if ~maskIndexed
    error('cellLatentModel:InvalidBenchmarkInputRole', ...
        'ROI %s input mask channel "%s" is not marked indexed.', ...
        char(string(roiObj.id)), inputMaskName);
end
if rawIndexed
    error('cellLatentModel:InvalidBenchmarkInputRole', ...
        ['ROI %s brightfield channel "%s" is marked indexed and may be ' ...
         'a label image. Select a genuine non-indexed raw channel.'], ...
        char(string(roiObj.id)), brightfieldName);
end
end

function value = channelIndexedFlag(roiObj, channelName)
try
    plane = roiObj.findChannelID(channelName, 'exact');
catch
    plane = roiObj.findChannelID(channelName);
end
if numel(plane) ~= 1
    error('cellLatentModel:BenchmarkChannelNotFound', ...
        'ROI %s channel "%s" does not resolve to one plane.', ...
        char(string(roiObj.id)), channelName);
end
logicalIndex = double(roiObj.channelid(plane));
if logicalIndex < 1 || logicalIndex > numel(roiObj.display.indexed)
    error('cellLatentModel:InvalidBenchmarkInputRole', ...
        'ROI %s channel "%s" has inconsistent indexed metadata.', ...
        char(string(roiObj.id)), channelName);
end
value = logical(roiObj.display.indexed(logicalIndex));
end

function assertCompatibleStacks(inputMasks, brightfield, gtMasks, roiId)
if ~isequal(size(inputMasks), size(brightfield)) || ...
        ~isequal(size(inputMasks), size(gtMasks))
    error('cellLatentModel:BenchmarkChannelSizeMismatch', ...
        ['ROI %s inference masks, brightfield and reviewed masks must have ' ...
         'identical H/W/T dimensions.'], char(string(roiId)));
end
end

function assertFramesAvailable(frames, total, roiId)
if isempty(frames) || any(frames < 1 | frames > total) || ...
        any(diff(frames) ~= 1)
    error('cellLatentModel:InvalidBenchmarkFrameBounds', ...
        ['ROI %s benchmark frames must be one non-empty contiguous range ' ...
         'within 1:%d.'], char(string(roiId)), total);
end
end

function frames = approvedFrames(approval, roiObj)
bounds = double(approval.frame_bounds(:).');
if numel(bounds) ~= 2 || any(~isfinite(bounds)) || ...
        bounds(1) < 1 || bounds(2) < bounds(1)
    error('cellLatentModel:InvalidBenchmarkFrameBounds', ...
        'ROI %s approval has invalid frame bounds.', char(string(roiObj.id)));
end
frames = round(bounds(1)):round(bounds(2));
end

function masks = canonicalFrameLocalLabels(masks)
masks = uint32(masks);
for frame = 1:size(masks, 3)
    source = masks(:,:,frame);
    labels = unique(source);
    labels(labels == 0) = [];
    target = zeros(size(source), 'uint32');
    for i = 1:numel(labels)
        target(source == labels(i)) = uint32(i);
    end
    masks(:,:,frame) = target;
end
end

function assertGroundTruthFamily(family, requested, roiId)
if ~strcmpi(char(string(family.name)), requested)
    error('cellLatentModel:BenchmarkGroundTruthFamilyMismatch', ...
        ['ROI %s reviewed mask provider resolves to family "%s", not the ' ...
         'requested GT family "%s".'], char(string(roiId)), ...
        char(string(family.name)), requested);
end
if ~strcmpi(char(string(family.lineage_source)), 'ground_truth')
    error('cellLatentModel:BenchmarkGroundTruthFamilyMismatch', ...
        'ROI %s family "%s" is not marked ground_truth.', ...
        char(string(roiId)), requested);
end
end

function assertInferenceChannelsNotGroundTruth( ...
        model, inputMaskName, brightfieldName, roiId)
model = cellModel.normalize(model);
families = model.families;
reviewed = strcmpi(string(families.lineage_source), 'ground_truth');
providers = string(families.mask_provider(reviewed));
roles = {inputMaskName, brightfieldName};
for i = 1:numel(roles)
    if any(strcmpi(providers, string(roles{i})))
        error('cellLatentModel:BenchmarkInputTargetCollision', ...
            ['ROI %s input channel "%s" is the mask provider of a ' ...
             'ground_truth cell-model family. Reviewed spatial labels ' ...
             'cannot enter the inference bundle under an alias.'], ...
            char(string(roiId)), roles{i});
    end
end
end

function target = buildTargets(model, family, stableIds, frames, ...
        roiFrameCount, roiId, approvalHash)
model = cellModel.normalize(model);
[model, ~] = cellModel.canonicalizeParentageEvents(model);
familyId = uint32(family.family_id);
materialized = unique(uint64(stableIds(stableIds > 0)));
if isempty(materialized)
    error('cellLatentModel:EmptyBenchmarkTarget', ...
        'ROI %s has no materialized stable GT identity.', ...
        char(string(roiId)));
end
instances = model.instances;
trackIds = unique(instances.track_id( ...
    instances.family_id == familyId & instances.track_id > 0));
if ~all(ismember(materialized, trackIds))
    error('cellLatentModel:InvalidBenchmarkTarget', ...
        'ROI %s materialized identities do not belong to the GT family.', ...
        char(string(roiId)));
end

trackIds = sort(materialized(:));
n = numel(trackIds);
birthSource = zeros(n,1,'uint32');
birthLocal = zeros(n,1,'uint32');
birthObserved = false(n,1);
endSource = zeros(n,1,'uint32');
endLocal = zeros(n,1,'uint32');
endObserved = false(n,1);
parentTrack = zeros(n,1,'uint64');
birthClass = zeros(n,1,'uint8'); % 0 censored, 1 NULL, 2 parent-linked

relationRows = find(model.relations.family_id == familyId & ...
    model.relations.type_id == uint8(1));
relations = repmat(struct('parent',uint64(0),'child',uint64(0), ...
    'event_source',uint32(0),'event_local',uint32(0)),0,1);
for i = 1:numel(relationRows)
    row = relationRows(i);
    child = model.relations.child_track_id(row);
    parent = model.relations.parent_track_id(row);
    if ~ismember(child, trackIds), continue; end
    if ~ismember(parent, trackIds)
        error('cellLatentModel:BenchmarkRelationOutsideNamespace', ...
            ['ROI %s relation child Track %u is selected but parent Track ' ...
             '%u is absent from the materialized target namespace.'], ...
            char(string(roiId)), child, parent);
    end
    sourceEvent = model.relations.event_frame(row);
    [present, localEvent] = ismember(double(sourceEvent), frames);
    if ~present
        error('cellLatentModel:BenchmarkRelationOutsideFrameBounds', ...
            ['ROI %s relation for selected child Track %u has event frame ' ...
             '%u outside the approved benchmark range %u:%u. Expand the ' ...
             'bounds rather than publishing an ambiguous local event.'], ...
            char(string(roiId)), child, sourceEvent, ...
            uint32(frames(1)), uint32(frames(end)));
    end
    relation = struct('parent',uint64(parent),'child',uint64(child), ...
        'event_source',uint32(sourceEvent), ...
        'event_local',uint32(localEvent));
    relations(end+1,1) = relation; %#ok<AGROW>
end
if numel(unique([relations.child])) ~= numel(relations)
    error('cellLatentModel:InvalidBenchmarkParentage', ...
        'ROI %s contains multiple selected parents for one child.', ...
        char(string(roiId)));
end

for i = 1:n
    id = trackIds(i);
    allFrames = unique(double(instances.frame( ...
        instances.family_id == familyId & instances.track_id == id)));
    globalBirth = min(allFrames);
    globalEnd = max(allFrames);
    birthSource(i) = uint32(globalBirth);
    endSource(i) = uint32(globalEnd);
    [birthInRange, localBirth] = ismember(globalBirth, frames);
    [endInRange, localEnd] = ismember(globalEnd, frames);
    birthLocal(i) = uint32(localBirth * birthInRange);
    endLocal(i) = uint32(localEnd * endInRange);
    birthObserved(i) = birthInRange && ...
        (globalBirth > frames(1) || frames(1) == 1);
    endObserved(i) = endInRange && globalEnd < frames(end) && ...
        globalEnd < double(roiFrameCount);

    match = find([relations.child] == id);
    if birthObserved(i)
        if isempty(match)
            birthClass(i) = uint8(1);
        else
            birthClass(i) = uint8(2);
            parentTrack(i) = relations(match).parent;
        end
    elseif ~isempty(match)
        error('cellLatentModel:BenchmarkRelationAtCensoredBirth', ...
            ['ROI %s relation for child Track %u falls in a left-censored ' ...
             'benchmark interval. Expand the approved frame bounds.'], ...
            char(string(roiId)), id);
    end
end

relationNamespace = struct( ...
    'schema', 'detecdiv.cell_model.roi_family_track_id.v1', ...
    'scope', 'roi_and_family', ...
    'namespace_id', namespaceId( ...
        roiId, family, frames, approvalHash), ...
    'roi_id', char(string(roiId)), ...
    'family_id', double(familyId), ...
    'family_name', char(string(family.name)), ...
    'mask_provider', char(string(family.mask_provider)), ...
    'lineage_source', char(string(family.lineage_source)), ...
    'approval_sha256', char(string(approvalHash)));
target = struct( ...
    'track_ids', trackIds, ...
    'birth_source', birthSource, ...
    'birth_local', birthLocal, ...
    'birth_observed', birthObserved, ...
    'end_source', endSource, ...
    'end_local', endLocal, ...
    'end_observed', endObserved, ...
    'parent_track', parentTrack, ...
    'birth_class', birthClass, ...
    'relations', relations, ...
    'relation_namespace', relationNamespace, ...
    'lifecycle_datasets', struct( ...
        'track_ids','/lifecycle/track_ids', ...
        'birth_source_frame','/lifecycle/birth_source_frame', ...
        'birth_local_frame','/lifecycle/birth_local_frame', ...
        'birth_observed','/lifecycle/birth_observed', ...
        'end_source_frame','/lifecycle/end_source_frame', ...
        'end_local_frame','/lifecycle/end_local_frame', ...
        'end_observed','/lifecycle/end_observed', ...
        'parent_track_id','/lifecycle/parent_track_id', ...
        'birth_class','/lifecycle/birth_class', ...
        'birth_class_legend',struct('censored',0,'null',1,'parent',2)), ...
    'relation_datasets', relationDatasetContract(relations));
end

function value = relationDatasetContract(relations)
value = struct('count','/relations/count', ...
    'parent_track_id','','child_track_id','', ...
    'event_source_frame','','event_local_frame','');
if isempty(relations), return; end
value.parent_track_id = '/relations/parent_track_id';
value.child_track_id = '/relations/child_track_id';
value.event_source_frame = '/relations/event_source_frame';
value.event_local_frame = '/relations/event_local_frame';
end

function writeTargetFile(filename, stableIds, target)
writeStack(filename, '/stable_track_ids', uint32(stableIds), 'uint32');
writeVector(filename, '/lifecycle/track_ids', target.track_ids, 'uint64');
writeVector(filename, '/lifecycle/birth_source_frame', ...
    target.birth_source, 'uint32');
writeVector(filename, '/lifecycle/birth_local_frame', ...
    target.birth_local, 'uint32');
writeVector(filename, '/lifecycle/birth_observed', ...
    uint8(target.birth_observed), 'uint8');
writeVector(filename, '/lifecycle/end_source_frame', ...
    target.end_source, 'uint32');
writeVector(filename, '/lifecycle/end_local_frame', ...
    target.end_local, 'uint32');
writeVector(filename, '/lifecycle/end_observed', ...
    uint8(target.end_observed), 'uint8');
writeVector(filename, '/lifecycle/parent_track_id', ...
    target.parent_track, 'uint64');
writeVector(filename, '/lifecycle/birth_class', ...
    target.birth_class, 'uint8');
writeVector(filename, '/relations/count', ...
    uint32(numel(target.relations)), 'uint32');
if ~isempty(target.relations)
    writeVector(filename, '/relations/parent_track_id', ...
        [target.relations.parent].', 'uint64');
    writeVector(filename, '/relations/child_track_id', ...
        [target.relations.child].', 'uint64');
    writeVector(filename, '/relations/event_source_frame', ...
        [target.relations.event_source].', 'uint32');
    writeVector(filename, '/relations/event_local_frame', ...
        [target.relations.event_local].', 'uint32');
end
end

function writeStack(filename, dataset, stack, datatype)
stored = permute(stack, [2 1 3]);
dims = [size(stack,2), size(stack,1), size(stack,3)];
chunk = [min(dims(1),256), min(dims(2),256), 1];
h5create(filename, dataset, dims, 'Datatype', datatype, ...
    'ChunkSize', chunk, 'Deflate', 1);
h5write(filename, dataset, stored);
h5writeatt(filename, dataset, 'axis_order', 'time,y,x');
end

function writeVector(filename, dataset, values, datatype)
values = cast(values(:), datatype);
if isempty(values)
    error('cellLatentModel:EmptyBenchmarkDataset', ...
        'Cannot write empty required dataset %s.', dataset);
end
h5create(filename, dataset, size(values), 'Datatype', datatype);
h5write(filename, dataset, values);
end

function approval = approvalForIndex(approvals, index)
match = find(double([approvals.roi_index]) == double(index), 1);
if isempty(match)
    error('cellLatentModel:BenchmarkRequiresManagedApproval', ...
        'ROI %d has no managed GT approval.', index);
end
approval = approvals(match);
end

function value = approvalRecord(approval)
value = struct( ...
    'annotation_id', char(string(approval.annotation_id)), ...
    'revision', double(approval.revision), ...
    'approved_sha256', char(string(approval.approved_hash)), ...
    'validated_at', canonicalApprovalTimestamp(approval.validated_at), ...
    'frame_bounds', double(approval.frame_bounds));
end

function value = canonicalApprovalTimestamp(inputValue)
raw = char(string(inputValue));
if ~endsWith(raw, '***')
    value = raw;
    return;
end
base = extractBefore(string(raw), strlength(string(raw)) - 2);
stamp = datetime(base, 'InputFormat', 'yyyy-MM-dd''T''HH:mm:ss', ...
    'TimeZone', 'Europe/Paris');
offsetMinutes = round(minutes(tzoffset(stamp)));
signValue = '+';
if offsetMinutes < 0
    signValue = '-';
end
offsetMinutes = abs(offsetMinutes);
value = sprintf('%s%c%02d:%02d', char(base), signValue, ...
    floor(offsetMinutes / 60), mod(offsetMinutes, 60));
end

function value = parentageEventPolicy()
convention = cellModel.relationTemporalConvention();
value = struct( ...
    'convention', convention.name, ...
    'canonical_event', convention.canonical_event, ...
    'legacy_transform', ...
        ['event_frame is derived as the first child instance frame; ' ...
         'parent and child track IDs are unchanged'], ...
    'source_mutated_during_export', false, ...
    'approval_hash_scope', ...
        ['managed DetecDiv source payload; the target payload SHA-256 ' ...
         'covers the canonicalized export']);
end

function snapshot = sourceSnapshot(classif, indices)
classifierFile = fullfile(classif.path, ...
    [char(string(classif.strid)) '_classification.mat']);
if ~isfile(classifierFile)
    error('cellLatentModel:BenchmarkSourceNotMaterialized', ...
        ['Classifier snapshot is missing: %s. Save the classifier before ' ...
         'creating an immutable benchmark export.'], classifierFile);
end
snapshot = struct('classifier_files', fileRecord(classifierFile), ...
    'rois', repmat(struct('roi_index',0,'roi_id','', ...
        'source_path','','roi_bbox',[],'files',struct([]), ...
        'source_sha256','', ...
        'image_store_sha256',''), ...
        numel(indices), 1));
for i = 1:numel(indices)
    source = classif.roi(indices(i));
    id = char(string(source.id));
    files = { ...
        fullfile(source.path, ['im_' id '.h5']), ...
        fullfile(source.path, ['objects_' id '.h5']), ...
        fullfile(source.path, ['data_' id '.mat'])};
    records = repmat(fileRecord(files{1}), 0, 1);
    for j = 1:numel(files)
        if ~isfile(files{j})
            error('cellLatentModel:BenchmarkSourceNotMaterialized', ...
                'ROI %s authoritative source is missing: %s', id, files{j});
        end
        records(end+1,1) = fileRecord(files{j}); %#ok<AGROW>
    end
    aggregate = strjoin(string({records.sha256}), '|');
    snapshot.rois(i) = struct( ...
        'roi_index', indices(i), ...
        'roi_id', id, ...
        'source_path', normalizedPath(source.path), ...
        'roi_bbox', double(source.value), ...
        'files', records, ...
        'source_sha256', textSha256(aggregate), ...
        'image_store_sha256', records(1).sha256);
end
end

function assertUniqueSourcePayloads(snapshot)
imageHashes = lower(string({snapshot.rois.image_store_sha256}));
if numel(unique(imageHashes)) ~= numel(imageHashes)
    error('cellLatentModel:InvalidBenchmarkSplit', ...
        ['Two exported ROI identities reference byte-identical DetecDiv ' ...
         'image stores. Exact source copies cannot cross benchmark ' ...
         'partitions under different paths or IDs.']);
end
end

function assertSnapshotsEqual(before, after)
if ~strcmp(jsonencode(before), jsonencode(after))
    error('cellLatentModel:BenchmarkSourceChanged', ...
        ['A classifier/ROI source changed while the read-only benchmark ' ...
         'snapshot was being built. Nothing was published.']);
end
end

function assertClassifierSnapshotMatches(classif, indices, filename)
try
    loaded = load(strrep(filename, '/', filesep), 'classiObj');
    saved = loaded.classiObj;
catch ME
    error('cellLatentModel:BenchmarkClassifierSnapshotMismatch', ...
        'Cannot read the saved classifier snapshot: %s', ME.message);
end
if ~isa(saved, 'classi') || ...
        ~strcmp(char(string(saved.strid)), char(string(classif.strid)))
    error('cellLatentModel:BenchmarkClassifierSnapshotMismatch', ...
        'The saved classifier does not match the active DetecDiv classifier.');
end
scientificProperties = {'classifierPkg','trainingParam','executionParam', ...
    'channelName','channelName2'};
for propertyIndex = 1:numel(scientificProperties)
    name = scientificProperties{propertyIndex};
    if ~isequaln(saved.(name), classif.(name))
        error('cellLatentModel:BenchmarkClassifierSnapshotMismatch', ...
            ['Active classifier property "%s" differs from the saved ' ...
             'snapshot. Save the classifier before exporting.'], name);
    end
end
savedIds = string({saved.roi.id});
for i = 1:numel(indices)
    currentIndex = indices(i);
    id = string(classif.roi(currentIndex).id);
    savedIndex = find(savedIds == id, 1);
    if isempty(savedIndex) || ...
            ~strcmpi(canonicalPath(saved.roi(savedIndex).path), ...
                canonicalPath(classif.roi(currentIndex).path)) || ...
            ~isequaln(double(saved.roi(savedIndex).value), ...
                double(classif.roi(currentIndex).value)) || ...
            ~isequal(effectiveBounds(saved, savedIndex), ...
                effectiveBounds(classif, currentIndex))
        error('cellLatentModel:BenchmarkClassifierSnapshotMismatch', ...
            ['ROI %s identity, source path or frame bounds differ from ' ...
             'the saved classifier. Save it before exporting; the exporter ' ...
             'will never call classiSave implicitly.'], id);
    end
end
end

function bounds = effectiveBounds(classif, index)
bounds = trainingBounds.resolve(classif, index);
if isempty(bounds)
    total = annotationManager.frameCount(classif.roi(index));
    bounds = [1 double(total)];
else
    bounds = double(bounds(:).');
end
end

function record = fileRecord(filename)
info = dir(filename);
if isempty(info)
    error('cellLatentModel:BenchmarkSourceNotMaterialized', ...
        'Cannot stat source file: %s', filename);
end
record = struct('path', normalizedPath(filename), ...
    'sha256', fileSha256(filename), 'bytes', double(info.bytes));
end

function record = manifestRecord(filename, root)
record = struct('path', relativePath(filename, root), ...
    'sha256', fileSha256(filename), 'bytes', fileBytes(filename));
end

function verifyPayloadRecords(root, inputRows, targetRows)
verifyRows(inputRows);
verifyRows(targetRows);
    function verifyRows(rows)
    for i = 1:numel(rows)
        filename = fullfile(root, ...
            strrep(rows(i).payload_path, '/', filesep));
        if ~isfile(filename) || ...
                ~strcmpi(fileSha256(filename), rows(i).payload_sha256)
            error('cellLatentModel:BenchmarkPayloadHashMismatch', ...
                'Benchmark payload hash mismatch: %s', filename);
        end
    end
    end
end

function assertInferenceManifestClean(value)
forbidden = {'ground_truth','groundtruth','stable_track','track_id', ...
    'parent','lineage','relation','approval','birth','end_event', ...
    'target','genealogy','identity'};
scanValue(value, forbidden, 'inputs_manifest');
end

function scanValue(value, forbidden, location)
if isstruct(value)
    names = fieldnames(value);
    for row = 1:numel(value)
        for i = 1:numel(names)
            assertNoForbiddenToken(names{i}, forbidden, location);
            scanValue(value(row).(names{i}), forbidden, ...
                [location '.' names{i}]);
        end
    end
elseif iscell(value)
    for i = 1:numel(value)
        scanValue(value{i}, forbidden, location);
    end
elseif ischar(value) || isstring(value)
    values = string(value);
    for i = 1:numel(values)
        assertNoForbiddenToken(char(values(i)), forbidden, location);
    end
end
end

function assertNoForbiddenToken(value, forbidden, location)
value = lower(char(string(value)));
for i = 1:numel(forbidden)
    if contains(value, forbidden{i})
        error('cellLatentModel:BenchmarkInputLeakage', ...
            'Forbidden inference token "%s" at %s.', forbidden{i}, location);
    end
end
end

function assertInferenceDirectoryClean(folder)
files = dir(fullfile(folder, '**', '*'));
files = files(~[files.isdir]);
for i = 1:numel(files)
    [~, name, ext] = fileparts(files(i).name);
    assertNoForbiddenToken([name ext], inputForbiddenTokens(), folder);
    filename = fullfile(files(i).folder, files(i).name);
    if strcmpi(ext, '.json')
        assertInferenceManifestClean(jsondecode(fileread(filename)));
    elseif any(strcmpi(ext, {'.h5','.hdf5'}))
        scanH5Names(h5info(filename), inputForbiddenTokens(), filename);
    else
        error('cellLatentModel:BenchmarkInputLeakage', ...
            'Unsupported file in inference directory: %s', filename);
    end
end
end

function tokens = inputForbiddenTokens()
tokens = {'ground_truth','groundtruth','stable_track','track_id', ...
    'parent','lineage','relation','approval','birth','end_event', ...
    'target','genealogy','identity'};
end

function scanH5Names(info, forbidden, filename)
for i = 1:numel(info.Datasets)
    assertNoForbiddenToken(info.Datasets(i).Name, forbidden, filename);
end
for i = 1:numel(info.Groups)
    assertNoForbiddenToken(info.Groups(i).Name, forbidden, filename);
    scanH5Names(info.Groups(i), forbidden, filename);
end
end

function assertSafeInputChannelName(value, label)
assertNoForbiddenToken(value, inputForbiddenTokens(), label);
end

function split = dirtyWarning(status)
if isempty(strtrim(status))
    split = {};
else
    split = {['DetecDiv worktree was not clean at export time: ' status]};
end
end

function [root, commit, status] = codeProvenance()
packageDir = fileparts(mfilename('fullpath'));
root = fileparts(fileparts(fileparts(packageDir)));
[ok, commit] = system(sprintf('git -C "%s" rev-parse HEAD', root));
if ok ~= 0
    error('cellLatentModel:BenchmarkCodeProvenanceFailed', ...
        'Cannot resolve the DetecDiv Git commit.');
end
commit = strtrim(commit);
[ok, status] = system(sprintf('git -C "%s" status --porcelain', root));
if ok ~= 0
    error('cellLatentModel:BenchmarkCodeProvenanceFailed', ...
        'Cannot inspect the DetecDiv Git worktree.');
end
status = strtrim(regexprep(status, '\s+', ' '));
end

function value = namespaceId(roiId, family, frames, approvalHash)
payload = sprintf('%s|%u|%s|%s|%d:%d|%s', char(string(roiId)), ...
    uint32(family.family_id), char(string(family.name)), ...
    char(string(family.mask_provider)), frames(1), frames(end), ...
    char(string(approvalHash)));
value = ['ns_' textSha256(payload)];
end

function value = validatedExportId(raw)
value = strtrim(char(string(raw)));
if isempty(regexp(value, '^[A-Za-z0-9][A-Za-z0-9_.-]*_v\d{3}$', 'once'))
    error('cellLatentModel:InvalidBenchmarkExportId', ...
        'Export ID must be a safe immutable name ending in _vNNN.');
end
end

function value = validatedLabelQuality(raw)
value = lower(strtrim(char(string(raw))));
allowed = {'human_ground_truth','published_ground_truth', ...
    'marker_derived_teacher','weak_supervision','model_prediction'};
if ~ismember(value, allowed)
    error('cellLatentModel:InvalidBenchmarkLabelQuality', ...
        'LabelQuality must be one of: %s.', strjoin(allowed, ', '));
end
end

function value = requiredText(raw, name)
value = strtrim(char(string(raw)));
if isempty(value) || strcmpi(value, '<none>') || strcmpi(value, '<auto>')
    error('cellLatentModel:MissingBenchmarkBinding', ...
        '%s must name one explicit DetecDiv resource.', name);
end
end

function value = trainingText(classif, name, fallback)
value = fallback;
try
    if isstruct(classif.trainingParam) && ...
            isfield(classif.trainingParam, name) && ...
            ~isempty(classif.trainingParam.(name))
        raw = classif.trainingParam.(name);
        while iscell(raw)
            if isempty(raw), raw = fallback; break; end
            raw = raw{end};
        end
        value = char(string(raw));
    end
catch
    value = fallback;
end
end

function tf = isTextCollection(value)
tf = ischar(value) || isstring(value) || iscell(value);
end

function values = textCollection(raw)
if isempty(raw)
    values = {};
elseif ischar(raw) || isstring(raw)
    values = cellstr(string(raw));
else
    values = cellfun(@(x)char(string(x)), raw, ...
        'UniformOutput', false);
end
values = values(~cellfun(@isempty, values));
end

function assertAllowedRoot(root, allowUnitTestRoot)
required = canonicalPath( ...
    'C:\Users\Gilles\SynologyDrive\Data\cell_latent_model');
if strcmpi(root, required), return; end
if allowUnitTestRoot
    testRoot = canonicalPath(tempdir);
    if isPathWithin(root, testRoot), return; end
end
error('cellLatentModel:BenchmarkRootNotAllowed', ...
    ['Scientific benchmark exports must be written below %s. Only unit ' ...
     'test fixtures may use a temporary root.'], required);
end

function tf = isPathWithin(pathValue, root)
pathValue = lower([canonicalPath(pathValue) filesep]);
root = lower([canonicalPath(root) filesep]);
tf = startsWith(pathValue, root);
end

function value = canonicalPath(raw)
value = char(java.io.File(char(string(raw))).getCanonicalPath());
end

function value = normalizedPath(raw)
value = strrep(char(string(raw)), '\', '/');
end

function value = relativePath(filename, root)
filename = canonicalPath(filename);
root = canonicalPath(root);
prefix = [root filesep];
if ~startsWith(lower(filename), lower(prefix))
    error('cellLatentModel:BenchmarkPathEscapesRoot', ...
        'Generated file escaped benchmark staging root: %s', filename);
end
value = strrep(filename(numel(prefix)+1:end), '\', '/');
end

function writeJsonNew(filename, value)
if isfile(filename) || isfolder(filename)
    error('cellLatentModel:ImmutableBenchmarkExists', ...
        'Refusing to overwrite benchmark artifact: %s', filename);
end
fid = fopen(filename, 'w');
if fid < 0
    error('cellLatentModel:BenchmarkWriteFailed', ...
        'Cannot create benchmark artifact: %s', filename);
end
cleanup = onCleanup(@() fclose(fid));
fwrite(fid, jsonencode(value, 'PrettyPrint', true), 'char');
end

function value = fileSha256(filename)
fid = fopen(filename, 'r');
if fid < 0
    error('cellLatentModel:BenchmarkHashReadFailed', ...
        'Cannot hash %s.', filename);
end
cleanup = onCleanup(@() fclose(fid));
value = bytesSha256(fread(fid, Inf, '*uint8'));
end

function value = textSha256(textValue)
value = bytesSha256(unicode2native(char(string(textValue)), 'UTF-8'));
end

function value = bytesSha256(bytes)
digest = java.security.MessageDigest.getInstance('SHA-256');
if ~isempty(bytes)
    digest.update(uint8(bytes(:)));
end
hash = typecast(digest.digest(), 'uint8');
value = lower(reshape(dec2hex(hash,2).',1,[]));
end

function value = fileBytes(filename)
info = dir(filename);
value = double(info.bytes);
end

function value = compactUuid()
value = regexprep(char(java.util.UUID.randomUUID), '-', '');
end

function value = utcIso8601()
value = char(datetime('now', 'TimeZone', 'UTC', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ss.SSSXXX'));
end

function removeFolder(folder)
if isfolder(folder)
    try rmdir(folder, 's'); catch, end
end
end
