function [spec,policy] = trainingParameterSpec(~)
%CELLLATENTMODEL.TRAININGPARAMETERSPEC Clear classifierGUI labels.
% Only parameters listed here are useful classifierGUI decisions. Other
% defaults remain part of the immutable backend configuration and are not
% deleted from saved classifiers.
policy = struct('showUnspecified',false);
spec = [ ...
    item('architectureVersion','Model architecture and version', ...
        'Training scope', ...
        ['detecdiv_composite_v1 exposes the existing tracking, lineage and ' ...
         'state runtimes through one classifier and one versioned bundle.'], ...
        {'Composite causal model v1','Lineage-only compatibility v1', ...
         'Composite causal model v1'}), ...
    item('trainTrackingActions','Train EDGE / APPEAR / END tracking', ...
        'Training scope', ...
        'Updates the existing latent tracking-action head from reviewed stable track IDs.'), ...
    item('trainMotherNull','Train mother / NULL lineage', ...
        'Training scope', ...
        'Updates the existing physical-time parent-or-NULL head.'), ...
    item('stateUpdateMode','Frozen biological-state module at inference', ...
        'Training scope', ...
        ['The promoted BF/geometry state student remains frozen unless an ' ...
         'audited state-training dataset is configured separately.'], ...
        {'Promoted frozen BF state student','No biological-state update', ...
         'Promoted frozen BF state student'}), ...
    item('trainingObjective','Lineage-head implementation', ...
        'Mother/NULL head > Architecture', ...
        ['Used when mother/NULL training is selected. The composite preset ' ...
         'uses the physical-time head.'], ...
        {'Legacy relation ensemble','Physical-time mother/NULL head', ...
         'Physical-time mother/NULL head'}), ...
    item('trackingTopK','Predecessors retained per detection (top-K)', ...
        'Tracking head > Candidates','Nearest detections retained from the previous frame.'), ...
    item('trackingMinimumTruthOverlap','Minimum instance / GT overlap', ...
        'Tracking head > GT quality', ...
        'Minimum fraction of an instance assigned to one reviewed stable track ID.'), ...
    item('trackingMinimumDetectionCoverage','Minimum annotated-instance coverage', ...
        'Tracking head > GT quality', ...
        'Formatting stops when too few detected instances map to reviewed tracking GT.'), ...
    item('trackingInitialModelSource','Starting weights', ...
        'Tracking head > Initialization','Promoted checkpoint, custom checkpoint, or random initialization.', ...
        {'Promoted cross-domain tracker','Custom checkpoint','Random initialization', ...
         'Promoted cross-domain tracker'}), ...
    item('trackingInitialCheckpoint','Custom checkpoint path', ...
        'Tracking head > Initialization', ...
        'Used only when Initial tracking weights is Custom checkpoint.'), ...
    item('trackingEpochs','Epochs','Tracking head > Optimization', ...
        'Maximum EDGE/APPEAR/END optimization epochs.'), ...
    item('trackingLearningRate','Learning rate', ...
        'Tracking head > Optimization','AdamW learning rate for tracking actions.'), ...
    item('trackingWeightDecay','Weight decay', ...
        'Tracking head > Optimization','AdamW weight decay for the tracking head.'), ...
    item('trackingAssociationLossWeight','EDGE — predecessor-association weight', ...
        'Tracking head > Loss weights','Weight for predecessor association decisions.'), ...
    item('trackingAppearanceLossWeight','APPEAR — new-track weight', ...
        'Tracking head > Loss weights','Weight for starting a new trajectory.'), ...
    item('trackingEndLossWeight','END — track-termination weight', ...
        'Tracking head > Loss weights','Weight for terminating an old trajectory.'), ...
    item('trackingSuccessorLossWeight','EDGE vs END — successor-group weight', ...
        'Tracking head > Loss weights', ...
        ['Optional auxiliary loss comparing every outgoing EDGE with END. ' ...
        'Zero keeps the legacy objective; ambiguous, incomplete, or ' ...
        'no-candidate successors are excluded and audited.']), ...
    item('frameIntervalMinutes','Frame interval (minutes)','Shared > Dataset', ...
        'Mandatory for the physical-time mother/NULL objective.'), ...
    item('trainingDomain','Biological and acquisition domain','Shared > Dataset', ...
        'Auditable domain label; Project47 cannot select a model.'), ...
    item('groundTruthFamily','Reviewed mother/NULL family','Mother/NULL head > Ground truth', ...
        'Cell-model family containing explicit mother-child links.'), ...
    item('validationFraction','Automatic ROI validation fraction','Shared > Validation', ...
        'Held-out ROI fraction when no validation split is configured.'), ...
    item('continuousVariant','Observation modalities','Mother/NULL head > Architecture', ...
        'Geometry-only or all explicitly observed modalities.'), ...
    item('decisionLatencyMinutes','Decision delay after appearance (minutes)', ...
        'Mother/NULL head > Temporal context','Physical time after appearance used for the decision.'), ...
    item('temporalWindowMinutes','Observation horizon (minutes)', ...
        'Mother/NULL head > Temporal context','Maximum future observation horizon.'), ...
    item('continuousStateDim','Per-cell memory size','Mother/NULL head > Architecture', ...
        'Hidden state size for the physical-time lineage head.'), ...
    item('continuousCausalFeedback','Feed earlier predicted events back into the model', ...
        'Mother/NULL head > Architecture','Feeds earlier predicted relations into later decisions.'), ...
    item('epochs','Epochs','Mother/NULL head > Optimization','Maximum optimization epochs.'), ...
    item('learningRate','Learning rate','Mother/NULL head > Optimization','AdamW learning rate.'), ...
    item('weightDecay','Weight decay','Mother/NULL head > Optimization','AdamW weight decay.'), ...
    item('motherNullEarlyStoppingPatience', ...
        'Early stopping patience (epochs)', ...
        'Mother/NULL head > Model selection', ...
        ['Stop when validation NLL has not improved meaningfully for this ' ...
         'many epochs. Epoch 0 is always an eligible checkpoint.']), ...
    item('motherNullEarlyStoppingMinDelta', ...
        'Minimum validation NLL improvement', ...
        'Mother/NULL head > Model selection', ...
        'Validation decrease required to reset early-stopping patience.'), ...
    item('device','Compute device','Shared > Runtime','cuda uses the GPU when available.'), ...
    item('modelName','New immutable model-bundle name','Output bundle', ...
        'One bundle containing explicit tracking, lineage and frozen-state component references.') ...
    ];
end

function out=item(param,label,group,tip,choiceLabels)
if nargin<5,choiceLabels={};end
out=struct('param',param,'label',label,'group',group,'tip',tip, ...
    'choiceLabels',{choiceLabels});
end
