function spec = trainingParameterSpec(~)
%CELLLATENTMODEL.TRAININGPARAMETERSPEC Clear classifierGUI labels.
spec = [ ...
    item('architectureVersion','Latent architecture/version', ...
        'Training scope', ...
        ['detecdiv_composite_v1 exposes the existing tracking, lineage and ' ...
         'state runtimes through one classifier and one versioned bundle.'], ...
        {'Composite causal model v1','Lineage-only compatibility v1', ...
         'Composite causal model v1'}), ...
    item('trainTrackingActions','Train EDGE / APPEAR / END tracking', ...
        'Training scope', ...
        'Updates the existing latent tracking-action head from reviewed stable track IDs.'), ...
    item('trainMotherNull','Train mother / NULL lineage', ...
        'Training scope', ...
        'Updates the existing physical-time parent-or-NULL head.'), ...
    item('stateUpdateMode','Biological-state update at inference', ...
        'Training scope', ...
        ['The promoted BF/geometry state student remains frozen unless an ' ...
         'audited state-training dataset is configured separately.'], ...
        {'Promoted frozen BF state student','No biological-state update', ...
         'Promoted frozen BF state student'}), ...
    item('trainingObjective','Mother/NULL head architecture', ...
        'Lineage architecture', ...
        ['Used when mother/NULL training is selected. The composite preset ' ...
         'uses the physical-time head.'], ...
        {'Legacy relation ensemble','Physical-time mother/NULL head', ...
         'Physical-time mother/NULL head'}), ...
    item('trackingTopK','Tracking predecessor candidates', ...
        'Tracking architecture','Nearest detections retained from the previous frame.'), ...
    item('trackingInitialModelSource','Initial tracking weights', ...
        'Tracking architecture','Promoted checkpoint, custom checkpoint, or random initialization.', ...
        {'Promoted cross-domain tracker','Custom checkpoint','Random initialization', ...
         'Promoted cross-domain tracker'}), ...
    item('trackingEpochs','Tracking epochs','Tracking optimization', ...
        'Maximum EDGE/APPEAR/END optimization epochs.'), ...
    item('trackingLearningRate','Tracking learning rate', ...
        'Tracking optimization','AdamW learning rate for tracking actions.'), ...
    item('trackingAppearanceLossWeight','APPEAR loss weight', ...
        'Tracking optimization','Weight for starting a new trajectory.'), ...
    item('trackingEndLossWeight','END loss weight', ...
        'Tracking optimization','Weight for terminating an old trajectory.'), ...
    item('frameIntervalMinutes','Minutes between frames','Data', ...
        'Mandatory for the physical-time mother/NULL objective.'), ...
    item('trainingDomain','Biological/acquisition domain','Data', ...
        'Auditable domain label; Project47 cannot select a model.'), ...
    item('groundTruthFamily','Reviewed mother-child GT family','Data', ...
        'Cell-model family containing explicit mother-child links.'), ...
    item('validationFraction','ROI validation fraction','Validation', ...
        'Held-out ROI fraction when no validation split is configured.'), ...
    item('continuousVariant','Physical-time observation set','Lineage architecture', ...
        'Geometry-only or all explicitly observed modalities.'), ...
    item('decisionLatencyMinutes','Mother-decision latency (minutes)', ...
        'Lineage architecture','Physical time after appearance used for the decision.'), ...
    item('temporalWindowMinutes','Observation horizon (minutes)', ...
        'Lineage architecture','Maximum future observation horizon.'), ...
    item('continuousStateDim','Cell-memory dimension','Lineage architecture', ...
        'Hidden state size for the physical-time lineage head.'), ...
    item('continuousCausalFeedback','Reuse prior predicted lineage events', ...
        'Lineage architecture','Feeds earlier predicted relations into later decisions.'), ...
    item('epochs','Training epochs','Optimization','Maximum optimization epochs.'), ...
    item('learningRate','Learning rate','Optimization','AdamW learning rate.'), ...
    item('weightDecay','Weight decay','Optimization','AdamW weight decay.'), ...
    item('device','Training device','Runtime','cuda uses the GPU when available.'), ...
    item('modelName','Immutable composite model version','Artifact', ...
        'One bundle containing explicit tracking, lineage and frozen-state component references.') ...
    ];
end

function out=item(param,label,group,tip,choiceLabels)
if nargin<5,choiceLabels={};end
out=struct('param',param,'label',label,'group',group,'tip',tip, ...
    'choiceLabels',{choiceLabels});
end
