function spec = trainingSpec(~)
%CELLLATENTMODEL.TRAININGSPEC Typed ROI resources used for model training.

spec = [ ...
    binding('trackChannelName', 'channel', 'mask_roi_image', ...
        'Reviewed tracked-mask GT', true, false, false, ...
        ['Indexed GT mask used for training. For managed annotations this ' ...
         'is the editable <classifier id>_cell channel.'], ...
        'legacyFallback', 'classifierInputChannels'), ...
    binding('groundTruthFamily', 'cellModelFamily', 'lineage_ground_truth', ...
        'Reviewed lineage GT', true, true, false, ...
        'Reviewed cell-model family containing the training parent-child relations.', ...
        'autoValue', '<auto>'), ...
    binding('brightfieldChannelName', 'channel', 'brightfield_image', ...
        'Brightfield image', false, false, true, ...
        'Brightfield observation used by continuous-lineage training.'), ...
    binding('gfpChannelName', 'channel', 'legacy_gfp_fluorescence', ...
        'Legacy GFP image', false, false, true, ...
        'Optional GFP observation used by the legacy relation ensemble.'), ...
    binding('nucleusChannelName', 'channel', 'division_nucleus_fluorescence', ...
        'Division/nucleus image', false, false, true, ...
        'Optional explicitly typed division/nucleus fluorescence.'), ...
    binding('budneckChannelName', 'channel', 'bud_neck_fluorescence', ...
        'Bud-neck image', false, false, true, ...
        'Optional explicitly typed bud-neck fluorescence.') ...
    ];
end

function item = binding(param, type, role, label, required, allowAuto, allowNone, tip, varargin)
item = classifierBinding.newBinding( ...
    'param', param, 'type', type, 'role', role, 'label', label, ...
    'tip', tip, 'required', required, 'allowAuto', allowAuto, ...
    'allowNone', allowNone, varargin{:});
end
