function spec = trainingSpec(classif)
%CELLLATENTMODEL.TRAININGSPEC Typed ROI resources used for model training.

tp=cellLatentModel.utils.defaultTrainingParam();
try
    if isstruct(classif.trainingParam)
        tp=cellLatentModel.utils.applyOverrides(tp,classif.trainingParam);
    end
catch
end
composite=strcmpi(textValue(tp.architectureVersion),'detecdiv_composite_v1');
needsTracking=composite && logical(tp.trainTrackingActions);
needsLineage=logical(tp.trainMotherNull);

spec = [ ...
    binding('instanceChannelName', 'channel', 'mask_roi_image', ...
        '[INPUT] Frame-local instance masks', needsTracking, false, false, ...
        ['Segmentation masks before tracking. Labels may be reused between ' ...
         'frames and are never interpreted as stable identities.'], ...
        'quality','input','semantic','frame_local_instances'), ...
    binding('trackChannelName', 'channel', 'mask_roi_image', ...
        '[GT] Reviewed stable identities and spatial masks', ...
        needsTracking || needsLineage, false, false, ...
        ['The channel supplies frame-local mask labels; persistent GT identity ' ...
         'is read from cellModel.instances.track_id.'], ...
        'legacyFallback', 'classifierInputChannels', ...
        'quality','gt','semantic','stable_tracks'), ...
    binding('groundTruthFamily', 'cellModelFamily', 'lineage_ground_truth', ...
        '[GT] Reviewed mother/NULL lineage', needsLineage, true, false, ...
        'Reviewed cell-model family containing the training parent-child relations.', ...
        'autoValue', '<auto>', 'quality','gt','semantic','mother_null_lineage'), ...
    binding('brightfieldChannelName', 'channel', 'brightfield_image', ...
        '[INPUT] Brightfield image', false, false, true, ...
        'Brightfield observation used by continuous-lineage training.', ...
        'quality','input','semantic','brightfield_image'), ...
    binding('gfpChannelName', 'channel', 'legacy_gfp_fluorescence', ...
        '[INPUT] Legacy GFP image', false, false, true, ...
        'Optional GFP observation used by the legacy relation ensemble.', ...
        'quality','input','semantic','legacy_gfp'), ...
    binding('nucleusChannelName', 'channel', 'division_nucleus_fluorescence', ...
        '[INPUT] Division/nucleus image', false, false, true, ...
        'Optional explicitly typed division/nucleus fluorescence.', ...
        'quality','input','semantic','division_nucleus_marker'), ...
    binding('budneckChannelName', 'channel', 'bud_neck_fluorescence', ...
        '[INPUT] Bud-neck image', false, false, true, ...
        'Optional explicitly typed bud-neck fluorescence.', ...
        'quality','input','semantic','bud_neck_marker') ...
    ];
end

function value=textValue(value)
while iscell(value),if isempty(value),value='';return;else,value=value{end};end,end
value=strtrim(char(string(value)));
end

function item = binding(param, type, role, label, required, allowAuto, allowNone, tip, varargin)
item = classifierBinding.newBinding( ...
    'param', param, 'type', type, 'role', role, 'label', label, ...
    'tip', tip, 'required', required, 'allowAuto', allowAuto, ...
    'allowNone', allowNone, varargin{:});
end
