function paramout = setparam(ctx)
%OBJECTMETRICS.SETPARAM Defaults for object-centric metric materialization.
if nargin<1||isempty(ctx), ctx=struct(); end
paramout=struct( ...
    'inputData','channel_quantification', ...
    'geometryData','<auto>', ...
    'family','<auto>', ...
    'maskIndexVariable','', ...
    'outputName','object_metrics', ...
    'deriveGrowth',true, ...
    'sizeVariable','Area_Cell', ...
    'frameIntervalMinutes',1, ...
    'growthWindow',5, ...
    'tip',{{ ...
        'computeMetrics dataseries groupid', ...
        'Geometry dataseries groupid or <auto> for the family mask provider', ...
        'Cell-model family name, provider, ID, or <auto>', ...
        'Optional MaskIdx_* binding; empty resolves from the family provider', ...
        'Output long-table dataseries groupid', ...
        'Add per-track and mother-bud growth measurements', ...
        'Size variable used for growth, usually Area_Cell or Vol_Cell', ...
        'Time between frames in minutes', ...
        'Odd local window used by the robust Theil-Sen growth slope'}});
if isstruct(ctx)&&isfield(ctx,'params')&&isstruct(ctx.params)
    names=fieldnames(ctx.params);
    for i=1:numel(names), paramout.(names{i})=ctx.params.(names{i}); end
end
end
