function paramout = setparam(ctx)
% computeRLS.setparam  Build parameters for computeRLS processor.

if nargin < 1 || isempty(ctx)
    ctx = struct();
end

listout = {};
ctxParam = struct();
if isstruct(ctx) && isfield(ctx,'params') && isstruct(ctx.params)
    ctxParam = ctx.params;
end

if isfield(ctx,'useProvidedDataSeries') && ctx.useProvidedDataSeries
    if isfield(ctx,'classification_data')
        listout = ctx.classification_data;
    elseif isfield(ctx,'classificationData')
        listout = ctx.classificationData;
    elseif isfield(ctxParam,'classification_data')
        listout = ctxParam.classification_data;
    elseif isfield(ctxParam,'classificationData')
        listout = ctxParam.classificationData;
    end
elseif isfield(ctx,'classification_data') && ~isempty(ctx.classification_data)
    listout = ctx.classification_data;
elseif isfield(ctx,'classificationData') && ~isempty(ctx.classificationData)
    listout = ctx.classificationData;
elseif isfield(ctxParam,'classification_data') && ~isempty(ctxParam.classification_data)
    listout = ctxParam.classification_data;
elseif isfield(ctxParam,'classificationData') && ~isempty(ctxParam.classificationData)
    listout = ctxParam.classificationData;
else
    try
        listout = listROIDataID("classification");
    catch
        listout = {};
    end
end

listout = normalizeChoiceList(listout);

if isempty(listout)
    listout = {''};
end

listout{end+1} = listout{end};

tip = { ...
    'Classification data output name', ...
    'Arrest threshold in expected division periods if ExpectedDivisionPeriod is set; otherwise frames', ...
    'Death threshold frame number', ...
    'Clog threshold frame number', ...
    'Empty Threshold Discard frame number', ...
    'EmptyThresholdNext', ...
    'State decoder: off, viterbi, or median', ...
    'Expected division/budding period in frames', ...
    'Minimum division/budding interval in frames', ...
    'Minimum interval factor when using expected period', ...
    'Median decoder/filter window in frames', ...
    'Viterbi live-state switch penalty', ...
    'Viterbi terminal-state transition penalty', ...
    'Viterbi unexpected transition penalty', ...
    'Viterbi empty-to-live refill penalty', ...
    'QC low-margin frame threshold', ...
    'QC minimum mean probability margin', ...
    'QC maximum low-confidence frame fraction' ...
    };

paramout = struct();
paramout.classification_data = listout;
paramout.ArrestThreshold = 3;
paramout.DeathThreshold = 3;
paramout.ClogThreshold = 1;
paramout.EmptyThresholdDiscard = 500;
paramout.EmptyThresholdNext = 100;
paramout.StateDecoder = {'off','viterbi','median','off'};
paramout.ExpectedDivisionPeriod = 60;
paramout.MinDivisionInterval = NaN;
paramout.MinDivisionIntervalFactor = 0.5;
paramout.MedianFilterWindow = 3;
paramout.ViterbiLiveSwitchPenalty = 0.10;
paramout.ViterbiTerminalPenalty = 0.25;
paramout.ViterbiUnexpectedTransitionPenalty = 1.00;
paramout.ViterbiRefillPenalty = 0.50;
paramout.QCLowMarginThreshold = 0.05;
paramout.QCMinMeanMargin = 0.05;
paramout.QCMaxLowConfidenceFraction = 0.50;
paramout.paramTooltip = computeRLSTooltips();
paramout.tip = tip;
end

function tips = computeRLSTooltips()
tips = struct();
tips.classification_data = tooltipLines({ ...
    'Classifier dataseries used as input, usually div_1.', ...
    'Default: first available classification dataseries / div_1 when available.', ...
    'Typical values: div_1, GT_div_1.', ...
    'Unit: dataseries group id.'});
tips.ArrestThreshold = tooltipLines({ ...
    'Long live interval without budding required to call cell-cycle arrest.', ...
    'Default: 3.', ...
    'Typical range: 2-4 division periods.', ...
    'Unit: division periods when ExpectedDivisionPeriod is set; otherwise frames.'});
tips.DeathThreshold = tooltipLines({ ...
    'Minimum continuous dead-state duration required to validate death.', ...
    'Default: 3.', ...
    'Typical range: 2-5.', ...
    'Unit: frames.'});
tips.ClogThreshold = tooltipLines({ ...
    'Minimum continuous clog-state duration required to validate clogging.', ...
    'Default: 1.', ...
    'Typical range: 1-5.', ...
    'Unit: frames.'});
tips.EmptyThresholdDiscard = tooltipLines({ ...
    'Legacy empty-cavity discard threshold kept for compatibility; not currently used by computeRLS core.', ...
    'Default: 500.', ...
    'Typical range: experiment-length dependent, often 100-500.', ...
    'Unit: frames.'});
tips.EmptyThresholdNext = tooltipLines({ ...
    'If the ROI becomes empty soon after birth, search after the empty interval for a refilled trajectory.', ...
    'Default: 100.', ...
    'Typical range: 30-150, or about 1-2 expected division periods.', ...
    'Unit: frames after birth.'});
tips.StateDecoder = tooltipLines({ ...
    'State-sequence decoder applied before event detection.', ...
    'Default: off.', ...
    'Typical values: off, viterbi, median.', ...
    'Unit: categorical option.'});
tips.ExpectedDivisionPeriod = tooltipLines({ ...
    'Expected budding/division period P used to scale arrest and minimum division interval rules.', ...
    'Default: 60.', ...
    'Typical range: 40-90, adjust to acquisition and strain.', ...
    'Unit: frames.'});
tips.MinDivisionInterval = tooltipLines({ ...
    'Explicit minimum accepted interval between two budding events; NaN means derive it from ExpectedDivisionPeriod.', ...
    'Default: NaN.', ...
    'Typical range: P/2 to P, or NaN to use the factor rule.', ...
    'Unit: frames.'});
tips.MinDivisionIntervalFactor = tooltipLines({ ...
    'Factor applied to ExpectedDivisionPeriod when MinDivisionInterval is NaN.', ...
    'Default: 0.5.', ...
    'Typical range: 0.4-0.7.', ...
    'Unit: fraction of expected division period.'});
tips.MedianFilterWindow = tooltipLines({ ...
    'Window used by StateDecoder=median to smooth isolated label flips.', ...
    'Default: 3.', ...
    'Typical range: 3-5, preferably odd.', ...
    'Unit: frames.'});
tips.ViterbiLiveSwitchPenalty = tooltipLines({ ...
    'Penalty for switching between compatible live states in the Viterbi decoder.', ...
    'Default: 0.10.', ...
    'Typical range: 0-0.5.', ...
    'Unit: log-score penalty.'});
tips.ViterbiTerminalPenalty = tooltipLines({ ...
    'Penalty for entering terminal/empty states from live states in the Viterbi decoder.', ...
    'Default: 0.25.', ...
    'Typical range: 0-1.', ...
    'Unit: log-score penalty.'});
tips.ViterbiUnexpectedTransitionPenalty = tooltipLines({ ...
    'Penalty for biologically unexpected state transitions in the Viterbi decoder.', ...
    'Default: 1.00.', ...
    'Typical range: 0.5-2.', ...
    'Unit: log-score penalty.'});
tips.ViterbiRefillPenalty = tooltipLines({ ...
    'Penalty for transitions from empty back to live states, allowing trap refill when supported by probabilities.', ...
    'Default: 0.50.', ...
    'Typical range: 0.2-1.5.', ...
    'Unit: log-score penalty.'});
tips.QCLowMarginThreshold = tooltipLines({ ...
    'Frame is considered ambiguous when top1_probability - top2_probability is below this margin.', ...
    'Default: 0.05.', ...
    'Typical range: 0.02-0.15.', ...
    'Unit: probability margin.'});
tips.QCMinMeanMargin = tooltipLines({ ...
    'Minimum mean top1-top2 probability margin required for each RLS interval.', ...
    'Default: 0.05.', ...
    'Typical range: 0.02-0.15.', ...
    'Unit: probability margin.'});
tips.QCMaxLowConfidenceFraction = tooltipLines({ ...
    'Maximum fraction of ambiguous frames allowed in each RLS interval.', ...
    'Default: 0.50.', ...
    'Typical range: 0.20-0.50.', ...
    'Unit: fraction of frames.'});
end

function txt = tooltipLines(lines)
txt = strjoin(lines, newline);
end

function out = normalizeChoiceList(v)
    if isempty(v)
        out = {};
        return;
    end

    if ischar(v)
        v = cellstr(v);
    elseif isstring(v) || isnumeric(v) || islogical(v) || iscategorical(v)
        v = cellstr(string(v(:)));
    elseif ~iscell(v)
        v = {char(string(v))};
    end

    out = {};
    for i = 1:numel(v)
        item = v{i};
        if isempty(item)
            continue;
        end
        if ischar(item)
            out{end+1} = item; %#ok<AGROW>
        elseif isstring(item) || isnumeric(item) || islogical(item) || iscategorical(item)
            vals = cellstr(string(item(:)));
            out = [out vals(:)']; %#ok<AGROW>
        end
    end

    if isempty(out)
        out = {};
        return;
    end

    out = cellfun(@(x) char(strtrim(string(x))), out(:)', 'UniformOutput', false);
    out = out(~cellfun(@isempty, out));
    out = unique(out, 'stable');
end
