function names = featureNames()
%BUDMOTHERLINKER.UTILS.FEATURENAMES Canonical LYN-16 feature order.
names = { ...
    'dist_0','dist_std','poly_fit_budcm_budpt', ...
    'poly_fit_expansion_vector','position_bud_std', ...
    'position_bud_max','position_bud_min','position_bud_last', ...
    'position_bud_first','orientation_bud_std', ...
    'orientation_bud_max','orientation_bud_min', ...
    'orientation_bud_last','orientation_bud_first', ...
    'orientation_bud_last_minus_first','plyfit_orientation_bud'};
end
