function spec = executionSpec(classif)
%CELLLATENTTRACKER.EXECUTIONSPEC Pipeline/runtime contract.
if nargin < 1, classif = []; end
p = cellLatentTracker.utils.defaultExecutionParam();
try
    if ~isempty(classif) && isprop(classif,'executionParam') && ...
            isstruct(classif.executionParam)
        p = cellLatentModel.utils.applyOverrides(p,classif.executionParam);
    end
catch
end
spec = struct();
spec.category = 'Pixel';
spec.defaultClasses = {'tracklet'};
spec.summary = ['Latent stable-ID tracker: consumes frame-local instances and ' ...
    'optional brightfield, then solves EDGE/APPEAR/END actions. Segmentation, ' ...
    'Trackastra, and mother/NULL lineage remain separate pipeline nodes.'];
spec.staticKeys = {'topK','frameIntervalMinutes','device', ...
    'solverTimeLimitSeconds','debug'};
spec.artifactKeys = {'checkpointDir'};
spec.outputKeys = {'outputName'};
spec.defaultImportKeys = [spec.staticKeys spec.outputKeys];
spec.outputProvenance = struct('quality','pred', ...
    'producer','cellLatentTracker','semantic','stable_tracks', ...
    'template','results_<outputName>');
spec.defaults = p;
spec.labels = struct( ...
    'imageChannelName','[INPUT] Brightfield image (optional)', ...
    'instanceChannelName','[INPUT] Frame-local instance masks', ...
    'outputName','[PRED] Stable-track output name', ...
    'checkpointDir','Trained latent-tracker checkpoint', ...
    'topK','Candidate predecessors per cell', ...
    'frameIntervalMinutes','Minutes between frames', ...
    'device','Inference device', ...
    'solverTimeLimitSeconds','Solver time limit (seconds)', ...
    'debug','Verbose diagnostics');
spec.tips = struct( ...
    'imageChannelName','Optional intensity image used by the trained checkpoint.', ...
    'instanceChannelName',['Indexed segmentation masks before tracking. ' ...
        'Labels may be frame-local.'], ...
    'outputName',['Physical PRED ROI channel is results_<outputName>. ' ...
        'The canonical new name is results_pred_latent_tracker_tracks.'], ...
    'checkpointDir','Folder containing manifest.json and tracking_edge_residual.pt.', ...
    'topK','Must match the formatted candidate policy used for training.', ...
    'frameIntervalMinutes','Physical acquisition interval.', ...
    'device','automatic chooses CUDA when available.', ...
    'solverTimeLimitSeconds','Maximum causal assignment solve time.', ...
    'debug','Print tracker integration details.');
spec.choices = struct('device',{{'automatic','cuda','cpu'}}, ...
    'debug',{{false,true}});
end
