function spec = trainingSpec(~)
%CELLLATENTTRACKER.TRAININGSPEC Typed training inputs.
spec = [ ...
    classifierBinding.newBinding( ...
        'param','instanceChannelName', 'type','channel', ...
        'role','mask_roi_image', 'quality','input', ...
        'semantic','frame_local_instances', ...
        'label','[INPUT] Frame-local instance masks', ...
        'required',true, 'legacyFallback','classifierInputChannels', ...
        'tip',['Segmentation masks before tracking. IDs may restart on every ' ...
               'frame; these masks are model inputs, never tracking truth.']), ...
    classifierBinding.newBinding( ...
        'param','groundTruthChannelName', 'type','channel', ...
        'role','tracked_mask_ground_truth', 'quality','gt', ...
        'semantic','stable_tracks', ...
        'label','[GT] Reviewed stable-ID tracks (target)', ...
        'required',true, 'allowAuto',true, ...
        'tip',['Reviewed mask geometry; persistent identity is read from ' ...
               'cellModel.instances.track_id. The same mask channel may be ' ...
               'used as INPUT geometry without leaking IDs. An ID change ' ...
               'creates END + APPEAR targets.']), ...
    classifierBinding.newBinding( ...
        'param','brightfieldChannelName', 'type','channel', ...
        'role','brightfield_image', 'quality','input', ...
        'semantic','brightfield_image', ...
        'label','[INPUT] Brightfield image (optional feature)', ...
        'required',false, 'allowNone',true, ...
        'tip','Optional brightfield appearance features for every instance.') ...
    ];
end
