function scope = trainingScopeSpec(~)
%CELLLATENTTRACKER.TRAININGSCOPESPEC User-facing ownership contract.
scope=classifierBinding.newTrainingScope( ...
    'module','cellLatentTracker', ...
    'displayName','Latent tracker — EDGE/APPEAR/END stable IDs', ...
    'objective','Choose continuation, new-track appearance, or track termination for every detection.', ...
    'trainedComponents',{'EDGE association head','APPEAR new-track head','END termination head'}, ...
    'frozenComponents',{'CellposeSAM','Trackastra','mother/NULL lineage linker'}, ...
    'datasetUnit','Frame-local instances plus optional brightfield, supervised by stable-ID tracking GT.', ...
    'splitPolicy','Whole-ROI validation held out from selected train ROIs; test ROIs are untouched.', ...
    'outputParameter','outputName','outputQuality','pred', ...
    'outputSemantic','stable cell tracks', ...
    'outputTemplate','results_<outputName>', ...
    'canonicalOutput','results_pred_latent_tracker_tracks', ...
    'notes',{'GT IDs are never consumed at inference.'});
end
