function spec = trainingParameterSpec(~)
%CELLLATENTTRACKER.TRAININGPARAMETERSPEC Human-readable classifierGUI metadata.
spec = [ ...
    item('validationFraction','ROI validation fraction','Validation', ...
        'Held-out ROI fraction when no explicit validation split exists.'), ...
    item('frameIntervalMinutes','Minutes between frames','Data', ...
        'Physical acquisition interval recorded in the dataset manifest.'), ...
    item('trainingDomain','Biological/acquisition domain','Data', ...
        'Auditable domain name for this training series.'), ...
    item('topK','Candidate predecessors per cell','Tracking candidates', ...
        'Nearest detections retained from frame t-1 before GT labels are consulted.'), ...
    item('minimumTruthOverlap','Minimum instance/GT overlap','GT mapping', ...
        'Minimum fraction of an instance covered by one stable GT ID.'), ...
    item('minimumDetectionCoverage','Minimum mapped-instance coverage','GT mapping', ...
        'Formatting fails below this mapped detection fraction.'), ...
    item('initialModelSource','Initial tracker weights','Model initialization', ...
        ['promoted_cross_domain copies the frozen promoted tracker into a new ' ...
         'version; it never modifies the source checkpoint.'], ...
        {'Promoted cross-domain tracker (recommended)','Custom checkpoint', ...
         'Random initialization', ...
         'Promoted cross-domain tracker (recommended)'}), ...
    item('initialCheckpoint','Custom initial checkpoint','Model initialization', ...
        'Used only when initialModelSource is checkpoint.'), ...
    item('epochs','Training epochs','Optimization','Maximum optimization epochs.'), ...
    item('learningRate','Learning rate','Optimization','AdamW learning rate.'), ...
    item('weightDecay','Weight decay','Optimization','AdamW weight decay.'), ...
    item('hiddenDim','Latent hidden dimension','Architecture', ...
        'Must remain 32 when initialized from the promoted cross-domain tracker.'), ...
    item('dropout','Dropout','Architecture','Training dropout probability.'), ...
    item('associationLossWeight','EDGE loss weight','Losses', ...
        'Weight for predecessor association versus APPEAR.'), ...
    item('appearanceLossWeight','APPEAR loss weight','Losses', ...
        'Weight for starting a new trajectory instead of reusing an ID.'), ...
    item('endLossWeight','END loss weight','Losses', ...
        'Weight for terminating an old trajectory.'), ...
    item('device','Training device','Runtime','automatic uses CUDA when available.'), ...
    item('modelName','Immutable model version name','Artifact', ...
        'Use a new vNNN name for every completed training artifact.') ...
    ];
end

function out = item(param,label,group,tip,choiceLabels)
if nargin < 5, choiceLabels = {}; end
out = struct('param',param,'label',label,'group',group,'tip',tip, ...
    'choiceLabels',{choiceLabels});
end
