function paramout = setparam(ctx)
% singleCellOscillations.setparam  Default parameters for the processor.

if nargin < 1 || isempty(ctx)
    ctx = struct();
end

paramout = struct();

paramout.classification_data = localDefaultSelection(ctx, 'classification_data', 'div_1');
paramout.fluorescence_data = localDefaultSelection(ctx, 'fluorescence_data', 'channel_quantification');
paramout.labelColumn = 'labels';
paramout.fluorescenceColumn = 'Ratio_Mean_NoBckg_channel002_z001_channel001_z001_cyto';
paramout.cellValueReducer = 'mean';
paramout.frameStart = [];
paramout.frameEnd = [];
paramout.framePeriod = 1;
paramout.timeUnit = 'frames';
paramout.baselineMethod = 'moving_mean';
paramout.baselineWindow = 50;
paramout.baselineEndpoints = 'shrink';
paramout.cycleBoundaryMode = 'label_transition';
paramout.transitionFrom = 'large';
paramout.transitionTo = 'small';
paramout.minCycleLength = 10;
paramout.maxCycleLength = 200;
paramout.normFrames = 100;
paramout.interpolationMethod = 'linear';
paramout.allowExtrapolation = true;
paramout.traceOutputName = 'osc_detrended_trace';
paramout.normalizedCyclesOutputName = 'osc_normalized_cycles';
paramout.cycleMetadataOutputName = 'osc_cycle_metadata';
paramout.writeArtifacts = false;
paramout.outputDir = '';
paramout.workbookName = 'single_cell_oscillations.xlsx';
paramout.runId = '';
paramout.verbose = true;
paramout.tip = buildTips();
end

function value = localDefaultSelection(ctx, fieldName, fallback)
value = fallback;
if isstruct(ctx) && isfield(ctx, fieldName) && ~isempty(ctx.(fieldName))
    value = ctx.(fieldName);
elseif isstruct(ctx) && isfield(ctx, 'params') && isstruct(ctx.params) && isfield(ctx.params, fieldName) && ~isempty(ctx.params.(fieldName))
    value = ctx.params.(fieldName);
end
if isstring(value)
    value = cellstr(value);
elseif ischar(value)
    value = {value};
end
if ~iscell(value)
    value = {char(string(value))};
end
end

function tip = buildTips()
tip = { ...
    'Classification dataseries name, usually div_1', ...
    'Fluorescence dataseries name, usually channel_quantification', ...
    'Column containing state labels', ...
    'Column containing the fluorescence trace to analyze', ...
    'How to reduce cell-valued fluorescence traces', ...
    'First selected frame; empty means first available', ...
    'Last selected frame; empty means last available', ...
    'Time between frames', ...
    'Time unit label', ...
    'Baseline method: moving_mean, moving_median, none', ...
    'Moving baseline window', ...
    'Moving baseline endpoint handling', ...
    'Cycle boundary detection mode', ...
    'State label before the boundary', ...
    'State label after the boundary', ...
    'Minimum cycle length in frames', ...
    'Maximum cycle length in frames', ...
    'Number of normalized points per cycle', ...
    'Interpolation method', ...
    'Allow extrapolation when normalizing short cycles', ...
    'Output dataseries name for the detrended trace', ...
    'Output dataseries name for normalized cycles', ...
    'Output dataseries name for cycle metadata', ...
    'Write run artifacts to files', ...
    'Output directory for optional artifacts', ...
    'Workbook file name for optional artifacts', ...
    'Run identifier used in artifacts and metadata', ...
    'Print diagnostic messages' ...
    };
end
