function text = annotationInitializationUnavailableMessage()
%ANNOTATIONINITIALIZATIONUNAVAILABLEMESSAGE Explain the explicit prerequisite.

text = ['Initialize GT requires either a compatible existing PRED source ' ...
    'or a runnable classifier model with safe non-GT inputs. CellposeSAM ' ...
    'classifiers can segment the selected ROI image directly; latent ' ...
    'classifiers still require existing PRED masks/tracks.'];
end
