function value = annotationPredictionUiText(activeModel, overwriteGt)
%ANNOTATIONPREDICTIONUITEXT Package-aware direct GT initialization wording.

if nargin < 2, overwriteGt = false; end
package = '';
try, package = char(string(activeModel.package)); catch, end
isCellpose = strcmpi(package, 'cellposesam');

if isCellpose
    model = 'the active local CellposeSAM model';
    try
        if contains(lower(char(string(activeModel.modelLabel))), 'default')
            model = 'the default CellposeSAM SAM model';
        end
    catch
    end
    replacement = 'replace the current CellposeSAM PRED result';
    if overwriteGt
        replacement = [replacement ' and replace existing editable or validated GT'];
    end
    value = struct( ...
        'confirmTitle', 'Run CellposeSAM and initialize ground truth', ...
        'confirmation', sprintf([ ...
            'Run %s on the selected ROI image, %s? The segmentation is ' ...
            'written first as PRED, then copied into editable Draft GT. ' ...
            'No ground truth is consumed by inference.'], model, replacement), ...
        'progressTitle', 'Run CellposeSAM and initialize ground truth', ...
        'progressMessage', 'Segmenting selected ROI image(s) with CellposeSAM...', ...
        'successTitle', 'Ground truth initialized from CellposeSAM', ...
        'classifierSuccess', [ ...
            'CellposeSAM segmented and initialized %d ROI(s) as editable Draft GT.\n' ...
            'Run ID: %s\nThe PRED result was preserved separately.\n' ...
            'No ground truth was consumed by inference.'], ...
        'scoreSuccess', [ ...
            'CellposeSAM PRED copied into editable Draft GT.\n' ...
            'Run ID: %s\nThe PRED result was preserved separately.\n' ...
            'No ground truth was consumed by inference.']);
    return;
end

replacement = 'recompute and replace the current model prediction';
if overwriteGt
    replacement = [replacement ' and replace existing editable or validated GT'];
end
value = struct( ...
    'confirmTitle', 'Refine existing prediction with active latent model', ...
    'confirmation', [ ...
        'Apply the active latent model to the existing PRED masks/tracks, ' ...
        replacement '? No segmentation will be run. The refined output ' ...
        'remains a prediction; its editable copy will be marked Draft.'], ...
    'progressTitle', 'Refine PRED and initialize ground truth', ...
    'progressMessage', 'Applying latent model to existing masks/tracks...', ...
    'successTitle', 'Ground truth initialized from active model', ...
    'classifierSuccess', [ ...
        'Refined and initialized %d ROI(s) as editable Draft GT.\n' ...
        'Run ID: %s\nNo segmentation was launched automatically.\n' ...
        'No ground truth was consumed by inference.'], ...
    'scoreSuccess', [ ...
        'Refined prediction copied into editable Draft GT.\n' ...
        'Run ID: %s\nNo segmentation was launched automatically.\n' ...
        'No ground truth was consumed by inference.']);
end
