function text = annotationInitializationUnavailableMessage()
%ANNOTATIONINITIALIZATIONUNAVAILABLEMESSAGE Explain the explicit prerequisite.

text = ['Initialize GT requires an existing compatible PRED mask or ' ...
    'tracked-object provider. Run CellposeSAM separately for the selected ' ...
    'ROI(s), click Refresh, then reopen Initialize GT. No segmentation is ' ...
    'launched automatically from Initialize GT.'];
end
