function spec = annotationSpec(classif)
%CNN.ANNOTATIONSPEC Reviewed sequence-label ground-truth contract.
spec=annotationManager.newSpec(classif);
execution=cnn.executionSpec(classif);
predictionGroup=char(string(execution.defaults.outputName));
component=annotationManager.newComponent( ...
    'id','sequence_label','kind','sequence_label', ...
    'storage','dataseries','coverageUnit','roi', ...
    'editor','class_palette','bootstrap','copy_fields', ...
    'classes',spec.classes, ...
    'groundTruth',annotationManager.newAsset( ...
        'groupId',spec.classifierId,'valueField','labels_training', ...
        'idField','id_training','quality','gt','producer','human_review', ...
        'semantic','sequence_class'), ...
    'prediction',annotationManager.newAsset( ...
        'groupId',predictionGroup,'valueField','labels','idField','id', ...
        'quality','pred','producer','cnn','semantic','sequence_class'));
spec.displayName='Image/sequence class';
spec.components=component;
spec.defaultEditor='class_palette';
end
