function scope = trainingScopeSpec(~)
%CNN.TRAININGSCOPESPEC Image-classifier ownership contract.
scope=classifierBinding.newTrainingScope( ...
    'module','cnn', ...
    'displayName','CNN — image/sequence classifier', ...
    'objective','Predict a reviewed class from microscopy images.', ...
    'trainedComponents',{'selected CNN backbone and classification head'}, ...
    'frozenComponents',{'Segmentation modules','tracking modules','lineage modules','temporal LSTM head'}, ...
    'datasetUnit','Formatted microscopy images with reviewed sequence/image labels.', ...
    'splitPolicy',['Legacy formatted-image split controlled by CNN_data_splitting_factor; ' ...
        'this split is not guaranteed ROI-disjoint.'], ...
    'outputParameter','outputName','outputQuality','pred', ...
    'outputSemantic','image/sequence classification dataseries', ...
    'outputTemplate','<outputName>', ...
    'canonicalOutput','pred_cnn_image_class', ...
    'notes',{'Use a pipeline-level ROI split when ROI-disjoint validation is required.'});
end
