function spec = trainingSpec(~)
%CNN.TRAININGSPEC Legacy-compatible image and annotation bindings.

spec = [ ...
    classifierBinding.newBinding( ...
        'param','inputChannelNames', 'type','channel', 'role','roi_image', ...
        'label','Training image channels', 'required',true, ...
        'storage','classifierInputChannels', 'cardinality','many', ...
        'tip','Ordered ROI image channels assembled as the CNN input.'), ...
    classifierBinding.newBinding( ...
        'param','groundTruthLabels', 'type','dataseries', ...
        'role','sequence_label_ground_truth', 'label','Sequence-label GT', ...
        'required',true, 'storage','annotation', 'editable',false, ...
        'componentId','sequence_label', ...
        'tip','Managed classifier dataseries field containing reviewed labels.') ...
    ];
end
