function trainCPSAMFun(classif, setparam)
% Gather dataset and train a Cellpose/CellposeSAM model from MATLAB

path = fullfile(classif.path);

%---------------- Default parameters
if nargin == 2
    tip = {
        'Expected average diameter of objects',
        'Minimum size to keep (object)',
         ' Flow threshold',
        'Number of training epochs',
        'Learning rate',
        'Weight decay (L2 regularization)',
        'Batch size',
        'Minimum number of masks per image',
        'Use pretrained SAM model (True/False)',
        'Verbose logging during training'
    };

    classif.trainingParam = struct( ...
        'diameter', NaN, ...
        'min_size', 10, ...
        'flow_threshold', 0.4,...
        'n_epochs', 5, ...
        'learning_rate', 1e-4, ...
        'weight_decay', 1e-5, ...
        'batch_size', 1, ...
        'min_train_masks', 1, ...
        'use_pretrained', true, ...
        'verbose', true, ...
        'tip', {tip} ...
    );
    return;
end

trainingParam = classif.trainingParam;
if isempty(trainingParam)
    disp('Training parameters not set. Launch with setparam = 1 first.');
    return;
end

%------------- Paths
train_dir = fullfile(classif.path, 'trainingdataset', 'train');
if ~exist(train_dir, 'dir')
    error('Training folder not found: %s', train_dir);
end

train_dir_clean = strrep(train_dir, '\', '/');
save_path_clean = strrep(classif.path, '\', '/');

% pretrained_model
if trainingParam.use_pretrained
    pretrained_arg = "'sam'";
else
    pretrained_arg = 'None';
end

%------------- Python script content
python_script_content = sprintf( ...
"import os\n" +...
"import torch\n" +...
"from cellpose import io, train, models\n" +...
"\n" +...
"def train_model():\n" + ...
"    train_dir = r'%s'\n" +...
"    save_path = r'%s'\n" +...
"    imgs, labels, _ = io.load_images_labels(train_dir, mask_filter='_masks')\n" +...
"    print(f'[INFO] loaded {len(imgs)} images and {len(labels)} masks')\n" +...
"    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n" +...
"    print(f'[INFO] device: {device}')\n" +...
"    model = models.CellposeModel(device=device, pretrained_model=%s)\n" +...
"    model_path, train_losses, test_losses = train.train_seg(\n" +...
"        model.net,\n" +...
"        train_data=imgs,\n" +...
"        train_labels=labels,\n" +...
"        weight_decay=%g,\n" +...
"        learning_rate=%g,\n" +...
"        n_epochs=%d,\n" +...
"        model_name='%s',\n" +...
"        save_path=save_path,\n" +...
"        batch_size=%d,\n" +...
"        min_train_masks=%d,\n" +...
"        normalize=True,\n" +...
"    )\n" +...
"\n" +...
"if __name__ == '__main__':\n" +...
"    train_model()\n", ...
train_dir_clean, ...
save_path_clean, ...
pretrained_arg, ...
trainingParam.weight_decay, ...
trainingParam.learning_rate, ...
trainingParam.n_epochs, ...
classif.strid, ...
trainingParam.batch_size, ...
trainingParam.min_train_masks ...
);

%------------- Write Python script
python_script_path = fullfile(classif.path, 'train_cpsam_script.py');
fid = fopen(python_script_path, 'w');
if fid == -1
    error('Unable to create Python script: %s', python_script_path);
end
fprintf(fid, '%s', python_script_content);
fclose(fid);

disp(['Python script saved to: ' python_script_path]);

%------------- Execute Python script
python_env = pyenv();
if strcmp(python_env.Status, 'NotLoaded')
    error('Python environment not loaded. Activate an environment before running this script.');
else
    disp(['Active Python env: ' python_env.Executable]);
end

try
    pyrunfile(python_script_path);
    disp('[OK] CellposeSAM training finished successfully.');
catch ME
    disp('[ERROR] during Python script execution.');
    disp(ME.message);
end

end
