function trainCPSAMFun(classif, setparam)
% trainCPSAMFun  Train a Cellpose/CellposeSAM model from a HDF5 framebank.
%
% Le framebank HDF5 est supposé être créé par formatPixelTrainingSetCPSAM, avec :
%   /images : [H W C N] (uint8)   -> Python : (N, C, W, H)
%   /masks  : [H W N]   (uint16)  -> Python : (N, W, H)
%   /split  : [N 1]     (uint8)   -> 1 = train, 0 = val (interne CPSAM)
%
% -------------------------------------------------------------------------
% 0) Initialisation des paramètres (mode setparam)
% -------------------------------------------------------------------------
if nargin == 2
    tip = {
        'Expected average diameter of objects',                % diameter
        'Minimum size to keep (object)',                       % min_size
        'Flow threshold',                                      % flow_threshold
        'Cell probability threshold -6 --> 6; default : 0',    % cell_prob_threshold
        'Number of training epochs',                           % n_epochs
        'Learning rate',                                       % learning_rate
        'Weight decay (L2 regularization)',                    % weight_decay
        'Batch size',                                          % batch_size
        'Minimum number of masks per image (USED IN FORMAT)',  % min_train_masks
        'Use pretrained SAM model (True/False)',               % use_pretrained
        'Verbose logging during training' ,                    % verbose
        'Max number of images used for training' ,             % MaxTrainImages
        'Seed for random number generation',                   % Seed
        'Downsampling of negative images (0: none; 1: at most as many negatives as positives)',
        'Train/val splitting ratio (internal CPSAM val fraction)'
    };

    classif.trainingParam = struct( ...
        'diameter',            NaN, ...
        'min_size',            10, ...
        'flow_threshold',      0.4, ...
        'cell_prob_threshold', 0, ...
        'n_epochs',            5, ...
        'learning_rate',       1e-4, ...
        'weight_decay',        1e-5, ...
        'batch_size',          1, ...
        'min_train_masks',     0, ...   % utilisé côté formatage
        'use_pretrained',      true, ...
        'verbose',             true, ...
        'MaxTrainImages',      50, ...
        'Seed',                12345, ...
        'NegDownsampleTrainRatio', 0, ...
        'CPSAM_ValFraction',   0.2, ...
        'tip',                 {tip} ...
    );
    return;
end

% -------------------------------------------------------------------------
% 1) Paramètres de training
% -------------------------------------------------------------------------
trainingParam = classif.trainingParam;
if isempty(trainingParam)
    disp('Training parameters not set. Launch with trainCPSAMFun(classif, 1) first.');
    return;
end

if ~isfield(trainingParam, 'verbose'),        trainingParam.verbose = true; end
if ~isfield(trainingParam, 'use_pretrained'), trainingParam.use_pretrained = true; end
if ~isfield(trainingParam, 'n_epochs'),       trainingParam.n_epochs = 5; end
if ~isfield(trainingParam, 'learning_rate'),  trainingParam.learning_rate = 1e-4; end
if ~isfield(trainingParam, 'weight_decay'),   trainingParam.weight_decay = 1e-5; end
if ~isfield(trainingParam, 'batch_size'),     trainingParam.batch_size = 1; end
if ~isfield(trainingParam, 'MaxTrainImages'), trainingParam.MaxTrainImages = 50; end
if ~isfield(trainingParam, 'Seed'),           trainingParam.Seed = 12345; end
if ~isfield(trainingParam, 'NegDownsampleTrainRatio'), trainingParam.NegDownsampleTrainRatio = 0; end

ValFraction = 0.1;   % 10% val par défaut (côté formatage)
if ~isempty(trainingParam) && isfield(trainingParam, 'CPSAM_ValFraction') && ~isempty(trainingParam.CPSAM_ValFraction)
    ValFraction = trainingParam.CPSAM_ValFraction;
end
ValFraction = max(0, min(ValFraction, 0.5));  % clamp 0..0.5

% -------------------------------------------------------------------------
% 2) Chemin du framebank (robuste avec *_framebank_XXX.h5)
% -------------------------------------------------------------------------
base = classif.path;

% On cherche tous les fichiers du type <strid>_framebank*.h5
pattern = sprintf('%s_framebank*.h5', classif.strid);
d = dir(fullfile(base, pattern));

if isempty(d)
    error('Framebank HDF5 not found in %s with pattern %s. Run formatPixelTrainingSetCPSAM before training.', ...
          base, pattern);
end

% Trier par date de modification (plus récent d'abord)
[~, idxSort] = sort([d.datenum], 'descend');
d = d(idxSort);

framebank_path = '';
for k = 1:numel(d)
    cand = fullfile(base, d(k).name);
    try
        % Petit sanity check : est-ce un HDF5 lisible ?
        h5info(cand);
        framebank_path = cand;
         fprintf('[INFO] Using framebank file: %s (modified: %s)\n', ...
            framebank_path, d(k).date);
        break;
    catch ME
        warning('[WARN] HDF5 file %s seems corrupted/unreadable (%s), skipping...', cand, ME.message);
    end
end

if isempty(framebank_path)
    error('No usable HDF5 framebank found in %s for pattern %s (all candidates unreadable).', ...
          base, pattern);
end

framebank_clean = strrep(framebank_path, '\', '/');
save_path_clean = strrep(classif.path, '\', '/');

% -------------------------------------------------------------------------
% 3) Modèle pré-entraîné + logger
% -------------------------------------------------------------------------
if trainingParam.use_pretrained
    pretrained_arg = "'sam'";
else
    pretrained_arg = 'None';
end

if trainingParam.verbose
    logger_line = "io.logger_setup()";
else
    logger_line = "";
end

% -------------------------------------------------------------------------
% 4) Script Python – version simplifiée
% -------------------------------------------------------------------------
python_script_content = sprintf( ...
"import os\n" + ...
"import torch\n" + ...
"import h5py\n" + ...
"import numpy as np\n" + ...
"import datetime\n" + ...
"import matplotlib\n" + ...
"matplotlib.use('Agg')\n" + ...
"import matplotlib.pyplot as plt\n" + ...
"from cellpose import io, train, models\n" + ...
"\n" + ...
"def load_from_framebank(framebank_path):\n" + ...
"    if not os.path.exists(framebank_path):\n" + ...
"        raise FileNotFoundError(f'Framebank not found: {framebank_path}')\n" + ...
"\n" + ...
"    # DEBUG: afficher chemin + date de modification du framebank\n" + ...
"    mtime = datetime.datetime.fromtimestamp(os.path.getmtime(framebank_path))\n" + ...
"    print('[INFO] loading framebank:', framebank_path)\n" + ...
"    print('[INFO] framebank last modified:', mtime.isoformat())\n" + ...
"\n" + ...
"    with h5py.File(framebank_path, 'r') as f:\n" + ...
"        images = f['/images']      # MATLAB: [H W C N] => Python: (N, C, W, H)\n" + ...
"        masks  = f['/masks']       # MATLAB: [H W N]   => Python: (N, W, H)\n" + ...
"        split_raw = f['/split'][:]\n" + ...
"        split = np.array(split_raw, dtype=np.uint8).ravel()\n" + ...
"\n" + ...
"        print('[DEBUG] images shape (raw):', images.shape)\n" + ...
"        print('[DEBUG] masks shape (raw):', masks.shape)\n" + ...
"        print('[DEBUG] split shape (raw):', split_raw.shape, '->', split.shape)\n" + ...
"\n" + ...
"        N_img = images.shape[0]\n" + ...
"        N_msk = masks.shape[0]\n" + ...
"        N_split = split.size\n" + ...
"\n" + ...
"        if not (N_img == N_msk == N_split):\n" + ...
"            raise RuntimeError(\n" + ...
"                f'Inconsistent N between images/masks/split: '\n" + ...
"                f'images={images.shape}, masks={masks.shape}, split_len={N_split}'\n" + ...
"            )\n" + ...
"\n" + ...
"        # shapes: images (N, C, W, H), masks (N, W, H)\n" + ...
"        _, C, W, H = images.shape\n" + ...
"        _, W2, H2  = masks.shape\n" + ...
"        if W != W2 or H != H2:\n" + ...
"            raise RuntimeError(\n" + ...
"                f'Inconsistent W/H between images and masks: '\n" + ...
"                f'images={images.shape}, masks={masks.shape}'\n" + ...
"            )\n" + ...
"\n" + ...
"        train_idx = np.where(split == 1)[0]\n" + ...
"        print(f'[INFO] found {len(train_idx)} training frames in framebank')\n" + ...
"\n" + ...
"        imgs = []\n" + ...
"        labels = []\n" + ...
"        masks_per_img   = []\n" + ...
"        pixels_per_img  = []\n" + ...
"\n" + ...
"        for idx in train_idx:\n" + ...
"            # mask: (N, W, H) -> (W, H) -> transpose => (H, W)\n" + ...
"            lab = np.array(masks[idx])   # (W, H)\n" + ...
"            lab = lab.T                  # (H, W)\n" + ...
"            if lab.ndim != 2:\n" + ...
"                raise RuntimeError(f'Loaded mask with ndim={lab.ndim}, expected 2')\n" + ...
"            n_masks  = int(lab.max())\n" + ...
"            n_pixels = int((lab > 0).sum())\n" + ...
"            masks_per_img.append(n_masks)\n" + ...
"            pixels_per_img.append(n_pixels)\n" + ...
"\n" + ...
"            # image: (N, C, W, H) -> (C, W, H) -> (H, W, C) ou (H, W)\n" + ...
"            img = np.array(images[idx])  # (C, W, H)\n" + ...
"            if img.ndim == 3:\n" + ...
"                img = np.transpose(img, (2, 1, 0))   # (H, W, C)\n" + ...
"                if img.shape[2] == 1:\n" + ...
"                    img = img[:, :, 0]              # (H, W)\n" + ...
"            elif img.ndim == 2:\n" + ...
"                img = img.T                         # (H, W)\n" + ...
"            else:\n" + ...
"                raise RuntimeError(\n" + ...
"                    f'Loaded image with unexpected ndim={img.ndim}, shape={img.shape}'\n" + ...
"                )\n" + ...
"\n" + ...
"            imgs.append(img)\n" + ...
"            labels.append(lab)\n" + ...
"\n" + ...
"    masks_per_img  = np.array(masks_per_img)\n" + ...
"    pixels_per_img = np.array(pixels_per_img)\n" + ...
"    print(\n" + ...
"        f'[DEBUG] masks_per_img: min={masks_per_img.min()}, '\n" + ...
"        f'max={masks_per_img.max()}, mean={masks_per_img.mean():.2f}'\n" + ...
"    )\n" + ...
"    print(\n" + ...
"        f'[DEBUG] pixels_per_img: min={pixels_per_img.min()}, '\n" + ...
"        f'max={pixels_per_img.max()}, mean={pixels_per_img.mean():.1f}'\n" + ...
"    )\n" + ...
"    if len(imgs) == 0:\n" + ...
"        raise RuntimeError('No training images found in framebank (train split).')\n" + ...
"    print('[INFO] first training image shape (after reorder):', imgs[0].shape)\n" + ...
"    return imgs, labels\n" + ...
"\n" + ...
"def train_model():\n" + ...
"    framebank_path = r'%s'\n" + ...
"    save_path      = r'%s'\n" + ...
"    model_name     = '%s'\n" + ...
"    %s\n" + ...
"    imgs, labels = load_from_framebank(framebank_path)\n" + ...
"    print(f'[INFO] loaded {len(imgs)} images and {len(labels)} masks FROM framebank')\n" + ...
"    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n" + ...
"    print(f'[INFO] device: {device}')\n" + ...
"\n" + ...
"    model = models.CellposeModel(\n" + ...
"        gpu=True,\n" + ...
"        device=device,\n" + ...
"        pretrained_model=%s,\n" + ...
"    )\n" + ...
"\n" + ...
"    model_path, train_losses, test_losses = train.train_seg(\n" + ...
"        model.net,\n" + ...
"        train_data=imgs,\n" + ...
"        train_labels=labels,\n" + ...
"        weight_decay=%g,\n" + ...
"        learning_rate=%g,\n" + ...
"        n_epochs=%d,\n" + ...
"        model_name=model_name,\n" + ...
"        save_path=save_path,\n" + ...
"        batch_size=%d,\n" + ...
"        min_train_masks=0,\n" + ...
"    )\n" + ...
"    print('[INFO] training finished, model saved to', model_path)\n" + ...
"\n" + ...
"    # --- log and plot training losses ---\n" + ...
"    if train_losses is not None and len(train_losses) > 0:\n" + ...
"        epochs = np.arange(1, len(train_losses) + 1)\n" + ...
"        loss_png = os.path.join(save_path, f'{model_name}_losses.png')\n" + ...
"        try:\n" + ...
"            plt.figure(figsize=(8, 5))\n" + ...
"            plt.plot(epochs, train_losses, label='train loss')\n" + ...
"            if test_losses is not None and len(test_losses) == len(train_losses):\n" + ...
"                plt.plot(epochs, test_losses, label='test loss')\n" + ...
"            plt.xlabel('epoch')\n" + ...
"            plt.ylabel('loss')\n" + ...
"            plt.title(f'Cellpose training: {model_name}')\n" + ...
"            plt.grid(True, linestyle='--', alpha=0.4)\n" + ...
"            plt.legend()\n" + ...
"            plt.tight_layout()\n" + ...
"            plt.savefig(loss_png, dpi=150)\n" + ...
"            plt.close()\n" + ...
"            print('[INFO] loss plot saved to:', loss_png)\n" + ...
"        except Exception as e:\n" + ...
"            print('[WARN] could not save loss plot:', e)\n" + ...
"\n" + ...
"if __name__ == '__main__':\n" + ...
"    train_model()\n", ...
framebank_clean, ...
save_path_clean, ...
classif.strid, ...
logger_line, ...
pretrained_arg, ...
trainingParam.weight_decay, ...
trainingParam.learning_rate, ...
trainingParam.n_epochs, ...
trainingParam.batch_size ...
);


% -------------------------------------------------------------------------
% 5) Sauvegarde du script Python
% -------------------------------------------------------------------------
python_script_path = fullfile(classif.path, 'train_cpsam_from_framebank.py');
fid = fopen(python_script_path, 'w');
if fid == -1
    error('Unable to create Python script: %s', python_script_path);
end
fprintf(fid, '%s', python_script_content);
fclose(fid);

disp(['[INFO] Python training script saved to: ' python_script_path]);

% -------------------------------------------------------------------------
% 6) Environnement Python & exécution
% -------------------------------------------------------------------------
try
    test = select_and_load_conda_env; %#ok<NASGU>
catch ME
    warning('select_and_load_conda_env failed: %s', ME.message);
end

python_env = pyenv();
if strcmp(python_env.Status, 'NotLoaded')
    error('Python environment not loaded. Activate an environment before running this script.');
else
    disp(['[INFO] Active Python env: ' python_env.Executable]);
end

try
    pyrunfile(python_script_path);
    disp('[OK] CellposeSAM training finished successfully.');
catch ME
    disp('[ERROR] during Python script execution.');
    disp(ME.message);
end

end
