function trainYOLOSegFun(classif, setparam)

% Gather all classification images in each class: unbudded, small budded,
% large budded, perform the training and output and save the trained net

path = fullfile(classif.path);
name = classif.strid;

%---------------- Parameters setting
if nargin == 2 % Basic parameter initialization
    
    tip = {'Choose the training method', ...
           'Choose the Yolo model size', ...
           'Choose the size of the mini batch; Higher values require more memory and are prone to errors', ...
           'Enter the number of epochs', ...
           'Enter the initial learning rate', ...
           'Enter the magnitude of translation for data augmentation (in pixels)', ...
           'Enter the magnitude of rotation for data augmentation (in pixels)', ...
           'Specify value for L2 regularization', ...
           'Choose execution environment'};
      
    classif.trainingParam = struct('CNN_training_method', {{'auto','Adam', 'SGD','AdamW','NAdam','RAdam', 'auto'}}, ...
        'Yolo_Model', {{'yolo11n-seg.pt','yolo11s-seg.pt','yolo11m-seg.pt','yolo11l-seg.pt','yolo11m-seg.pt'}}, ...
        'CNN_mini_batch_size', 8, ...
        'CNN_max_epochs', 20, ...
        'CNN_initial_learning_rate', 0.001, ...
        'CNN_translation_augmentation', [-5 5], ...
        'CNN_rotation_augmentation', [-20 20], ...
        'CNN_l2_regularization', 0.00001, ...
        'execution_environment', {{'auto', 'cpu', 'gpu', 'auto'}}, ...
        'tip', {tip});
    
    return;
else
    trainingParam = classif.trainingParam;
    
    if numel(trainingParam) == 0
        disp('Could not find training parameters: first launch training with an extra argument to force parameter assignment');
        return;
    end
end

% Get the directory of the current MATLAB script
script_full_path = mfilename('fullpath');
[script_dir, ~, ~] = fileparts(script_full_path);

% prepare pthon environnement 
%pyenv('Version', 'C:\Users\Gilles\.conda\envs\my_cuda_env\python.exe');
%pyenv('ExecutionMode', 'OutOfProcess');

% help load the python env
%disp( py.sys.version )

% Prepare for YOLO training
images_folder = fullfile([path '/trainingdataset/images']);
labels_folder = fullfile([path '/trainingdataset/labels']);
yaml_path = fullfile(classif.path, '/trainingdataset/dataset.yaml');
output_model_path = fullfile(classif.path, [classif.strid '.pt']);
epochs = trainingParam.CNN_max_epochs;
learning_rate = trainingParam.CNN_initial_learning_rate;
batch_size = trainingParam.CNN_mini_batch_size;
device = ''; % Default device

if  numel(classif.roi) < 1 || numel(classif.roi(1).value) < 4
    error('Invalid or missing ROI information in classif.');
end

imgsz=max(256,classif.roi(1).value(4)); % image size multiplied by 4 to improve accuracy!!

degrees=trainingParam.CNN_rotation_augmentation(2);
translate= trainingParam.CNN_translation_augmentation(2)/classif.roi(1).value(4);
optimizer=trainingParam.CNN_training_method{end};
model_size=trainingParam.Yolo_Model{end};

switch trainingParam.execution_environment{end}
    case "auto"
    case "cpu"
        device='cpu';
    case "gpu"
        device=0;
end

% Escape backslashes for Python compatibility
images_folder = strrep(images_folder, '\', '\\');
labels_folder = strrep(labels_folder, '\', '\\');
yaml_path = strrep(yaml_path, '\', '\\');
output_model_path = strrep(output_model_path, '\', '\\');
classipath=strrep(classif.path, '\', '\\');

% Construire le contenu du script Python avec sprintf
if isempty(device)
    device_param = ""; % Ne pas inclure le paramètre 'device' si vide
elseif isnumeric(device)
    device_param = sprintf("        device=%d,\n", device); % Inclure le paramètre avec un nombre
else
    device_param = sprintf("        device=cpu,\n"); % Inclure le paramètre avec une chaîne
end

python_script_content = sprintf( ...
    "from ultralytics import YOLO\n" + ...
    "\n" + ...
    "def train_yolo():\n" + ...
    "    # Retrieve arguments\n" + ...
    "    yaml_path = r'%s'\n" + ...
    "    epochs = %d\n" + ...
    "    learning_rate = %f\n" + ...
    "    batch_size = %d\n" + ...
    "    imgsz = %d\n" + ...
    "    degrees = %d\n" + ...
    "    translate = %f\n" + ...
    "    optimizer = '%s'\n" + ...
    "    project = r'%s'\n" + ...
    "\n" + ...
    "    # Load YOLO model\n" + ...
    "    model = YOLO(r'%s')\n" + ...
    "\n" + ...
    "    # Train the model\n" + ...
    "    model.train(\n" + ...
    "        data=yaml_path,\n" + ...
    "        epochs=epochs,\n" + ...
    "        batch=batch_size,\n" + ...
    "        lr0=learning_rate,\n" + ...
    device_param + ...
    "        imgsz=imgsz,\n" + ...
    "        degrees=degrees,\n" + ...
    "        translate=translate,\n" + ...
    "        optimizer=optimizer,\n" + ...
    "        mask_ratio=1,\n" + ...
    "        project=project,\n" + ... 
    "        name='run'\n" + ... 
    "    )\n" + ...
    "\n" + ...
    "    try:\n" + ...
    "        # Uncomment the following line to export the model\n" + ...
    "        # model.export(export_dir='%s', format='torchscript')\n" + ...
    "        print('Model exported successfully.')\n" + ...
    "    except Exception as e:\n" + ...
    "        print(f'Export failed: {e}')\n" + ...
    "\n" + ...
    "if __name__ == '__main__':\n" + ...
    "    train_yolo()\n", ...
    yaml_path, epochs, ...
    learning_rate, batch_size, imgsz, ...
    degrees, translate, optimizer, classipath, model_size, output_model_path);

% Sauvegarder le script Python dans un fichier
python_script_path = fullfile(classif.path, 'train_script.py');
fid = fopen(python_script_path, 'w');
if fid == -1
    error('Impossible de créer le fichier Python : %s', python_script_path);
end
fprintf(fid, '%s', python_script_content); % Écriture du script
fclose(fid);

% Afficher le chemin du script Python enregistré
disp(['Python script saved to: ', python_script_path]);

% Vérifier que les chemins requis existent
if ~exist(images_folder, 'dir') || ~exist(labels_folder, 'dir') || ~exist(yaml_path, 'file')
    error('One or more required files or directories are missing.');
end

% python_command = sprintf('python "%s"', python_script_path);
% [status, cmdout] = system(python_command);
% if status == 0
%     disp('Python script executed successfully.');
% else
%     disp('Error executing Python script:');
%     disp(cmdout);
% end

% Vérifier si Python est configuré et si un environnement est actif
%if ~ pyenv().Executable
%    error('Aucune installation de Python détectée. Veuillez configurer un environnement Python actif avec la commande `pyenv`.');
%end

% Vérifier si l'environnement Python est correctement configuré
python_env = pyenv();
if strcmp(python_env.Status, 'NotLoaded')
    error('L''environnement Python n''est pas chargé. Veuillez activer un environnement Python avant de lancer ce script.');
else
    disp(['Environnement Python actif : ', python_env.Executable]);
end

% Run the Python script
try
    pyrunfile(python_script_path);
    disp('YOLOv11 training completed successfully.');
catch ME
    disp('Error during YOLO training:');
    disp(ME.message);
end

