function trainCPSAMFun(classif, setparam)
% trainCPSAMFun  Train a Cellpose/CellposeSAM model from a HDF5 framebank.
%
% Le framebank HDF5 est supposé être créé par formatPixelTrainingSetCPSAM, avec :
%   /images : [H W C N] (uint8)   -> Python : (N, C, W, H)
%   /masks  : [H W N]   (uint16)  -> Python : (N, W, H)
%   /split  : [N 1]     (uint8)   -> Python : (1, N)  (d'où le .ravel())

% -------------------------------------------------------------------------
% 0) Initialisation des paramètres (mode setparam)
% -------------------------------------------------------------------------
if nargin == 2
    tip = {
        'Expected average diameter of objects',                % diameter
        'Minimum size to keep (object)',                       % min_size
        'Flow threshold',                                      % flow_threshold
        'Cell probability threshold -6 --> 6; default : 0',    % cell_prob_threshold
        'Number of training epochs',                           % n_epochs
        'Learning rate',                                       % learning_rate
        'Weight decay (L2 regularization)',                    % weight_decay
        'Batch size',                                          % batch_size
        'Minimum number of masks per image (USED IN FORMAT)',  % min_train_masks
        'Use pretrained SAM model (True/False)',               % use_pretrained
        'Verbose logging during training' ,                     % verbose
        'Max number of images used for training' ,                      % verbose
        'Seed'
    };

    classif.trainingParam = struct( ...
        'diameter',            NaN, ...
        'min_size',            10, ...
        'flow_threshold',      0.4, ...
        'cell_prob_threshold', 0, ...
        'n_epochs',            5, ...
        'learning_rate',       1e-4, ...
        'weight_decay',        1e-5, ...
        'batch_size',          1, ...
        'min_train_masks',     1, ...   % utilisé côté formatage
        'use_pretrained',      true, ...
        'verbose',             true, ...
        'MaxTrainImages',      50, ...
        'Seed', 12345, ...
        'tip',                 {tip} ...
    );
    return;
end

% -------------------------------------------------------------------------
% 1) Paramètres de training
% -------------------------------------------------------------------------
trainingParam = classif.trainingParam;
if isempty(trainingParam)
    disp('Training parameters not set. Launch with trainCPSAMFun(classif, 1) first.');
    return;
end

if ~isfield(trainingParam, 'verbose'),        trainingParam.verbose = true; end
if ~isfield(trainingParam, 'use_pretrained'), trainingParam.use_pretrained = true; end
if ~isfield(trainingParam, 'n_epochs'),       trainingParam.n_epochs = 5; end
if ~isfield(trainingParam, 'learning_rate'),  trainingParam.learning_rate = 1e-4; end
if ~isfield(trainingParam, 'weight_decay'),   trainingParam.weight_decay = 1e-5; end
if ~isfield(trainingParam, 'batch_size'),     trainingParam.batch_size = 1; end
if ~isfield(trainingParam, 'MaxTrainImages'),  trainingParam.MaxTrainImages = 50; end
if ~isfield(trainingParam, 'Seed'),     trainingParam.Seed = 12345; end


% -------------------------------------------------------------------------
% 2) Chemin du framebank
% -------------------------------------------------------------------------
base = classif.path;
framebank_name = sprintf('%s_framebank.h5', classif.strid);
framebank_path = fullfile(base, framebank_name);

if ~exist(framebank_path, 'file')
    error('Framebank HDF5 not found: %s\nRun formatPixelTrainingSetCPSAM before training.', framebank_path);
end

framebank_clean = strrep(framebank_path, '\', '/');
save_path_clean = strrep(classif.path, '\', '/');

% -------------------------------------------------------------------------
% 3) Modèle pré-entraîné + logger
% -------------------------------------------------------------------------
if trainingParam.use_pretrained
    pretrained_arg = "'sam'";
else
    pretrained_arg = 'None';
end

if trainingParam.verbose
    logger_line = "io.logger_setup()";
else
    logger_line = "";
end



% -------------------------------------------------------------------------
% 4) Script Python – version simplifiée
% -------------------------------------------------------------------------
python_script_content = sprintf( ...
"import os\n" + ...
"import torch\n" + ...
"import h5py\n" + ...
"import numpy as np\n" + ...
"from cellpose import io, train, models\n" + ...
"\n" + ...
"def load_from_framebank(framebank_path):\n" + ...
"    if not os.path.exists(framebank_path):\n" + ...
"        raise FileNotFoundError(f'Framebank not found: {framebank_path}')\n" + ...
"    with h5py.File(framebank_path, 'r') as f:\n" + ...
"        images = f['/images']      # MATLAB: [H W C N] => Python: (N, C, W, H)\n" + ...
"        masks  = f['/masks']       # MATLAB: [H W N]   => Python: (N, W, H)\n" + ...
"        split_raw = f['/split'][:]\n" + ...
"        split = np.array(split_raw, dtype=np.uint8).ravel()\n" + ...
"\n" + ...
"        print('[DEBUG] images shape (raw):', images.shape)\n" + ...
"        print('[DEBUG] masks shape (raw):', masks.shape)\n" + ...
"        print('[DEBUG] split shape (raw):', split_raw.shape, '->', split.shape)\n" + ...
"\n" + ...
"        N_img = images.shape[0]\n" + ...
"        N_msk = masks.shape[0]\n" + ...
"        N_split = split.size\n" + ...
"\n" + ...
"        if not (N_img == N_msk == N_split):\n" + ...
"            raise RuntimeError(\n" + ...
"                f'Inconsistent N between images/masks/split: '\n" + ...
"                f'images={images.shape}, masks={masks.shape}, split_len={N_split}'\n" + ...
"            )\n" + ...
"\n" + ...
"        # shapes: images (N, C, W, H), masks (N, W, H)\n" + ...
"        _, C, W, H = images.shape\n" + ...
"        _, W2, H2  = masks.shape\n" + ...
"        if W != W2 or H != H2:\n" + ...
"            raise RuntimeError(\n" + ...
"                f'Inconsistent W/H between images and masks: '\n" + ...
"                f'images={images.shape}, masks={masks.shape}'\n" + ...
"            )\n" + ...
"\n" + ...
"        train_idx = np.where(split == 1)[0]\n" + ...
"        print(f'[INFO] found {len(train_idx)} training frames in framebank')\n" + ...
"\n" + ...
"        imgs = []\n" + ...
"        labels = []\n" + ...
"        masks_per_img   = []\n" + ...
"        pixels_per_img  = []\n" + ...
"\n" + ...
"        for idx in train_idx:\n" + ...
"            # mask: (N, W, H) -> (W, H) -> transpose => (H, W)\n" + ...
"            lab = np.array(masks[idx])   # (W, H)\n" + ...
"            lab = lab.T                  # (H, W)\n" + ...
"            if lab.ndim != 2:\n" + ...
"                raise RuntimeError(f'Loaded mask with ndim={lab.ndim}, expected 2')\n" + ...
"            n_masks  = int(lab.max())\n" + ...
"            n_pixels = int((lab > 0).sum())\n" + ...
"            masks_per_img.append(n_masks)\n" + ...
"            pixels_per_img.append(n_pixels)\n" + ...
"\n" + ...
"            # image: (N, C, W, H) -> (C, W, H) -> (H, W, C) ou (H, W)\n" + ...
"            img = np.array(images[idx])  # (C, W, H)\n" + ...
"            if img.ndim == 3:\n" + ...
"                img = np.transpose(img, (2, 1, 0))   # (H, W, C)\n" + ...
"                if img.shape[2] == 1:\n" + ...
"                    img = img[:, :, 0]              # (H, W)\n" + ...
"            elif img.ndim == 2:\n" + ...
"                img = img.T                         # (H, W)\n" + ...
"            else:\n" + ...
"                raise RuntimeError(\n" + ...
"                    f'Loaded image with unexpected ndim={img.ndim}, shape={img.shape}'\n" + ...
"                )\n" + ...
"\n" + ...
"            imgs.append(img)\n" + ...
"            labels.append(lab)\n" + ...
"\n" + ...
"    masks_per_img  = np.array(masks_per_img)\n" + ...
"    pixels_per_img = np.array(pixels_per_img)\n" + ...
"    print(\n" + ...
"        f'[DEBUG] masks_per_img: min={masks_per_img.min()}, '\n" + ...
"        f'max={masks_per_img.max()}, mean={masks_per_img.mean():.2f}'\n" + ...
"    )\n" + ...
"    print(\n" + ...
"        f'[DEBUG] pixels_per_img: min={pixels_per_img.min()}, '\n" + ...
"        f'max={pixels_per_img.max()}, mean={pixels_per_img.mean():.1f}'\n" + ...
"    )\n" + ...
"    if len(imgs) == 0:\n" + ...
"        raise RuntimeError('No training images found in framebank (train split).')\n" + ...
"    print('[INFO] first training image shape (after reorder):', imgs[0].shape)\n" + ...
"    return imgs, labels\n" + ...
"\n" + ...
"def train_model():\n" + ...
"    framebank_path = r'%s'\n" + ...
"    save_path      = r'%s'\n" + ...
"    %s\n" + ...  % logger_line
"    imgs, labels = load_from_framebank(framebank_path)\n" + ...
"    print(f'[INFO] loaded {len(imgs)} images and {len(labels)} masks FROM framebank')\n" + ...
"    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n" + ...
"    print(f'[INFO] device: {device}')\n" + ...
"\n" + ...
"    model = models.CellposeModel(\n" + ...
"        gpu=True,\n" + ...
"        device=device,\n" + ...
"        pretrained_model=%s,\n" + ...
"    )\n" + ...
"\n" + ...
"    model_path, train_losses, test_losses = train.train_seg(\n" + ...
"        model.net,\n" + ...
"        train_data=imgs,\n" + ...
"        train_labels=labels,\n" + ...
"        weight_decay=%g,\n" + ...
"        learning_rate=%g,\n" + ...
"        n_epochs=%d,\n" + ...
"        model_name='%s',\n" + ...
"        save_path=save_path,\n" + ...
"        batch_size=%d,\n" + ...
"        min_train_masks=0,\n" + ...
"    )\n" + ...
"    print('[INFO] training finished, model saved to', model_path)\n" + ...
"\n" + ...
"if __name__ == '__main__':\n" + ...
"    train_model()\n", ...
framebank_clean, ...
save_path_clean, ...
logger_line, ...
pretrained_arg, ...
trainingParam.weight_decay, ...
trainingParam.learning_rate, ...
trainingParam.n_epochs, ...
classif.strid, ...
trainingParam.batch_size ...
);

% -------------------------------------------------------------------------
% 5) Sauvegarde du script Python
% -------------------------------------------------------------------------
python_script_path = fullfile(classif.path, 'train_cpsam_from_framebank.py');
fid = fopen(python_script_path, 'w');
if fid == -1
    error('Unable to create Python script: %s', python_script_path);
end
fprintf(fid, '%s', python_script_content);
fclose(fid);

disp(['[INFO] Python training script saved to: ' python_script_path]);

% -------------------------------------------------------------------------
% 6) Environnement Python & exécution
% -------------------------------------------------------------------------
try
    test = select_and_load_conda_env; %#ok<NASGU>
catch ME
    warning('select_and_load_conda_env failed: %s', ME.message);
end

python_env = pyenv();
if strcmp(python_env.Status, 'NotLoaded')
    error('Python environment not loaded. Activate an environment before running this script.');
else
    disp(['[INFO] Active Python env: ' python_env.Executable]);
end

try
    pyrunfile(python_script_path);
    disp('[OK] CellposeSAM training finished successfully.');
catch ME
    disp('[ERROR] during Python script execution.');
    disp(ME.message);
end

end
