function tests = testPythonAppControlFailure
%TESTPYTHONAPPCONTROLFAILURE Regression tests for retry classification.
tests = functiontests(localfunctions);
end

function testFrenchSmartAppControlStartupBlockIsRetryable(testCase)
output = startupTrace([ ...
    'ImportError: DLL load failed while importing _bglu_dense: ' ...
    'Une stratégie de contrôle d''application a bloqué ce fichier.']);

info = cellLatentModel.utils.inspectPythonAppControlFailure(1,output);

verifyTrue(testCase,info.retryable);
verifyTrue(testCase,info.isDllImportFailure);
verifyTrue(testCase,info.isAppControlBlock);
verifyTrue(testCase,info.isBeforeCli);
verifyEqual(testCase,info.blockedModule,'_bglu_dense');
end

function testRealPackageImportTraceIsRetryable(testCase)
output = sprintf([ ...
    'Traceback (most recent call last):\n' ...
    '  File "C:\\Users\\TestUser\\.conda\\envs\\detecdiv_python\\lib\\runpy.py", line 187, in _run_module_as_main\n' ...
    '    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)\n' ...
    '  File "C:\\Users\\TestUser\\.conda\\envs\\detecdiv_python\\lib\\runpy.py", line 146, in _get_module_details\n' ...
    '    return _get_module_details(pkg_main_name, error)\n' ...
    '  File "C:\\Users\\TestUser\\.conda\\envs\\detecdiv_python\\lib\\runpy.py", line 110, in _get_module_details\n' ...
    '    __import__(pkg_name)\n' ...
    '  File "C:\\repo\\src\\cell_latent_model\\__init__.py", line 3, in <module>\n' ...
    '    from scipy.optimize import linprog\n' ...
    'ImportError: DLL load failed while importing _bglu_dense: ' ...
    'Une stratégie de contrôle d''application a bloqué ce fichier.\n']);

info = cellLatentModel.utils.inspectPythonAppControlFailure(1,output);

verifyTrue(testCase,info.retryable);
verifyTrue(testCase,info.isBeforeCli);
verifyEqual(testCase,info.blockedModule,'_bglu_dense');
end

function testMojibakeFrenchMessageIsRetryable(testCase)
bad = char(65533);
message = ['ImportError: DLL load failed while importing _bglu_dense: ' ...
    'Une strat' bad 'gie de contr' bad 'le d' bad ...
    'application a bloqu' bad ' ce fichier.'];

info = cellLatentModel.utils.inspectPythonAppControlFailure(1, ...
    startupTrace(message));

verifyTrue(testCase,info.retryable);
end

function testEnglishMessageAndStatusCodeAreRetryable(testCase)
message = ['ImportError: DLL load failed while importing scipy_core: ' ...
    'An Application Control policy has blocked this file. ' ...
    '(0xC0E90002) C:\Python\scipy_core.pyd'];

info = cellLatentModel.utils.inspectPythonAppControlFailure(1, ...
    startupTrace(message));

verifyTrue(testCase,info.retryable);
verifyEqual(testCase,info.blockedModule,'scipy_core');
verifyEqual(testCase,info.blockedFile,'C:\Python\scipy_core.pyd');
end

function testOrdinaryDllFailureIsNotRetryable(testCase)
message = ['ImportError: DLL load failed while importing _bglu_dense: ' ...
    'The specified procedure could not be found.'];

info = cellLatentModel.utils.inspectPythonAppControlFailure(1, ...
    startupTrace(message));

verifyFalse(testCase,info.retryable);
verifyFalse(testCase,info.isAppControlBlock);
end

function testScientificCommandFailureIsNotRetryable(testCase)
output = sprintf([ ...
    'Traceback (most recent call last):\n' ...
    '  File "C:\\repo\\cell_latent_model\\__main__.py", line 5, in <module>\n' ...
    '    main()\n' ...
    '  File "C:\\repo\\cell_latent_model\\cli.py", line 200, in main\n' ...
    '    train_detecdiv_tracking_from_config(config)\n' ...
    'ImportError: DLL load failed while importing _solver: ' ...
    'An Application Control policy has blocked this file.\n']);

info = cellLatentModel.utils.inspectPythonAppControlFailure(1,output);

verifyFalse(testCase,info.retryable);
verifyFalse(testCase,info.isBeforeCli);
end

function testProgressProvesCliExecutionAndPreventsRetry(testCase)
output = [startupTrace([ ...
    'ImportError: DLL load failed while importing _solver: ' ...
    'An Application Control policy has blocked this file.']) ...
    '@@DETECDIV_PROGRESS@@ {"value":0.1}'];

info = cellLatentModel.utils.inspectPythonAppControlFailure(1,output);

verifyFalse(testCase,info.retryable);
verifyFalse(testCase,info.isBeforeCli);
end

function testSuccessfulProcessIsNeverRetryable(testCase)
output = startupTrace([ ...
    'ImportError: DLL load failed while importing _bglu_dense: ' ...
    'An Application Control policy has blocked this file.']);

info = cellLatentModel.utils.inspectPythonAppControlFailure(0,output);

verifyFalse(testCase,info.retryable);
end

function output = startupTrace(finalLine)
output = sprintf([ ...
    'Traceback (most recent call last):\n' ...
    '  File "C:\\Python\\lib\\runpy.py", line 187, in _run_module_as_main\n' ...
    '    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)\n' ...
    '  File "C:\\repo\\cell_latent_model\\__main__.py", line 1, in <module>\n' ...
    '    from .cli import main\n' ...
    '%s\n'],finalLine);
end
