function spec = executionSpec()
%BUDMOTHERLINKER.EXECUTIONSPEC Pipeline/UI contract for the builtin linker.

defaults = budMotherLinker.setparam(struct( ...
    'useProvidedChannels', true, ...
    'channels', {{'N/A'}}));

spec = struct();
spec.summary = ['Links newly appearing bud tracks to their mother with the ' ...
    'frozen HGB-16 model and stores the genealogy in a cell-model family.'];
spec.staticKeys = { ...
    'inputFamily','outputFamilyName', ...
    'modelPackage','lynRepository','lynCheckpoint','pythonExecutable', ...
    'frameEnd','minLifetime','maxBirthArea','minParentAge', ...
    'maxParentCentroidDistance','maxParentContourDistance','maxCandidates', ...
    'overwriteOutputFamily','keepRuntimeFiles','debug'};
spec.pathKeys = {'modelPackage','lynRepository','lynCheckpoint','pythonExecutable'};
spec.defaults = defaults;

spec.labels = struct( ...
    'trackChannelName', 'Tracked-label channel', ...
    'inputFamily', 'Input cell-model family', ...
    'outputFamilyName', 'Output lineage family', ...
    'modelPackage', 'HGB-16 model package', ...
    'lynRepository', 'LYN-trace repository', ...
    'lynCheckpoint', 'LYN feature checkpoint', ...
    'pythonExecutable', 'Python executable', ...
    'frameEnd', 'Last frame', ...
    'minLifetime', 'Minimum bud lifetime', ...
    'maxBirthArea', 'Maximum bud birth area', ...
    'minParentAge', 'Minimum mother age', ...
    'maxParentCentroidDistance', 'Maximum centroid distance', ...
    'maxParentContourDistance', 'Maximum contour distance', ...
    'maxCandidates', 'Maximum mother candidates', ...
    'overwriteOutputFamily', 'Overwrite output family', ...
    'keepRuntimeFiles', 'Keep runtime files', ...
    'debug', 'Debug output');

tipKeys = fieldnames(defaults);
tipKeys = setdiff(tipKeys, {'tip'}, 'stable');
spec.tips = struct();
if isfield(defaults, 'tip') && iscell(defaults.tip)
    for i = 1:min(numel(tipKeys), numel(defaults.tip))
        spec.tips.(tipKeys{i}) = defaults.tip{i};
    end
end
spec.choices = struct( ...
    'inputFamily', {{'<auto>'}}, ...
    'overwriteOutputFamily', {{true,false}}, ...
    'keepRuntimeFiles', {{false,true}}, ...
    'debug', {{false,true}});

resourceIn = struct( ...
    'type', 'channel', ...
    'role', 'tracked_mask', ...
    'symbol', 'trackChannelName', ...
    'param', 'trackChannelName', ...
    'port', 'channels', ...
    'nameParam', 'trackChannelName', ...
    'required', true, ...
    'transfer', '');
emptyResource = repmat(resourceIn, 0, 1);

spec.contract = struct();
spec.contract.selectors = struct( ...
    'channelParam', 'trackChannelName', ...
    'channelsParam', '', ...
    'framesParam', 'frameEnd', ...
    'outputNameParam', 'outputFamilyName');
spec.contract.parameters = struct( ...
    'static', {spec.staticKeys}, ...
    'paths', {spec.pathKeys});
spec.contract.requirements = struct( ...
    'roi', struct('required', true, 'channelsMin', 1), ...
    'params', struct('optional', {spec.staticKeys}));
spec.contract.capabilities = struct( ...
    'preservesRoiList', true, ...
    'roiDataSeries', false, ...
    'outputsDataSeries', false);
spec.contract.binding = struct( ...
    'scope', 'roi', ...
    'outputScope', 'roi', ...
    'mode', 'singleChannel', ...
    'selectorKeys', {{'trackChannelName'}}, ...
    'exactCount', 1, ...
    'minCount', 1, ...
    'defaultCount', 1, ...
    'resolveAt', 'run');
spec.contract.resources = struct('in', resourceIn, 'out', emptyResource);
end
