function spec = executionSpec(classif)
% sam31.executionSpec  Execution-time parameter contract.

if nargin < 1
    classif = [];
end

tp = sam31.utils.defaultTrainingParam();
spec = struct();
spec.category = 'Pixel';
spec.defaultClasses = {'cell'};
spec.segmentationKind = 'instance_tracking';
spec.instanceSegmentation = true;
spec.summary = 'SAM3.1 instance segmentation and video tracking bridge.';
spec.staticKeys = {'backend','pythonExecutable','repoRoot','sam3Repo','resolution', ...
    'detectorCheckpointPath','trackerCheckpointPath','maxNumObjects','chunkSize', ...
    'chunkOverlap','videoScoreThreshold','videoNewDetThreshold','videoDetNmsThreshold', ...
    'videoAssocIouThreshold','prompt','promptMode','minScore'};
spec.outputKeys = {'outputName'};
spec.defaultImportKeys = spec.staticKeys;

spec.defaults = struct( ...
    'backend', tp.backend, ...
    'pythonExecutable', tp.pythonExecutable, ...
    'repoRoot', tp.repoRoot, ...
    'sam3Repo', tp.sam3Repo, ...
    'resolution', tp.resolution, ...
    'detectorCheckpointPath', tp.detectorCheckpointPath, ...
    'trackerCheckpointPath', tp.trackerCheckpointPath, ...
    'maxNumObjects', tp.maxNumObjects, ...
    'chunkSize', tp.chunkSize, ...
    'chunkOverlap', tp.chunkOverlap, ...
    'videoScoreThreshold', tp.videoScoreThreshold, ...
    'videoNewDetThreshold', tp.videoNewDetThreshold, ...
    'videoDetNmsThreshold', tp.videoDetNmsThreshold, ...
    'videoAssocIouThreshold', tp.videoAssocIouThreshold, ...
    'prompt', tp.prompt, ...
    'promptMode', tp.promptMode, ...
    'minScore', tp.minScore, ...
    'outputName', tp.outputName);

spec.labels = struct( ...
    'backend', 'Python backend', ...
    'pythonExecutable', 'Python executable', ...
    'repoRoot', 'SAM31 repo', ...
    'sam3Repo', 'Official SAM3.1 repo', ...
    'resolution', 'Resolution', ...
    'detectorCheckpointPath', 'Detector checkpoint', ...
    'trackerCheckpointPath', 'Tracker checkpoint', ...
    'maxNumObjects', 'Object slots', ...
    'chunkSize', 'Chunk size', ...
    'chunkOverlap', 'Chunk overlap', ...
    'videoScoreThreshold', 'Detection score', ...
    'videoNewDetThreshold', 'New-object score', ...
    'videoDetNmsThreshold', 'Detection NMS', ...
    'videoAssocIouThreshold', 'Association IoU', ...
    'prompt', 'Text prompt', ...
    'promptMode', 'Prompt mode', ...
    'minScore', 'Output score', ...
    'outputName', 'Output name');

spec.tips = struct();
spec.choices = struct();
spec.choices.backend = {'wsl','local'};
spec.choices.promptMode = {'text'};

spec.defaults = mergeDefaultsFromClassi(spec.defaults, classif);
end

function defaults = mergeDefaultsFromClassi(defaults, classif)
if isempty(classif)
    return;
end
sources = {};
try
    if isobject(classif) && isprop(classif, 'trainingParam') && isstruct(classif.trainingParam)
        sources{end+1} = classif.trainingParam; %#ok<AGROW>
    elseif isstruct(classif) && isfield(classif, 'trainingParam') && isstruct(classif.trainingParam)
        sources{end+1} = classif.trainingParam; %#ok<AGROW>
    end
catch
end
try
    if isobject(classif) && isprop(classif, 'executionParam') && isstruct(classif.executionParam)
        sources{end+1} = classif.executionParam; %#ok<AGROW>
    elseif isstruct(classif) && isfield(classif, 'executionParam') && isstruct(classif.executionParam)
        sources{end+1} = classif.executionParam; %#ok<AGROW>
    end
catch
end
keys = fieldnames(defaults);
for s = 1:numel(sources)
    src = sources{s};
    for i = 1:numel(keys)
        key = keys{i};
        if isfield(src, key) && ~isempty(src.(key))
            defaults.(key) = src.(key);
        end
    end
end
end
