function spec = executionSpec(classif)
% sam31.executionSpec  Execution-time parameter contract.

if nargin < 1
    classif = [];
end

tp = sam31.utils.defaultExecutionParam();
spec = struct();
spec.category = 'Pixel';
spec.defaultClasses = {'cell'};
spec.segmentationKind = 'instance_tracking';
spec.instanceSegmentation = true;
spec.summary = 'SAM3.1 instance segmentation and video tracking bridge.';
spec.staticKeys = {'backend','resolution','maxNumObjects','chunkSize', ...
    'chunkOverlap','videoScoreThreshold', ...
    'videoNewDetThreshold','videoAssocIouThreshold', ...
    'hotstartUnmatchThreshold','sam31Runner', ...
    'inferInstanceSegmentation','inferCellTracking', ...
    'inferBudPairing','budPairingSourceKey', ...
    'budPairingTypicalCellSize','budPairingMaxBirthAreaFraction', ...
    'budPairingMinParentAreaReferenceFraction', ...
    'budPairingMaxParentDistanceFraction', ...
    'budPairingMaxParentCentroidDistanceFraction', ...
    'budPairingFutureWindow','budPairingMinParentAgeFrames', ...
    'budPairingMaxFutureDistanceReferenceFraction', ...
    'budPairingMaxFutureCentroidDistanceReferenceFraction'};
spec.outputKeys = {};
spec.defaultImportKeys = spec.staticKeys;

spec.defaults = struct( ...
    'backend', tp.backend, ...
    'resolution', tp.resolution, ...
    'maxNumObjects', tp.maxNumObjects, ...
    'chunkSize', tp.chunkSize, ...
    'chunkOverlap', tp.chunkOverlap, ...
    'videoScoreThreshold', tp.videoScoreThreshold, ...
    'videoNewDetThreshold', tp.videoNewDetThreshold, ...
    'videoAssocIouThreshold', tp.videoAssocIouThreshold, ...
    'hotstartUnmatchThreshold', tp.hotstartUnmatchThreshold, ...
    'sam31Runner', tp.sam31Runner, ...
    'inferInstanceSegmentation', tp.inferInstanceSegmentation, ...
    'inferCellTracking', tp.inferCellTracking, ...
    'inferBudPairing', tp.inferBudPairing, ...
    'budPairingSourceKey', tp.budPairingSourceKey, ...
    'budPairingTypicalCellSize', tp.budPairingTypicalCellSize, ...
    'budPairingMaxBirthAreaFraction', tp.budPairingMaxBirthAreaFraction, ...
    'budPairingMinParentAreaReferenceFraction', tp.budPairingMinParentAreaReferenceFraction, ...
    'budPairingMaxParentDistanceFraction', tp.budPairingMaxParentDistanceFraction, ...
    'budPairingMaxParentCentroidDistanceFraction', tp.budPairingMaxParentCentroidDistanceFraction, ...
    'budPairingFutureWindow', tp.budPairingFutureWindow, ...
    'budPairingMinParentAgeFrames', tp.budPairingMinParentAgeFrames, ...
    'budPairingMaxFutureDistanceReferenceFraction', tp.budPairingMaxFutureDistanceReferenceFraction, ...
    'budPairingMaxFutureCentroidDistanceReferenceFraction', tp.budPairingMaxFutureCentroidDistanceReferenceFraction);

spec.labels = struct( ...
    'backend', 'Python backend', ...
    'resolution', 'Resolution', ...
    'maxNumObjects', 'Object slots', ...
    'chunkSize', 'Chunk size', ...
    'chunkOverlap', 'Chunk overlap', ...
    'videoScoreThreshold', 'Detection score', ...
    'videoNewDetThreshold', 'New-object score', ...
    'videoAssocIouThreshold', 'Association IoU', ...
    'hotstartUnmatchThreshold', 'Unmatched-track grace', ...
    'sam31Runner', 'Runner', ...
    'inferInstanceSegmentation', 'Instance segmentation', ...
    'inferCellTracking', 'Cell tracking', ...
    'inferBudPairing', 'Infer bud pairing', ...
    'budPairingSourceKey', 'Pairing source key', ...
    'budPairingTypicalCellSize', 'Typical cell size', ...
    'budPairingMaxBirthAreaFraction', 'Max bud area / cell', ...
    'budPairingMinParentAreaReferenceFraction', 'Min mother area / cell', ...
    'budPairingMaxParentDistanceFraction', 'Max mother distance / cell', ...
    'budPairingMaxParentCentroidDistanceFraction', 'Max centroid distance / cell', ...
    'budPairingFutureWindow', 'Future support frames', ...
    'budPairingMinParentAgeFrames', 'Min mother age', ...
    'budPairingMaxFutureDistanceReferenceFraction', 'Max future distance / cell', ...
    'budPairingMaxFutureCentroidDistanceReferenceFraction', 'Max future centroid / cell');

spec.tips = struct( ...
    'backend', 'Where the SAM31 Python runner is launched. Use wsl for the Linux SAM3 environment when Windows Python is unstable.', ...
    'resolution', 'Working resolution used by SAM3.1. 140/280/560 are lighter yeast-friendly modes; 1008 is heavier.', ...
    'maxNumObjects', 'Maximum number of object slots tracked at the same time during inference. Raise this if tracks disappear when many cells are present.', ...
    'chunkSize', 'Number of frames processed per temporal chunk. Use 0 to process the full movie at once; smaller chunks reduce VRAM at the cost of weaker ID continuity across chunk boundaries.', ...
    'chunkOverlap', 'Number of frames overlapped between temporal chunks for ID stitching. Must be smaller than chunk size; 4 is a useful starting point for dense movies.', ...
    'videoScoreThreshold', 'Detection score threshold for per-frame detections.', ...
    'videoNewDetThreshold', 'Threshold for accepting new detections during video propagation.', ...
    'videoAssocIouThreshold', 'IoU threshold used to associate objects across frames.', ...
    'hotstartUnmatchThreshold', 'Frames an unmatched hot-start track is retained before retirement. Default 3; larger values retain unmatched tracks longer and may increase stale-mask conflicts.', ...
    'sam31Runner', 'session keeps the SAM31 predictor loaded across ROIs; external starts a fresh Python process per ROI.', ...
    'inferInstanceSegmentation', 'Run the SAM31 instance segmentation stage and write/update the result label channel.', ...
    'inferCellTracking', 'Keep object IDs coherent over time. Requires instance segmentation; when disabled, labels are frame-local instance masks.', ...
    'inferBudPairing', 'After SAM31 tracking, infer bud-mother links and store them in cell_information.userData.lineageSources. Requires cell tracking.', ...
    'budPairingSourceKey', 'Optional key for this source under lineageSources; empty uses the output name.', ...
    'budPairingTypicalCellSize', 'Typical cell length in pixels. Use 0 to estimate it from the median object major-axis length at each birth frame.', ...
    'budPairingMaxBirthAreaFraction', 'Maximum newborn/bud area as a fraction of the area implied by the typical cell size.', ...
    'budPairingMinParentAreaReferenceFraction', 'Adaptive mother-area threshold as a fraction of the median eligible cell area at the birth frame.', ...
    'budPairingMaxParentDistanceFraction', 'Maximum mother-child mask distance at birth as a fraction of the typical cell diameter.', ...
    'budPairingMaxParentCentroidDistanceFraction', 'Maximum mother-child centroid distance at birth as a fraction of the typical cell diameter.', ...
    'budPairingFutureWindow', 'Number of frames after birth used to score continued mother-child proximity.', ...
    'budPairingMinParentAgeFrames', 'Minimum number of frames a non-initial object must exist before it can be used as a mother.', ...
    'budPairingMaxFutureDistanceReferenceFraction', 'Adaptive future mask-distance cap as a fraction of the median equivalent cell diameter at the birth frame.', ...
    'budPairingMaxFutureCentroidDistanceReferenceFraction', 'Adaptive future centroid-distance cap as a fraction of the median equivalent cell diameter at the birth frame.');
spec.choices = struct();
spec.choices.backend = {'local','wsl'};
spec.choices.resolution = {'140','280','560','1008'};
spec.choices.sam31Runner = {'session','external'};
spec.choices.inferInstanceSegmentation = {true,false};
spec.choices.inferCellTracking = {true,false};
spec.choices.inferBudPairing = {true,false};

spec.defaults = mergeDefaultsFromClassi(spec.defaults, classif);
end

function defaults = mergeDefaultsFromClassi(defaults, classif)
if isempty(classif)
    return;
end
sources = {};
try
    if isobject(classif) && isprop(classif, 'trainingParam') && isstruct(classif.trainingParam)
        sources{end+1} = struct('resolution', classif.trainingParam.resolution);
    elseif isstruct(classif) && isfield(classif, 'trainingParam') && isstruct(classif.trainingParam)
        sources{end+1} = struct('resolution', classif.trainingParam.resolution);
    end
catch
end
try
    if isobject(classif) && isprop(classif, 'executionParam') && isstruct(classif.executionParam)
        sources{end+1} = classif.executionParam;
    elseif isstruct(classif) && isfield(classif, 'executionParam') && isstruct(classif.executionParam)
        sources{end+1} = classif.executionParam;
    end
catch
end
keys = fieldnames(defaults);
for s = 1:numel(sources)
    src = sources{s};
    for i = 1:numel(keys)
        key = keys{i};
        if isfield(src, key) && ~isempty(src.(key))
            defaults.(key) = src.(key);
        end
    end
end
end
