function spec = executionSpec(classif)
% sam31.executionSpec  Execution-time parameter contract.

if nargin < 1
    classif = [];
end

tp = sam31.utils.defaultTrainingParam();
spec = struct();
spec.category = 'Pixel';
spec.defaultClasses = {'cell'};
spec.segmentationKind = 'instance_tracking';
spec.instanceSegmentation = true;
spec.summary = 'SAM3.1 instance segmentation and video tracking bridge.';
spec.staticKeys = {'resolution','detectorCheckpointPath','trackerCheckpointPath', ...
    'maxNumObjects','prompt','minScore','chunkSize','chunkOverlap', ...
    'videoScoreThreshold','videoNewDetThreshold', ...
    'videoDetNmsThreshold','videoAssocIouThreshold','sam31Runner'};
spec.outputKeys = {};
spec.defaultImportKeys = spec.staticKeys;

spec.defaults = struct( ...
    'resolution', {tp.resolution}, ...
    'detectorCheckpointPath', tp.detectorCheckpointPath, ...
    'trackerCheckpointPath', tp.trackerCheckpointPath, ...
    'maxNumObjects', tp.maxNumObjects, ...
    'prompt', tp.prompt, ...
    'minScore', tp.minScore, ...
    'chunkSize', tp.chunkSize, ...
    'chunkOverlap', tp.chunkOverlap, ...
    'videoScoreThreshold', tp.videoScoreThreshold, ...
    'videoNewDetThreshold', tp.videoNewDetThreshold, ...
    'videoDetNmsThreshold', tp.videoDetNmsThreshold, ...
    'videoAssocIouThreshold', tp.videoAssocIouThreshold, ...
    'sam31Runner', {tp.sam31Runner});

spec.labels = struct( ...
    'resolution', 'Resolution', ...
    'detectorCheckpointPath', 'Detector checkpoint', ...
    'trackerCheckpointPath', 'Tracker checkpoint', ...
    'maxNumObjects', 'Object slots', ...
    'prompt', 'Prompt', ...
    'minScore', 'Min mask score', ...
    'chunkSize', 'Chunk size', ...
    'chunkOverlap', 'Chunk overlap', ...
    'videoScoreThreshold', 'Detection score', ...
    'videoNewDetThreshold', 'New-object score', ...
    'videoDetNmsThreshold', 'Detection NMS', ...
    'videoAssocIouThreshold', 'Association IoU', ...
    'sam31Runner', 'Runner');

spec.tips = struct( ...
    'resolution', 'Working resolution used by SAM3.1. 280 is the yeast-friendly mode; 1008 is heavier.', ...
    'detectorCheckpointPath', 'Optional detector checkpoint. Empty uses the latest detector checkpoint under the classifier sam31_artifacts folder.', ...
    'trackerCheckpointPath', 'Optional tracker checkpoint. Empty uses the latest tracker checkpoint under the classifier sam31_artifacts folder.', ...
    'maxNumObjects', 'Maximum number of object slots tracked at the same time during inference. Raise this if tracks disappear when many cells are present.', ...
    'prompt', 'Text prompt used to initialize tracking on the first frame.', ...
    'minScore', 'Minimum score retained when converting SAM3.1 outputs to label masks.', ...
    'chunkSize', 'Frames per tracking chunk. 0 tracks the full selected ROI movie in one session.', ...
    'chunkOverlap', 'Frame overlap between chunks. Used only when chunkSize is greater than 0.', ...
    'videoScoreThreshold', 'Detection score threshold for per-frame detections.', ...
    'videoNewDetThreshold', 'Threshold for accepting new detections during video propagation.', ...
    'videoDetNmsThreshold', 'NMS threshold applied to detections.', ...
    'videoAssocIouThreshold', 'IoU threshold used to associate objects across frames.', ...
    'sam31Runner', 'session keeps the SAM31 predictor loaded across ROIs; external starts a fresh Python process per ROI.');
spec.choices = struct();
spec.choices.resolution = {'280','1008'};
spec.choices.sam31Runner = {'session','external'};

spec.defaults = mergeDefaultsFromClassi(spec.defaults, classif);
end

function defaults = mergeDefaultsFromClassi(defaults, classif)
if isempty(classif)
    return;
end
sources = {};
try
    if isobject(classif) && isprop(classif, 'trainingParam') && isstruct(classif.trainingParam)
        sources{end+1} = classif.trainingParam;
    elseif isstruct(classif) && isfield(classif, 'trainingParam') && isstruct(classif.trainingParam)
        sources{end+1} = classif.trainingParam;
    end
catch
end
try
    if isobject(classif) && isprop(classif, 'executionParam') && isstruct(classif.executionParam)
        sources{end+1} = classif.executionParam;
    elseif isstruct(classif) && isfield(classif, 'executionParam') && isstruct(classif.executionParam)
        sources{end+1} = classif.executionParam;
    end
catch
end
keys = fieldnames(defaults);
for s = 1:numel(sources)
    src = sources{s};
    for i = 1:numel(keys)
        key = keys{i};
        if isfield(src, key) && ~isempty(src.(key))
            defaults.(key) = src.(key);
        end
    end
end
end
