function spec = trainingSpec(~)
%SAM31.TRAININGSPEC Movie image and managed tracked-mask GT.

spec = [ ...
    classifierBinding.newBinding( ...
        'param','inputChannelName', 'type','channel', 'role','roi_image', ...
        'quality','input','semantic','microscopy_movie', ...
        'label','[INPUT] Microscopy movie channel', 'required',true, ...
        'storage','classifierInputChannels', 'cardinality','one', ...
        'tip','Single intensity channel exported to the SAM3.1 framebank.'), ...
    classifierBinding.newBinding( ...
        'param','groundTruthChannelName', 'type','channel', ...
        'role','tracked_mask_ground_truth','quality','gt', ...
        'semantic','stable_tracks', 'label','[GT] Reviewed stable tracks', ...
        'required',true, 'storage','annotation', 'editable',false, ...
        'componentId','tracklets', ...
        'tip',['Managed reviewed stable-ID channel. New classifiers use ' ...
               'gt_<classifier>_stable_tracks; legacy names remain valid.']) ...
    ];
end
