function spec = trainingParameterSpec(~)
%SAM31.TRAININGPARAMETERSPEC Explicit SAM3.1 module-training controls.
spec=[ ...
    item('trainModules','SAM3.1 sub-modules to train','Training scope', ...
        'Select semantic, instance, video-memory, their combination, or all.'), ...
    item('resolution','SAM3.1 working resolution','Architecture', ...
        'Resolution used by the trained SAM3.1 modules.'), ...
    item('validationFraction','ROI validation fraction','Validation', ...
        'Whole-ROI holdout used when no explicit validation split exists.'), ...
    item('epochs','SAM3.1 training epochs','Optimization','Training epochs.'), ...
    item('saveFreq','Checkpoint interval (optimizer steps)','Artifact', ...
        'Frequency at which SAM3.1 checkpoints are written.'), ...
    item('clipLength','Video-memory clip length (frames)','Video memory', ...
        'Frames per temporal training clip.'), ...
    item('clipStride','Video-memory clip stride (frames)','Video memory', ...
        'Frame stride between exported clips.'), ...
    item('maxTracksPerClip','Maximum GT tracks per clip','Video memory', ...
        'Maximum reviewed trajectories retained in each clip.'), ...
    item('minVisibleFrames','Minimum visible frames per GT track','Video memory', ...
        'Tracks visible for fewer frames are excluded from video-memory training.') ...
    ];
end

function out=item(param,label,group,tip)
out=struct('param',param,'label',label,'group',group,'tip',tip, ...
    'choiceLabels',{{}});
end
