function spec = trainingSpec(~)
%SAM31.TRAININGSPEC Movie image and managed tracked-mask GT.

spec = [ ...
    classifierBinding.newBinding( ...
        'param','inputChannelName', 'type','channel', 'role','roi_image', ...
        'label','Training movie image', 'required',true, ...
        'storage','classifierInputChannels', 'cardinality','one', ...
        'tip','Single intensity channel exported to the SAM3.1 framebank.'), ...
    classifierBinding.newBinding( ...
        'param','groundTruthChannelName', 'type','channel', ...
        'role','tracked_mask_ground_truth', 'label','Tracked-instance GT', ...
        'required',true, 'storage','annotation', 'editable',false, ...
        'componentId','tracklets', ...
        'tip','Managed <classifier id>_cell channel containing reviewed tracks.') ...
    ];
end
