function tp = defaultTrainingParam()
% CNN_LSTM.utils.defaultTrainingParam
% Default training parameters for CNN+LSTM classifier.

    tip = { ...
        'Check box to train CNN', ...
        'Check box to compute CNN activations', ...
        'Check box to train the LSTM network', ...
        'Check box to asssemble the CNN and LSTM networks', ...
        'Specify if each frame should be classified, or if one class is expected for the whole sequence of images', ...
        'Choose the training method', ...
        'Choose the CNN', ...
        'Choose the size of the mini batch; Higher values require more memory and are prone to errors', ...
        'Enter the number of epochs', ...
        'Enter the initial learning rate', ...
        'Enter the learning rate drop factor', ...
        'Choose whether and how training and validation data should be shuffled during training', ...
        'Enter fraction of the data to be used for training vs validation during training', ...
        'Enter the magnitude of translation for data augmentation (in pixels)', ...
        'Enter the magnitude of rotation for data augmentation (in degrees)', ...
        'Specify value for L2 regularization', ...
        'Check to use a dropout layer', ...
        'Value for dropout regularization', ...
        'Range of random scale factor for CNN augmentation (e.g. [0.8 1.0])', ...
        'Enable random flips (left/right & up/down) during CNN augmentation', ...
        'Crop-in scale range for CNN augmentation (e.g. [0.8 1.0])', ...
        'Contrast multiplier range for CNN augmentation (e.g. [0.85 1.15])', ...
        'Brightness offset range (additive, e.g. [-0.10 0.10])', ...
        'Gamma exponent range for CNN augmentation (e.g. [0.9 1.1])', ...
        'Saturation multiplier range (RGB only, e.g. [0.95 1.05])', ...
        'Maximum hue jitter (0-0.5, small values recommended)', ...
        'Std-dev of Gaussian noise for CNN augmentation (set 0 to disable)', ...
        'Defocus sigma range in pixels (e.g. [0.3 1.0])', ...
        'Probability to apply defocus blur (e.g. 0.5)', ...
        'Choose the fraction of the data to be used for training vs validation during LSTM training', ...
        'Enter the size of the hidden unit', ...
        'Choose the size of the mini batch for LSTM training; Higher values require more memory and are prone to errors', ...
        'Enter the LSTM initial learning rate', ...
        'Enter the number of epochs for LSTM training', ...
        'Enter the length of the sequences in frames; put 0 if all frames should be used upon training', ...
        'Enter the dropping factor in learning rate', ...
        'Choose execution environment', ...
        'Select initial version of network to start training with; Default: ImageNet', ...
        'Minority balancing mode (none/auto)', ...
        'Activate balancing if min/max ratio <= this value', ...
        'Percentile for multi-minority selection (0=off)', ...
        '#Negatives per #Positives windows (e.g. 1 = 1:1)', ...
        'Positive window stride as a fraction of L', ...
        'Negative window stride as a fraction of L', ...
        'Keep validation distribution unbalanced (true/false)', ...
        'Fraction of ROIs used when formatting the LSTM training set', ...
        'Random seed used when sampling ROIs / frames for formatting', ...
        'Enable cropping when formatting the LSTM training set (true/false)', ...
        'Crop center [cx cy] used for formatting the LSTM training set', ...
        'Crop size [w h] used for formatting the LSTM training set', ...
        'Undersample majority classes (1 = no undersampling)', ...
        'Storage backend for formatted data (''hdf5'' or ''tiff'')' ...
        };

    tp = struct(...
        'train_CNN_classifier',true,...
        'compute_CNN_activations',true,...
        'train_LSTM_network',true,...
        'assemble_network',true,...
        'classifier_output',{{'sequence-to-sequence','sequence-to-one','sequence-to-sequence'}},...
        'CNN_training_method',{{'adam','sgdm','adam'}},...
        'CNN_network',{{'googlenet','inceptionresnetv2','inceptionv3','resnet50','resnet18','googlenet'}},...
        'CNN_mini_batch_size',8,...
        'CNN_max_epochs',6,...
        'CNN_initial_learning_rate',0.0001,...
        'CNN_learn_rate_drop_factor',0.9,...
        'CNN_data_shuffling',{{'once','every-epoch','never','every-epoch'}},...
        'CNN_data_splitting_factor',0.7,...
        'CNN_translation_augmentation',[-5 5],...
        'CNN_rotation_augmentation',[-5 5],...
        'CNN_l2_regularization',1e-5,...
        'CNN_use_dropout',true,...
        'CNN_dropout',0.5,...
        'CNN_rand_scale',[0.8 1.0], ...
        'CNN_rand_flip',true, ...
        'CNN_crop_scale',[0.8 1.0], ...
        'CNN_contrast_range',[1 1], ...
        'CNN_brightness_range',[0 0], ...
        'CNN_gamma_range',[1 1], ...
        'CNN_saturation_range',[1 1], ...
        'CNN_hue_delta',0, ...
        'CNN_noise_sigma',0, ...
        'CNN_defocus_sigma_range',[0 0], ...
        'CNN_defocus_prob',0, ...
        'LSTM_data_splitting_factor',0.9,...
        'LSTM_hidden_size',150,...
        'LSTM_mini_batch_size',8,...
        'LSTM_initial_learning_rate', 1e-4,...
        'LSTM_max_epochs', 50,...
        'LSTM_sequence_length', 40,...
        'LSTM_learn_rate_drop_factor', 0.9,...
        'execution_environment',{{'auto','parallel','cpu','gpu','multi-gpu','auto'}},...
        'transfer_learning',{{'ImageNet','ImageNet'}},...
        'LSTM_minority_mode','none',...
        'LSTM_minority_min_ratio',0.30,...
        'LSTM_minority_percentile',0.00,...
        'LSTM_pos_neg_ratio',1.0,...
        'LSTM_win_stride_pos_frac',0.10,...
        'LSTM_win_stride_neg_frac',1.00,...
        'LSTM_keep_valid_distrib',true,...
        'Format_Fraction',1.0, ...
        'Format_Seed',12345, ...
        'Format_Crop',false, ...
        'Format_CropCenter',[88 194], ...
        'Format_CropSize',[60 60], ...
        'Format_UndersampleMajority',1.0, ...
        'Format_StorageBackend',{{'hdf5','tiff','hdf5'}}, ...
        'tip',{tip});
end
