function spec = annotationSpec(classif)
%DEEPLAB_PIXEL_CLASSIFICATION.ANNOTATIONSPEC Semantic-mask GT contract.

spec = annotationManager.newSpec(classif);
execution = deeplab_pixel_classification.executionSpec(classif);
outputName = char(string(execution.defaults.outputName));
gtName = deeplab_pixel_classification.annotationChannelName(classif);
prediction = ['results_' outputName];

component = annotationManager.newComponent( ...
    'id', 'semantic_mask', ...
    'kind', 'semantic_mask', ...
    'storage', 'channel', ...
    'coverageUnit', 'frame', ...
    'editor', 'semantic_mask', ...
    'bootstrap', 'copy_channel', ...
    'classes', spec.classes, ...
    'groundTruth', annotationManager.newAsset('channel', gtName, ...
        'quality','gt','producer','human_review','semantic','semantic_mask'), ...
    'prediction', annotationManager.newAsset( ...
        'channel', prediction, 'channelCandidates', {prediction}, ...
        'quality','pred','producer','deeplab_pixel_classification', ...
        'semantic','semantic_mask'));

spec.displayName = 'Semantic segmentation';
spec.components = component;
spec.defaultEditor = 'semantic_mask';
end
