function spec = trainingSpec(~)
%DEEPLAB_PIXEL_CLASSIFICATION.TRAININGSPEC Semantic training resources.

spec = [ ...
    classifierBinding.newBinding( ...
        'param','inputChannelNames', 'type','channel', 'role','roi_image', ...
        'label','Training image channels', 'required',true, ...
        'storage','classifierInputChannels', 'cardinality','many', ...
        'tip','Ordered ROI image channels used as the DeepLab input.'), ...
    classifierBinding.newBinding( ...
        'param','groundTruthChannelName', 'type','channel', ...
        'role','semantic_mask_ground_truth', 'label','Semantic-mask GT', ...
        'required',true, 'storage','annotation', 'editable',false, ...
        'componentId','semantic_mask', ...
        'tip','Managed semantic annotation channel consumed by formatting.') ...
    ];
end
