function scope = trainingScopeSpec(~)
%DEEPLAB_PIXEL_CLASSIFICATION.TRAININGSCOPESPEC Semantic-segmentation contract.
scope=classifierBinding.newTrainingScope( ...
    'module','deeplab_pixel_classification', ...
    'displayName','DeepLab v3+ — semantic segmentation', ...
    'objective','Predict a reviewed semantic class for every image pixel.', ...
    'trainedComponents',{'DeepLab v3+ semantic segmentation network'}, ...
    'frozenComponents',{'Instance segmentation modules','tracking modules','lineage modules'}, ...
    'datasetUnit','Microscopy images paired with reviewed indexed semantic masks.', ...
    'splitPolicy',['Legacy formatted-image split controlled by CNN_data_splitting_factor; ' ...
        'this split is not guaranteed ROI-disjoint.'], ...
    'outputParameter','outputName','outputQuality','pred', ...
    'outputSemantic','semantic segmentation mask', ...
    'outputTemplate','results_<outputName>', ...
    'canonicalOutput','results_pred_deeplab_semantic_mask', ...
    'notes',{'Probability output is also PRED and never ground truth.'});
end
