function spec = trainingSpec(~)
%DEEPLAB_PIXEL_CLASSIFICATION.TRAININGSPEC Semantic training resources.

spec = [ ...
    classifierBinding.newBinding( ...
        'param','inputChannelNames', 'type','channel', 'role','roi_image', ...
        'quality','input','semantic','microscopy_images', ...
        'label','[INPUT] Microscopy image channels', 'required',true, ...
        'storage','classifierInputChannels', 'cardinality','many', ...
        'tip','Ordered ROI image channels used as the DeepLab input.'), ...
    classifierBinding.newBinding( ...
        'param','groundTruthChannelName', 'type','channel', ...
        'role','semantic_mask_ground_truth','quality','gt', ...
        'semantic','semantic_mask', 'label','[GT] Reviewed semantic mask', ...
        'required',true, 'storage','annotation', 'editable',false, ...
        'componentId','semantic_mask', ...
        'tip','Managed semantic annotation channel consumed by formatting.') ...
    ];
end
