function spec = annotationSpec(classif)
%TRACKASTRA.ANNOTATIONSPEC Stable-tracklet mask GT contract.

spec = annotationManager.newSpec(classif);
execution = trackastra.executionSpec(classif);
outputName = char(string(execution.defaults.outputName));
prediction = ['results_' outputName];
gtName = trackastra.annotationChannelName(classif);

component = annotationManager.newComponent( ...
    'id', 'tracklets', ...
    'kind', 'tracked_instances', ...
    'storage', 'channel', ...
    'coverageUnit', 'frame', ...
    'editor', 'tracking', ...
    'bootstrap', 'copy_channel', ...
    'classes', {'tracklet'}, ...
    'groundTruth', annotationManager.newAsset('channel', gtName, ...
        'quality','gt','producer','human_review', ...
        'semantic','stable_tracks'), ...
    'prediction', annotationManager.newAsset( ...
        'channel', prediction, 'channelCandidates', {prediction}, ...
        'quality','pred','producer','trackastra', ...
        'semantic','stable_tracks'));

spec.displayName = 'Cell tracking';
spec.components = component;
spec.defaultEditor = 'tracking';
end
