function spec = executionSpec(classif)
% trackastra.executionSpec  Pipeline execution-time parameter contract.

if nargin < 1
    classif = [];
end

p = trackastra.utils.defaultExecutionParam();
spec = struct();
spec.category = 'Pixel';
spec.defaultClasses = {'tracklet'};
spec.segmentationKind = 'instance_tracking';
spec.instanceSegmentation = false;
spec.summary = ['Trackastra linker: consumes raw images plus frame-local instance ' ...
    'masks and produces an indexed channel with stable tracklet IDs.'];
spec.staticKeys = {'pretrainedModel','trackingMode','device','batchSize','nWorkers','maxDistance', ...
    'maxFrameGap','divisionIdentityMode','normalizeImages'};
spec.staticKeys = [spec.staticKeys ...
    {'jointDecoder','buddingProposal','jointOverwriteOutputFamily'}];
spec.artifactKeys = {'modelSource','customModelPath','checkpointPath'};
spec.environmentKeys = {'pythonExecutable'};
spec.outputKeys = {'outputName','jointOutputFamilyName'};
spec.defaultImportKeys = [spec.staticKeys spec.outputKeys];
spec.outputProvenance = struct('quality','pred','producer','trackastra', ...
    'semantic','stable_tracks','template','results_<outputName>');
spec.defaults = p;

spec.labels = struct( ...
    'imageChannelName', '[INPUT] Microscopy image channel', ...
    'instanceChannelName', '[INPUT] Frame-local instance masks', ...
    'outputName', '[PRED] Stable-track output name', ...
    'pretrainedModel', 'Pretrained model', ...
    'trackingMode', 'Linking mode', ...
    'device', 'Device', ...
    'batchSize', 'Inference batch size', ...
    'nWorkers', 'Feature workers', ...
    'maxDistance', 'Maximum link distance', ...
    'maxFrameGap', 'Maximum missing frames to bridge', ...
    'divisionIdentityMode', 'Identity at division', ...
    'jointDecoder', 'Joint tracking-lineage decoder', ...
    'buddingProposal', 'Budding-aware Trackastra proposal', ...
    'jointOutputFamilyName', '[PRED] Joint lineage family', ...
    'jointOverwriteOutputFamily', 'Replace joint lineage family', ...
    'normalizeImages', 'Normalize images');

spec.tips = struct( ...
    'imageChannelName', 'Intensity image corresponding to the instance masks.', ...
    'instanceChannelName', 'Indexed mask channel. Labels may be frame-local; Trackastra assigns tracklet IDs.', ...
    'outputName', ['Physical ROI prediction channel is results_<outputName>. ' ...
        'The canonical new name is results_pred_trackastra_tracks.'], ...
    'pretrainedModel', 'For ordinary 2-D microscopy, general_2d is the standard starting point.', ...
    'trackingMode', 'greedy supports divisions; greedy_nodiv forbids them; ilp requires optional ILP dependencies.', ...
    'device', 'automatic chooses CUDA when available.', ...
    'batchSize', '0 uses the model/device default.', ...
    'nWorkers', '0 avoids multiprocessing overhead and is safest when launched from MATLAB on Windows.', ...
    'maxDistance', '0 leaves the Trackastra default; positive values constrain candidate links in pixels.', ...
    'maxFrameGap', '1 allows a continuation link from t to t+2 across one missing detection; 0 restricts links to adjacent frames.', ...
    'divisionIdentityMode', 'continuing_parent preserves the most spatially continuous child as the mother; symmetric starts a new track for both daughters.', ...
    'jointDecoder', ['Use the packaged MoMA HGB division scorer and global solver on the Trackastra candidate graph before stable track IDs are created. ' ...
        'This is an explicit opt-in because the current division model is calibrated on MoMA cavities.'], ...
    'buddingProposal', ['Keep the pretrained Trackastra model for ordinary links, use the packaged budding-finetuned model to add/re-score bud candidates, and restore bounded small low-overlap birth candidates. ' ...
        'The geometric candidates have conservative temporal scores and are evaluated by the typed division head. Requires the joint decoder. If modelSource is custom, that custom Trackastra artifact is used as the proposal model.'], ...
    'jointOutputFamilyName', ['PRED cell-model lineage family created from ' ...
        'jointly selected divisions; no mask channel is duplicated.'], ...
    'jointOverwriteOutputFamily', 'Replace an existing family with the same name.', ...
    'normalizeImages', 'Apply Trackastra image normalization before feature extraction.');

spec.choices = struct();
spec.choices.pretrainedModel = {'general_2d','general_3d','general_2d_w_SAM2_features'};
spec.choices.trackingMode = {'greedy','greedy_nodiv','ilp'};
spec.choices.device = {'automatic','cuda','cpu','mps'};
spec.choices.divisionIdentityMode = {'continuing_parent','symmetric'};
spec.choices.jointDecoder = {false,true};
spec.choices.buddingProposal = {false,true};
spec.choices.jointOverwriteOutputFamily = {true,false};
spec.choices.normalizeImages = {true,false};

spec.defaults = mergeDefaults(spec.defaults, classif);
end

function defaults = mergeDefaults(defaults, classif)
if isempty(classif)
    return;
end
sources = {};
try
    if isprop(classif,'executionParam') && isstruct(classif.executionParam)
        sources{end+1} = classif.executionParam; %#ok<AGROW>
    end
catch
end
for s = 1:numel(sources)
    keys = fieldnames(sources{s});
    for i = 1:numel(keys)
        if isfield(defaults, keys{i}) && ~isempty(sources{s}.(keys{i}))
            defaults.(keys{i}) = sources{s}.(keys{i});
        end
    end
end
end
