function [familyId, report] = persistJointLineage( ...
        roiobj, tracked, channelName, param, jointAudit, auditPath)
%TRACKASTRA.PERSISTJOINTLINEAGE Materialize decoded divisions without masks.

if ~isfield(jointAudit,'lineage_edges')
    error('trackastra:InvalidJointAudit', ...
        'Joint decoder audit has no lineage_edges field.');
end
lineageResult = struct('edges',jointAudit.lineage_edges);
[model,loadReport] = roiobj.loadCellModel('MigrateLegacy',true);
[model,familyId,applyReport] = cellModel.applyLineageResult( ...
    model,tracked,channelName,'<auto>', ...
    char(string(param.jointOutputFamilyName)),lineageResult, ...
    logical(param.jointOverwriteOutputFamily), ...
    'trackastra_joint_cell_latent_model');
model.provenance.last_classifier = ...
    'trackastra_joint_cell_latent_model';
model.provenance.last_audit_artifact = char(string(auditPath));
saveReport = roiobj.saveCellModel(model);
report = struct( ...
    'load',loadReport, ...
    'apply',applyReport, ...
    'save',saveReport);
end
