function spec = trainingSpec(~)
%TRACKASTRA.TRAININGSPEC Intensity image and stable-tracklet GT.

spec = [ ...
    classifierBinding.newBinding( ...
        'param','imageChannelName', 'type','channel', 'role','roi_image', ...
        'quality','input', 'semantic','microscopy_image', ...
        'label','[INPUT] Microscopy image', 'required',true, ...
        'legacyFallback','classifierInputChannels', ...
        'tip','Raw/intensity image exported beside the Trackastra GT.'), ...
    classifierBinding.newBinding( ...
        'param','groundTruthChannelName', 'type','channel', ...
        'role','tracked_mask_ground_truth', 'quality','gt', ...
        'semantic','stable_tracks', 'label','[GT] Reviewed stable tracks', ...
        'required',true, 'allowAuto',true, ...
        'tip','Indexed stable-tracklet channel; auto uses the managed annotation channel.') ...
    ];
end
