function spec = trainingParameterSpec(~)
%TRACKASTRA.TRAININGPARAMETERSPEC Clarify that this trains Trackastra only.
spec = [ ...
    item('validationFraction','ROI validation fraction','Validation', ...
        'ROI fraction held out when no explicit validation split exists.'), ...
    item('epochs','Trackastra training epochs','Optimization', ...
        'Trains the Trackastra association model, not the latent tracker.'), ...
    item('initialModelPath','Initial Trackastra model','Initialization', ...
        'Optional Trackastra folder used only to initialize this training.'), ...
    item('features','Trackastra object features','Architecture', ...
        'Feature extractor used by Trackastra.'), ...
    item('device','Trackastra training device','Runtime','cuda or cpu.'), ...
    item('modelName','Immutable Trackastra model name','Artifact', ...
        'Output folder for the trained Trackastra model.') ...
    ];
end
function out=item(param,label,group,tip)
out=struct('param',param,'label',label,'group',group,'tip',tip, ...
    'choiceLabels',{{}});
end
