function scope = trainingScopeSpec(~)
%TRACKASTRA.TRAININGSCOPESPEC User-facing ownership contract.
scope=classifierBinding.newTrainingScope( ...
    'module','trackastra', ...
    'displayName','Trackastra — stable track association', ...
    'objective','Associate cell detections through time and assign stable track IDs.', ...
    'trainedComponents',{'Trackastra temporal association model'}, ...
    'frozenComponents',{'CellposeSAM','latent EDGE/APPEAR/END tracker','mother/NULL lineage linker'}, ...
    'datasetUnit','Intensity movies paired with reviewed stable-track GT masks.', ...
    'splitPolicy','ROI-disjoint validation; GUI test ROIs are excluded.', ...
    'outputParameter','outputName','outputQuality','pred', ...
    'outputSemantic','stable cell tracks', ...
    'outputTemplate','results_<outputName>', ...
    'canonicalOutput','results_pred_trackastra_tracks');
end
