function spec = executionSpec(classif)
%BUDMOTHERLINKER.EXECUTIONSPEC Classifier and pipeline contract.

if nargin < 1, classif = []; end
p = budMotherLinker.utils.defaultExecutionParam();
if ~isempty(classif)
    try
        if isprop(classif, 'executionParam') && isstruct(classif.executionParam)
            p = budMotherLinker.utils.applyOverrides(p, classif.executionParam);
        end
    catch
    end
end

spec = struct();
spec.category = 'Tracking';
spec.defaultClasses = {'mother-bud link'};
spec.summary = ['Trainable lineage classifier using 16 LYN-compatible geometric ' ...
    'descriptors and a boosted-tree candidate ranker.'];
spec.staticKeys = { ...
    'inputFamily','outputFamilyName','frameEnd','minLifetime','maxBirthArea', ...
    'minParentAge','maxParentCentroidDistance','maxParentContourDistance', ...
    'maxCandidates','rankMarginThreshold','trackingLoadGuard', ...
    'maxNewTracksPerFrame','globalSolver','motherRefractoryFrames', ...
    'youngMotherFrames','solverBeamSize','reviewGlobalReassignments', ...
    'overwriteOutputFamily','debug'};
spec.artifactKeys = {'modelSource','modelPath'};
spec.environmentKeys = {};
% The package loads its own exported HGB artifact. It does not use the
% historical <classifier-id>.mat network loaded by classi.loadClassifier.
spec.requiresRuntimeClassifier = false;
spec.outputKeys = {'outputFamilyName'};
spec.defaultImportKeys = [spec.staticKeys spec.outputKeys];
spec.outputProvenance = struct('quality','pred', ...
    'producer','budMotherLinker','semantic','mother_bud_lineage', ...
    'template','<outputFamilyName>');
spec.defaults = p;
spec.labels = struct( ...
    'trackChannelName','[INPUT] Stable tracked-label channel', ...
    'inputFamily','Input lineage family', ...
    'outputFamilyName','[PRED] Mother–bud lineage family', ...
    'frameEnd','Last frame', ...
    'minLifetime','Minimum bud lifetime', ...
    'maxBirthArea','Maximum bud birth area', ...
    'minParentAge','Minimum mother age', ...
    'maxParentCentroidDistance','Maximum centroid distance', ...
    'maxParentContourDistance','Maximum contour distance', ...
    'maxCandidates','Maximum mother candidates', ...
    'rankMarginThreshold','Automatic-link margin', ...
    'trackingLoadGuard','Tracking-load guard', ...
    'maxNewTracksPerFrame','Maximum new tracks per frame', ...
    'globalSolver','Global temporal solver', ...
    'motherRefractoryFrames','Mother refractory window (frames)', ...
    'youngMotherFrames','New-daughter maturation window (frames)', ...
    'solverBeamSize','Global solver beam size', ...
    'reviewGlobalReassignments','Review globally changed links', ...
    'overwriteOutputFamily','Overwrite output family', ...
    'debug','Debug output');
spec.tips = struct( ...
    'trackChannelName','Indexed masks whose labels are stable track identifiers.', ...
    'inputFamily','Optional source family used to preserve latent states; auto resolves from the mask provider.', ...
    'outputFamilyName',['Dedicated PRED family that owns the predicted ' ...
        'mother–bud genealogy. New default: pred_bud_mother_lineage.'], ...
    'rankMarginThreshold','Negative uses the calibration stored with the selected model.', ...
    'globalSolver','Jointly decodes all event links with hard temporal biology constraints.', ...
    'motherRefractoryFrames','Forbids repeated budding by one mother inside this inclusive window.', ...
    'youngMotherFrames','Forbids a newly born daughter from immediately becoming a mother.', ...
    'reviewGlobalReassignments','Routes a globally changed local prediction to review before persistence.', ...
    'modelSource','builtin uses the bundled Project47 model; trained uses the classifier artifact.', ...
    'modelPath','Classifier-relative trained model artifact. It is not a pipeline static parameter.');
spec.choices = struct( ...
    'inputFamily',{{'<auto>'}}, ...
    'modelSource',{{'builtin','trained'}}, ...
    'trackingLoadGuard',{{true,false}}, ...
    'globalSolver',{{true,false}}, ...
    'reviewGlobalReassignments',{{true,false}}, ...
    'overwriteOutputFamily',{{true,false}}, ...
    'debug',{{false,true}});
end
