function spec = trainingSpec(~)
%BUDMOTHERLINKER.TRAININGSPEC Typed resources used to train lineage links.

spec = [ ...
    classifierBinding.newBinding( ...
        'param','trackChannelName', 'type','channel', 'role','mask_roi_image', ...
        'label','Reviewed tracked-mask GT', 'required',true, ...
        'legacyFallback','classifierInputChannels', ...
        'tip','Indexed masks whose labels are stable reviewed track IDs.'), ...
    classifierBinding.newBinding( ...
        'param','groundTruthFamily', 'type','cellModelFamily', ...
        'role','lineage_ground_truth', 'label','Reviewed lineage GT', ...
        'required',true, 'allowAuto',true, 'autoValue','<auto>', ...
        'tip','Cell-model family containing the reviewed mother-bud relations.') ...
    ];
end
