function spec = trainingSpec(~)
%BUDMOTHERLINKER.TRAININGSPEC Typed resources used to train lineage links.

spec = [ ...
    classifierBinding.newBinding( ...
        'param','trackChannelName', 'type','channel', 'role','mask_roi_image', ...
        'quality','gt', 'semantic','stable_tracks', ...
        'label','[GT/INPUT] Reviewed stable tracks', 'required',true, ...
        'legacyFallback','classifierInputChannels', ...
        'tip','Indexed masks whose labels are stable reviewed track IDs.'), ...
    classifierBinding.newBinding( ...
        'param','groundTruthFamily', 'type','cellModelFamily', ...
        'role','lineage_ground_truth', 'quality','gt', ...
        'semantic','mother_bud_lineage', ...
        'label','[GT] Reviewed mother–bud lineage', ...
        'required',true, 'allowAuto',true, 'autoValue','<auto>', ...
        'tip','Cell-model family containing the reviewed mother-bud relations.') ...
    ];
end
