function scope = trainingScopeSpec(~)
%BUDMOTHERLINKER.TRAININGSCOPESPEC User-facing ownership contract.
scope=classifierBinding.newTrainingScope( ...
    'module','budMotherLinker', ...
    'displayName','Bud–mother linker — geometric lineage ranker', ...
    'objective','Rank candidate mothers for each reviewed new-bud event.', ...
    'trainedComponents',{'16-feature boosted-tree mother ranker'}, ...
    'frozenComponents',{'Segmentation','Trackastra','latent EDGE/APPEAR/END tracker','stable track IDs'}, ...
    'datasetUnit','Reviewed stable tracks and reviewed mother–bud lineage GT.', ...
    'splitPolicy','Whole-ROI validation held out from selected train ROIs; test ROIs are untouched.', ...
    'outputParameter','outputFamilyName','outputQuality','pred', ...
    'outputSemantic','mother–bud lineage family', ...
    'outputTemplate','<outputFamilyName>', ...
    'canonicalOutput','pred_bud_mother_lineage');
end
