function spec = trainingParameterSpec(~)
%BUDMOTHERLINKER.TRAININGPARAMETERSPEC Clear geometric-linker labels.
spec = [ ...
    item('groundTruthSource','Optional external reviewed lineage GT','Data', ...
        ['Optional reviewed SQLite database or accepted_lineage.csv. Empty ' ...
         'uses the reviewed lineage stored in each ROI.']), ...
    item('validationFraction','ROI validation fraction','Validation', ...
        'Held-out ROI fraction when no explicit validation split exists.'), ...
    item('minLifetime','Minimum new-bud lifetime (frames)','Candidate events', ...
        'Shorter new trajectories are excluded from mother-link training.'), ...
    item('maxBirthArea','Maximum new-bud birth area (pixels)','Candidate events', ...
        'Larger appearing objects are excluded from new-bud events.'), ...
    item('minParentAge','Minimum candidate-mother age (frames)','Candidate mothers', ...
        'A candidate mother must already have existed for this many frames.'), ...
    item('maxParentCentroidDistance','Maximum mother centroid distance (pixels)', ...
        'Candidate mothers','Centroid-distance candidate cutoff.'), ...
    item('maxParentContourDistance','Maximum mother contour distance (pixels)', ...
        'Candidate mothers','Contour-distance candidate cutoff.'), ...
    item('maxCandidates','Candidate mothers per new bud','Candidate mothers', ...
        'Maximum ranked mother candidates retained for each new-bud event.'), ...
    item('maxIter','Boosted-tree iterations','Optimization', ...
        'Number of HistGradientBoosting iterations.'), ...
    item('learningRate','Boosted-tree learning rate','Optimization', ...
        'HistGradientBoosting learning rate.'), ...
    item('maxLeafNodes','Maximum leaves per tree','Optimization', ...
        'Maximum terminal nodes in each boosted tree.'), ...
    item('minSamplesLeaf','Minimum observations per leaf','Optimization', ...
        'Minimum formatted candidate rows in each tree leaf.'), ...
    item('l2Regularization','Boosted-tree L2 regularization','Optimization', ...
        'L2 penalty applied to boosted-tree leaf weights.'), ...
    item('randomState','Training random seed','Reproducibility', ...
        'Deterministic boosted-tree random seed.'), ...
    item('targetAutoPrecision','Target automatic-link precision','Calibration', ...
        'Validation precision target used to calibrate automatic linking.'), ...
    item('modelName','Immutable geometric-linker model name','Artifact', ...
        'Use a new domain-qualified vNNN name for every completed artifact.'), ...
    item('transfer_learning','Model initialization','Initialization', ...
        'The current geometric linker is fitted from the formatted dataset.') ...
    ];
end

function out=item(param,label,group,tip)
out=struct('param',param,'label',label,'group',group,'tip',tip, ...
    'choiceLabels',{{}});
end
