function initUserPreferences

         if numel(userpath)==0
                 userpath('reset')
             end

            pth=userpath;
 
           fle= fullfile(pth,'Detecdiv/userprefs.mat');
            if exist(fle)
                load(fle)
            else % structure must me created

               if ~exist(fullfile(userpath,'Detecdiv'))
                    mkdir(fullfile(userpath,'Detecdiv'))
               end


            tip={'Keyboard shortcuts used to assign a class to an image; Please enter space-separated letters; Please restart the ROI viewer after modification',...
                'Keyboard shortcuts used to correct GT vs prediction discrepancies; Please enter space-separated letters; Please restart the ROI viewer after modification',...
                'Keyboard shortcuts used to set frames bounds: only frames within the bounds will be considered for training; Please enter space-separated letters; Please restart the ROI viewer after modification',...
                'Keyboard shortcuts used to quickly jump between frames',....
                 'Keyboard shortcuts used to fill holes when painting',...
                 'Keyboard shortcuts used to change painting transparency',...
                 'Size in pixels of the brush size used when using the left mouse button;  Please restart the ROI viewer after modification',...
        'Size in pixels of the brush size used when using the right mouse button;  Please restart the ROI viewer after modification',...
        'Size in pixels of the brush size used when using the mouse wheel button;  Please restart the ROI viewer after modification'};
    
    userprefs=struct('roi_view_shortcut_keys','a z e r t y u i',...
        'roi_view_corr_shortcut_keys','j k',...
        'roi_view_bounds_shortcut_keys','w x',...
        'roi_view_frames_jump_size','l m',...
        'painting_fill_holes_shortcut','k',...
        'painting_transparency_shortcut','g h',...
        'painting_large_brush_size', 9,... 
        'painting_small_brush_size', 1,... 
        'painting_huge_brush_size', 49,...
        'tip',{tip});

          save(fle,'userprefs');
            end
            