function []=plotValidationsCNNLSTM(classi,varargin)
dateT=char( datetime('now','Format','yyyy-MM-dd-HH-mm-ss'));
path=[classi.path '\TrainingValidation\'];
folder=dir(path);
folder=folder(contains({folder.name},string(dateT)));

% dateT=[dateT '-n' num2str(numel(folder))];
mkdir([path dateT]);

commentsCNN="ND";

plottraj=1;
for i=1:numel(varargin)
    %Comment
    if strcmp(varargin{i},'CommentCNN')
        commentsCNN=string(varargin{i+1});
    end
    %plotTraj
    if strcmp(varargin{i},'Traj')
    plottraj=varargin{i+1};
    end
end

commentsLSTM="ND";
for i=1:numel(varargin)
    %Comment
    if strcmp(varargin{i},'CommentLSTM')
        commentsLSTM=string(varargin{i+1});
    end
end

load([path  '\trainingParam.mat']);
copyfile([classi.path '\' classi.strid '.mat'],[path  dateT '\' classi.strid '.mat']);
copyfile([classi.path '\netCNN.mat'],[path dateT  '\netCNN.mat']);
copyfile([classi.path '\netLSTM.mat'],[path dateT  '\netLSTM.mat']);

 %% CNN Training
copyfile([path 'CNNTraining.pdf'],[path dateT '\CNNTraining.pdf']);
folder=dir(path);
CNNfile=folder(contains({folder.name},'CNNTraining.pdf'));

%% LSTM Training
copyfile([path 'LSTMTraining.pdf'],[path dateT '\LSTMTraining.pdf']);
LSTMfile=folder(contains({folder.name},'CNNTraining.pdf'));

%% CNNparam
figCNN=figure('Name', CNNfile.date,'Units', 'Normalized', 'Position',[0.1, 0.1, 0.5, 0.5]);
load([path  '\CNNOptions.mat']);

if numel(CNNOptions.InitialLearnRate)==0
    CNNOptions.InitialLearnRate=999;
end

tableCNN=table(string(datetime('now','Format','HH:mm:ss')),...
    string(CNNfile.date),...
    string(classi.path),...
    string(classi.strid),...
    numel([trainingParam.rois]),...
    string(num2str([trainingParam.rois])),...
    string(trainingParam.network),...
    trainingParam.split,...
    string(num2str(trainingParam.rotateAugmentation)),...
    string(num2str(trainingParam.translateAugmentation)),...
    CNNOptions.InitialLearnRate,...
    string(CNNOptions.LearnRateScheduleSettings.Method ),...
    CNNOptions.LearnRateScheduleSettings.DropRateFactor,...
    CNNOptions.LearnRateScheduleSettings.DropPeriod,...
    CNNOptions.L2Regularization,...
    string(CNNOptions.Shuffle),...
    CNNOptions.MaxEpochs,...
    CNNOptions.MiniBatchSize,...
    string(CNNOptions.GradientThresholdMethod),...
    CNNOptions.GradientThreshold,...
    string(commentsCNN),...
    'VariableNames',...
    {'DateOfReport',...
    'DateOfTraining',...
    'path',...
    'classi',...
    'NumberOfRois',...
    'ROIList',...
    'CNNNetwork',...
    'CNNSplit',...
    'rotateAugmentation',...
    'translateAugmentation',...
    'InitialLearnRate' ,...
    'LearnRateScheduleMethod',...
    'LearnRateScheduleDropFactor',...
    'LearnRateScheduleDropPeriod',...
    'L2Reg',...
    'Shuffle',...
    'MaxEpochs',...
    'MiniBatchSize',...
    'GradientThresholdMethod',...
    'GradientThreshold',...
    'Comments'});
    %CNNOptions.LearnRateDropFactor,...
    %CNNOptions.LearnRateDropPeriod,...
%     'LearnRateScheduleDropFactor',...
%     'LearnRateScheduleDropPeriod',...
    
if isfield(CNNOptions,'Momentum')
    tableCNN_specific=table("SGDM",...
        CNNOptions.Momentum,...
        'VariableNames',...
        {'Method',...
        'Momentum'});
    
elseif isfield(CNNOptions,'Epsilon')
    tableCNN_specific=table("ADAM",...
        CNNOptions.GradientDecayFactor,...
        CNNOptions.Epsilon,...
        'VariableNames',...
        {'Method',...
        'GradientDecayFactor',...
        'Epsilon'});
end

tableCNN=[tableCNN tableCNN_specific];
tableCNN = table(tableCNN{:,:}.','RowNames',tableCNN.Properties.VariableNames);
%         tableCNN.Properties.VariableNames="ADAM";

%need to pass table into cell to use fig instead uifig, because
%the export functions for uifig are bugged (not thanks, Mathworks)
cellCNN=table2cell(tableCNN);
for i=1:numel(cellCNN)
    cellCNN{i}=char(cellCNN{i});
end

uitCNN=uitable(figCNN,'Data',cellCNN,'RowName',tableCNN.Row,'ColumnWidth',{1500},'Units', 'Normalized', 'Position',[0, 0,1, 1],...
    'FontWeight', 'bold');
export_fig(figCNN, [path dateT '\CNNParam.pdf']);
copyfile([path  '\CNNOptions.mat'],[path dateT '\CNNOptions.mat']);

%% LSTMparam
figLSTM=figure('Name', LSTMfile.date, 'Units', 'Normalized', 'Position',[0.1, 0.1, 0.5, 0.5],'HandleVisibility', 'on');
load([path  'LSTMOptions.mat']);

tableLSTM=table(string(LSTMfile.date),...
    string(classi.path),...
    string(classi.strid),...
    numel([trainingParam.rois]),...
    string(num2str([trainingParam.rois])),...
    trainingParam.lstmlayers,...,
    trainingParam.lstmsplit,...
    LSTMOptions.InitialLearnRate,...
    string(LSTMOptions.LearnRateScheduleSettings.Method ),...
    LSTMOptions.LearnRateScheduleSettings.DropRateFactor,...
    LSTMOptions.LearnRateScheduleSettings.DropPeriod,...
    LSTMOptions.L2Regularization,...
    string(LSTMOptions.Shuffle),...
    LSTMOptions.MaxEpochs,...
    LSTMOptions.MiniBatchSize,...
    string(LSTMOptions.GradientThresholdMethod),...
    LSTMOptions.GradientThreshold,...
    string(commentsLSTM),...
    'VariableNames',...
    {'DateOfTraining',...
    'path',...
    'classi',...
    'NumberOfROIs',...  
    'ROIList',...
    'NumberOfLayers',...
    'LSTMSplit',...
    'InitialLearnRate' ,...
    'LearnRateScheduleMethod',...
    'LearnRateScheduleDropFactor',...
    'LearnRateScheduleDropPeriod',...
    'L2Reg',...
    'Shuffle',...
    'MaxEpochs',...
    'MiniBatchSize',...
    'GradientThresholdMethod',...
    'GradientThreshold',...
    'Comments'});

if isfield(LSTMOptions,'Momentum')
    tableLSTM_specific=table("SGDM",...
        LSTMOptions.Momentum,...
        'VariableNames',...
        {'Method',...
        'Momentum'});
    
elseif isfield(LSTMOptions,'Epsilon')
    tableLSTM_specific=table("ADAM",...
        LSTMOptions.GradientDecayFactor,...
        LSTMOptions.Epsilon,...
        'VariableNames',...
        {'Method',...
        'GradientDecayFactor',...
        'Epsilon'});
end
tableLSTM=[tableLSTM tableLSTM_specific];
tableLSTM = table(tableLSTM{:,:}.','RowNames',tableLSTM.Properties.VariableNames);
%         tableLSTM.Properties.VariableNames="ADAM";
        
        %need to pass table into cell to use fig instead uifig, because
        %the export functions for uifig are bugged (not thanks, Mathworks)
        cellLSTM=table2cell(tableLSTM);
        for i=1:numel(cellLSTM)
        cellLSTM{i}=char(cellLSTM{i});
        end
        
    uitLSTM=uitable(figLSTM,'Data',cellLSTM,'RowName',tableLSTM.Row,'ColumnWidth',{1500},'Units', 'Normalized', 'Position',[0, 0,1, 1],...
        'FontWeight', 'bold');
    export_fig(figLSTM, [path dateT '\LSTMParam.pdf']);
    copyfile([path  '\LSTMOptions.mat'],[path dateT '\LSTMOptions.mat']);

%% Classif stats
for i=1:numel([trainingParam.rois{1,:}])
    roisTrain(i)=trainingParam.rois{1,i};
end
roisTest=1:numel(classi.roi(:)); %take all the rois of the classi
roisTest=setdiff(roisTest,roisTrain); %remove the training rois

[hClassiStats1, hClassiStats2, hClassiStats3] =classi.stats(roisTrain,'Dataset','TRAINSET');

export_fig(hClassiStats1, [path dateT '\accuracy_ROIs_Train.pdf']);
export_fig(hClassiStats2, [path dateT '\accuracy_classes_Train.pdf']);
export_fig(hClassiStats3, [path dateT '\confusion_Train.pdf']);

if numel(roisTest)>0

    [hClassiStats_Test1, hClassiStats_Test2, hClassiStats_Test3] =classi.stats(roisTest,'Dataset','TESTSET');

    export_fig(hClassiStats_Test1, [path dateT '\accuracy_ROIs_Test.pdf']);
    export_fig(hClassiStats_Test2, [path dateT '\accuracy_classes_Test.pdf']);
    export_fig(hClassiStats_Test3, [path dateT '\confusion_Test.pdf']);
end


%% Traj
if plottraj==1
    cctraj=1;
    for i=roisTrain
        trajiTrain(cctraj)=classi.roi(i).traj(classi.strid,'Hide',1,'Comment', 'TRAINSET');
        export_fig(trajiTrain(cctraj), [path dateT '\traj_Train_' num2str(roisTrain(cctraj)) '.pdf']);
        close(trajiTrain(cctraj));
        cctraj=cctraj+1;
    end
    
    cctraj=1;
    for i=roisTest
        trajiTest(cctraj)=classi.roi(i).traj(classi.strid,'Hide',1,'Comment', 'TESTSET');
        export_fig(trajiTest(cctraj), [path dateT '\traj_Test_' num2str(roisTest(cctraj)) '.pdf']);
        close(trajiTest(cctraj));
        cctraj=cctraj+1;
    end
end

%% RLS
[rlsTrain,~,~]=measureRLS2(classi,'Rois',roisTrain);
[rlsTest,~,~]=measureRLS2(classi,'Rois',roisTest);
%% statRLS
[hRlsStats1Train,hRlsStats2Train,hRlsStats3Train]=statRLS(rlsTrain,'Comment','TRAINSET');
export_fig(hRlsStats1Train, [path dateT '\rlsStats1Train.pdf']);
export_fig(hRlsStats2Train, [path dateT '\rlsStats2Train.pdf']);
export_fig(hRlsStats3Train, [path dateT '\rlsStats3Train.pdf']);

[hRlsStats1Test,hRlsStats2Test,hRlsStats3Test]=statRLS(rlsTest,'Comment','TESTSET');
export_fig(hRlsStats1Test, [path dateT '\rlsStats1Test.pdf']);
export_fig(hRlsStats2Test, [path dateT '\rlsStats2Test.pdf']);
export_fig(hRlsStats3Test, [path dateT '\rlsStats3Test.pdf']);
%% plotRLS
hRlsTrain=plotRLS(rlsTrain,'Comment','TRAINSET');
export_fig(hRlsTrain, [path dateT '\rlsTrain.pdf']);

hRlsTest=plotRLS(rlsTest,'Comment','TESTSET');
export_fig(hRlsTest, [path dateT '\rlsTest.pdf']);
%% Report
if exist([path  '\' dateT '\' 'Report_' dateT '.pdf'],'file')
    error('Cant write PDF, file already exists');
end

if numel(roisTest)>0
    disp('test data available, printing them on the report')

append_pdfs([path  '\' dateT '\' 'Report_' dateT  '.pdf'],...
    [path dateT '\CNNParam.pdf'],...
    [path dateT '\CNNTraining.pdf'],...
    [path dateT '\LSTMParam.pdf'],...
    [path dateT '\LSTMTraining.pdf'],...
    [path dateT '\accuracy_ROIs_Train.pdf'],...
    [path dateT '\accuracy_classes_Train.pdf'],...
    [path dateT '\confusion_Train.pdf'],...
    [path dateT '\accuracy_ROIs_Test.pdf'],...
    [path dateT '\accuracy_classes_Test.pdf'],...
    [path dateT '\confusion_Test.pdf'],...
    [path dateT '\rlsStats1Train.pdf'],...
    [path dateT '\rlsStats2Train.pdf'],...
    [path dateT '\rlsStats3Train.pdf'],...
    [path dateT '\rlsTrain.pdf'],...
    [path dateT '\rlsStats1Test.pdf'],...
    [path dateT '\rlsStats2Test.pdf'],...
    [path dateT '\rlsStats3Test.pdf'],...
    [path dateT '\rlsTest.pdf']);    

else
    disp('no test data')
append_pdfs([path  '\' dateT '\' 'Report_' dateT '.pdf'],...
    [path dateT '\CNNParam.pdf'],...
    [path dateT '\CNNTraining.pdf'],...
    [path dateT '\LSTMParam.pdf'],...
    [path dateT '\LSTMTraining.pdf'],...
    [path dateT '\accuracy_ROIs_Train.pdf'],...
    [path dateT '\accuracy_classes_Train.pdf'],...
    [path dateT '\confusion_Train.pdf'],...
    [path dateT '\rlsStats1Train.pdf'],...
    [path dateT '\rlsStats2Train.pdf'],...
    [path dateT '\rlsStats3Train.pdf'],...
    [path dateT '\rlsTrain.pdf'],...
    [path dateT '\rlsStats1Test.pdf'],...
    [path dateT '\rlsStats2Test.pdf'],...
    [path dateT '\rlsStats3Test.pdf'],...
    [path dateT '\rlsTest.pdf']);    

end
save([path dateT '\trainingParam.mat'],'trainingParam');

delete([path dateT '\CNNParam.pdf']);
delete([path dateT '\CNNTraining.pdf']);
delete([path dateT '\LSTMParam.pdf']);
delete([path dateT '\LSTMTraining.pdf']);
delete([path dateT '\accuracy_ROIs_Train.pdf']);
delete([path dateT '\accuracy_classes_Train.pdf']);
delete([path dateT '\confusion_Train.pdf']);
delete([path dateT '\rlsStats1Train.pdf']),...
delete([path dateT '\rlsStats2Train.pdf']),...
delete([path dateT '\rlsStats3Train.pdf']),...
delete([path dateT '\rlsTrain.pdf']),...
delete([path dateT '\rlsStats1Test.pdf']),...
delete([path dateT '\rlsStats2Test.pdf']),...
delete([path dateT '\rlsStats3Test.pdf']),...
delete([path dateT '\rlsTest.pdf']);

if numel(roisTest)>0
    delete([path dateT '\accuracy_ROIs_Test.pdf']);
    delete([path dateT '\accuracy_classes_Test.pdf']);
    delete([path dateT '\confusion_Test.pdf']);
end

%===TRAJ===
if plottraj==1
    cctraj=1;
    for i=roisTrain
        append_pdfs([path  '\' dateT '\' 'Report_' dateT '.pdf'],...
            [path dateT '\traj_Train_' num2str(roisTrain(cctraj)) '.pdf']);
        delete([path dateT '\traj_Train_' num2str(roisTrain(cctraj)) '.pdf'])
        cctraj=cctraj+1;
    end
    cctraj=1;
    for i=roisTest
        append_pdfs([path  '\' dateT '\' 'Report_' dateT '.pdf'],...
            [path dateT '\traj_Test_' num2str(roisTest(cctraj)) '.pdf']);
        delete([path dateT '\traj_Test_' num2str(roisTest(cctraj)) '.pdf'])
        cctraj=cctraj+1;
    end    
end

        
close all
clear figCNN figLSTM uit uitCNN uitLSTM
