function tests = testClassifierTrainingPipelineDefaults
tests = functiontests(localfunctions);
end

function testTrainingBindingsOverrideInferenceDefaults(testCase)
params = struct( ...
    'trackChannelName', '', ...
    'gfpChannelName', 'stale_gfp', ...
    'brightfieldChannelName', 'stale_bf', ...
    'outputFamilyName', 'keep_me');
training = struct( ...
    'trackChannelName', 'latent_model_1_cell', ...
    'gfpChannelName', '', ...
    'brightfieldChannelName', 'Channel1_z2', ...
    'notAnInput', 'ignored');

actual = classifierApplyTrainingInputBindings(params, training, ...
    {'trackChannelName','gfpChannelName','brightfieldChannelName'});

verifyEqual(testCase, actual.trackChannelName, 'latent_model_1_cell');
verifyEqual(testCase, actual.gfpChannelName, '');
verifyEqual(testCase, actual.brightfieldChannelName, 'Channel1_z2');
verifyEqual(testCase, actual.outputFamilyName, 'keep_me');
verifyFalse(testCase, isfield(actual, 'notAnInput'));
end

function testTrainingBindingAcceptsLegacyChoiceEncoding(testCase)
actual = classifierApplyTrainingInputBindings(struct(), ...
    struct('trackChannelName', {{'first_mask','reviewed_mask'}}), ...
    {'trackChannelName'});

verifyEqual(testCase, actual.trackChannelName, 'reviewed_mask');
end

function testValidationRestoresTrainingChannelWhenExecutionChoiceIsEmpty(testCase)
contract = channelContract( ...
    {'trackChannelName','nucleusChannelName'}, {'trackChannelName'});
classifier = struct( ...
    'trainingParam', struct( ...
        'trackChannelName', 'reviewed_mask', ...
        'nucleusChannelName', 'training_nucleus'), ...
    'executionParam', struct( ...
        'trackChannelName', '', ...
        'nucleusChannelName', 'validation_nucleus'), ...
    'channelName', {{'fallback_mask','generic_gfp'}}, ...
    'channelName2', '', ...
    'dataset', struct('channels', {{}}));

actual = classifierApplyPipelineInputBindings( ...
    struct('trackChannelName', '', 'nucleusChannelName', ''), ...
    classifier, contract, 'validate', '');

verifyEqual(testCase, actual.trackChannelName, 'reviewed_mask');
verifyEqual(testCase, actual.nucleusChannelName, 'training_nucleus');
end

function testTrainingSelectorsRemainAuthoritative(testCase)
contract = channelContract( ...
    {'trackChannelName','brightfieldChannelName'}, {'trackChannelName'});
classifier = struct( ...
    'trainingParam', struct( ...
        'trackChannelName', 'ground_truth_mask', ...
        'brightfieldChannelName', ''), ...
    'executionParam', struct( ...
        'trackChannelName', 'inference_mask', ...
        'brightfieldChannelName', 'inference_bf'), ...
    'channelName', {{'fallback_mask'}}, ...
    'channelName2', '', ...
    'dataset', struct('channels', {{}}));

actual = classifierApplyPipelineInputBindings( ...
    struct(), classifier, contract, 'train', '');

verifyEqual(testCase, actual.trackChannelName, 'ground_truth_mask');
verifyEqual(testCase, actual.brightfieldChannelName, '');
end

function testRequiredSlotsUseClassifierChannelsForAnyPackage(testCase)
contract = channelContract( ...
    {'imageChannelName','instanceChannelName'}, ...
    {'imageChannelName','instanceChannelName'});
classifier = struct( ...
    'trainingParam', struct(), 'executionParam', struct(), ...
    'channelName', {{'brightfield','cellpose_mask'}}, ...
    'channelName2', '', 'dataset', struct('channels', {{}}));

actual = classifierApplyPipelineInputBindings( ...
    struct(), classifier, contract, 'validate', '');

verifyEqual(testCase, actual.imageChannelName, 'brightfield');
verifyEqual(testCase, actual.instanceChannelName, 'cellpose_mask');
end

function testOptionalTypedSlotsAreNotInferredPositionally(testCase)
contract = channelContract( ...
    {'trackChannelName','nucleusChannelName','budneckChannelName'}, ...
    {'trackChannelName'});
classifier = struct( ...
    'trainingParam', struct(), 'executionParam', struct(), ...
    'channelName', {{'tracked_mask','generic_gfp','another_channel'}}, ...
    'channelName2', '', 'dataset', struct('channels', {{}}));

actual = classifierApplyPipelineInputBindings( ...
    struct(), classifier, contract, 'validate', '');

verifyEqual(testCase, actual.trackChannelName, 'tracked_mask');
verifyFalse(testCase, isfield(actual, 'nucleusChannelName'));
verifyFalse(testCase, isfield(actual, 'budneckChannelName'));
end

function testExplicitRunChannelsOverrideRequiredSlots(testCase)
contract = channelContract( ...
    {'imageChannelName','instanceChannelName'}, ...
    {'imageChannelName','instanceChannelName'});
classifier = struct( ...
    'trainingParam', struct(), ...
    'executionParam', struct( ...
        'imageChannelName', 'saved_image', ...
        'instanceChannelName', 'saved_mask'), ...
    'channelName', {{'fallback_image','fallback_mask'}}, ...
    'channelName2', '', 'dataset', struct('channels', {{}}));

actual = classifierApplyPipelineInputBindings( ...
    struct(), classifier, contract, 'validate', 'run_image,run_mask');

verifyEqual(testCase, actual.imageChannelName, 'run_image');
verifyEqual(testCase, actual.instanceChannelName, 'run_mask');
end

function testAllPackagedClassifierContractsReceiveRequiredChannels(testCase)
packages = {'budMotherLinker','cellLatentModel','cellLatentTracker', ...
    'cellposesam','cnn','cnn_lstm', ...
    'deeplab_pixel_classification','sam31','trackastra'};
for p = 1:numel(packages)
    pkg = packages{p};
    params = struct('pkg', pkg);
    if strcmp(pkg, 'cellLatentModel')
        params.backend = 'continuous_cell_state';
    end
    contract = pipelineNodeContract(struct( ...
        'type', 'classifier', 'pkg', pkg, ...
        'func', [pkg '.classify'], 'params', params));
    requiredKeys = requiredContractChannelKeys(contract);
    stored = arrayfun(@(i)sprintf('%s_input_%d', pkg, i), ...
        1:max(1, numel(requiredKeys)), 'UniformOutput', false);
    classifier = struct( ...
        'trainingParam', struct(), 'executionParam', struct(), ...
        'channelName', {stored}, 'channelName2', '', ...
        'dataset', struct('channels', {{}}));

    actual = classifierApplyPipelineInputBindings( ...
        struct(), classifier, contract, 'validate', '');

    for k = 1:numel(requiredKeys)
        key = requiredKeys{k};
        verifyTrue(testCase, isfield(actual, key), ...
            sprintf('%s did not configure required selector %s.', pkg, key));
        verifyNotEmpty(testCase, actual.(key), ...
            sprintf('%s left required selector %s empty.', pkg, key));
    end
end
end


function testValidationInheritsCompatibleTrainingExecutionDefaults(testCase)
classifier = struct( ...
    'trainingParam', struct( ...
        'frameIntervalMinutes', 5, 'minLifetime', 7, 'epochs', 999), ...
    'executionParam', struct('frameIntervalMinutes', [], 'minLifetime', 5), ...
    'classifierPkg', '', 'trainingFun', '', 'path', '', 'strid', 'test');
spec = struct( ...
    'staticKeys', {{'frameIntervalMinutes','minLifetime'}}, ...
    'artifactKeys', {{}}, 'environmentKeys', {{}}, 'outputKeys', {{}});

actual = classifierApplyTrainingExecutionDefaults( ...
    struct('frameIntervalMinutes', [], 'minLifetime', 5), ...
    classifier, spec, 'validate');

verifyEqual(testCase, actual.frameIntervalMinutes, 5);
verifyEqual(testCase, actual.minLifetime, 7);
verifyFalse(testCase, isfield(actual, 'epochs'));
end

function testEmptyHistoricalTrainingValueDoesNotEraseExplicitRuntime(testCase)
classifier = struct( ...
    'trainingParam', struct('frameIntervalMinutes', []), ...
    'executionParam', struct('frameIntervalMinutes', 5), ...
    'classifierPkg', '', 'trainingFun', '', 'path', '', 'strid', 'test');
spec = struct( ...
    'staticKeys', {{'frameIntervalMinutes'}}, ...
    'artifactKeys', {{}}, 'environmentKeys', {{}}, 'outputKeys', {{}});

actual = classifierApplyTrainingExecutionDefaults( ...
    classifier.executionParam, classifier, spec, 'annotation');

verifyEqual(testCase, actual.frameIntervalMinutes, 5);
end

function testTrainingExecutionSnapshotWinsOverStaleClassifierState(testCase)
folder = tempname;
mkdir(folder);
cleanup = onCleanup(@()rmdir(folder, 's'));
payload = struct( ...
    'schemaVersion', 1, 'classifierId', 'latent_1', ...
    'classifierPackage', 'cellLatentModel', ...
    'executionDefaults', struct( ...
        'backend', 'continuous_cell_state', ...
        'frameIntervalMinutes', 5, ...
        'modelSource', 'trained', ...
        'modelPath', fullfile('models','trained','continuous_cell_state.pt')));
file = fullfile(folder, 'training_execution_defaults.json');
fid = fopen(file, 'w');
closeFile = onCleanup(@()fclose(fid));
fwrite(fid, jsonencode(payload), 'char');
clear closeFile;
classifier = struct( ...
    'trainingParam', struct(), ...
    'executionParam', struct('backend', 'legacy'), ...
    'classifierPkg', 'cellLatentModel', 'trainingFun', '', ...
    'path', folder, 'strid', 'latent_1');

actual = classifierTrainingExecutionDefaults(classifier, struct());

verifyEqual(testCase, actual.backend, 'continuous_cell_state');
verifyEqual(testCase, actual.frameIntervalMinutes, 5);
verifyEqual(testCase, actual.modelSource, 'trained');
end

function testCompositeSnapshotMigratesGtInputToSegmentation(testCase)
folder=tempname;
mkdir(folder);
cleanup=onCleanup(@()rmdir(folder,'s')); %#ok<NASGU>
c=classi(folder,'latent_snapshot',1,'InitTraining',false);
c.classifierPkg='cellLatentModel';
c.trainingParam=cellLatentModel.utils.defaultTrainingParam();
c.trainingParam.architectureVersion='detecdiv_composite_v1';
c.trainingParam.trackChannelName='latent_model_1_cell';
c.trainingParam.instanceChannelName='results_cellposeSAM_cell';
c.executionParam=struct('backend','causal_composite');
r=makeRoiFixture('R1', ...
    {'raw','results_cellposeSAM_cell','latent_model_1_cell'});
r.display.indexed=[false true true];
c.roi=r;
payload=struct('schemaVersion',1,'classifierId',c.strid, ...
    'classifierPackage','cellLatentModel', ...
    'executionDefaults',struct('backend','causal_composite', ...
    'instanceChannelName','latent_model_1_cell', ...
    'trackChannelName','latent_model_1_cell'));
file=fullfile(c.path,'training_execution_defaults.json');
fid=fopen(file,'w');
closeFile=onCleanup(@()fclose(fid));
fwrite(fid,jsonencode(payload),'char');
clear closeFile;

actual=classifierTrainingExecutionDefaults(c,struct());

verifyEqual(testCase,actual.instanceChannelName, ...
    'results_cellposeSAM_cell');
verifyEmpty(testCase,actual.trackChannelName);
verifyEqual(testCase,actual.outputTrackChannelName, ...
    ['pred_' c.strid '_tracks']);
verifyEqual(testCase,actual.outputFamilyName, ...
    ['pred_' c.strid '_lineage']);
end

function testTrainingResultPreservesAuthoritativeRoiSnapshot(testCase)
folder=tempname;
mkdir(folder);
cleanup=onCleanup(@()rmdir(folder,'s')); %#ok<NASGU>
full=classi(folder,'full_classifier',1,'InitTraining',false);
full.classifierPkg='cellLatentModel';
full.roi=[makeRoiFixture('R1',{'raw'}), ...
    makeRoiFixture('R2',{'raw'}),makeRoiFixture('R3',{'raw'})];
full.trainingset=[1 2];
full.dataset.split=struct('train',[1 2],'val',3,'test',[]);
full.bounds=struct('SchemaVersion',2,'Type','Manual', ...
    'Values',[1 20],'RoiValues',struct( ...
    'roi_id','R2','roi_index',2,'values',[3 17], ...
    'updated_at','2026-08-17T00:00:00Z'), ...
    'Rules',struct('Dataseries',[],'Dataset',[], ...
    'Value',[],'Occurence',[0],'Offset',[0]));
full.trainingParam=struct('modelName','before');
full.executionParam=struct('backend','legacy');
classiObj=full; %#ok<NASGU>
target=fullfile(full.path,[full.strid '_classification.mat']);
save(target,'classiObj','-v7.3');

worker=classi(folder,'full_classifier',1,'InitTraining',false);
worker.classifierPkg='cellLatentModel';
worker.roi=full.roi(1);
worker.trainingset=1;
worker.dataset.split=struct('train',1,'val',[],'test',[]);
worker.bounds=struct('SchemaVersion',2,'Type','Auto','Values',[], ...
    'RoiValues',struct('roi_id',{},'roi_index',{},'values',{}, ...
    'updated_at',{}),'Rules',struct('Dataseries',[],'Dataset',[], ...
    'Value',[],'Occurence',[0],'Offset',[0]));
worker.trainingParam=struct('modelName','trained_v002');
worker.executionParam=struct('backend','causal_composite', ...
    'instanceChannelName','results_cellposeSAM_cell');
sidecar=fullfile(full.path,'training_execution_defaults.json');
fid=fopen(sidecar,'w');
fwrite(fid,jsonencode(struct('schemaVersion',1, ...
    'executionDefaults',struct('backend','legacy'))),'char');
fclose(fid);

report=classifierPersistTrainingResult(worker);
saved=load(target,'classiObj');
defaults=jsondecode(fileread(sidecar));

verifyTrue(testCase,report.usedAuthoritativeSnapshot);
verifyEqual(testCase,report.workerRoiCount,1);
verifyEqual(testCase,report.savedRoiCount,3);
verifyEqual(testCase,{saved.classiObj.roi.id},{'R1','R2','R3'});
verifyEqual(testCase,saved.classiObj.trainingset,[1 2]);
verifyEqual(testCase,saved.classiObj.dataset.split.val,3);
verifyEqual(testCase,saved.classiObj.bounds.Type,'Manual');
verifyEqual(testCase,saved.classiObj.bounds.Values,[1 20]);
verifyEqual(testCase,saved.classiObj.bounds.RoiValues.roi_id,'R2');
verifyEqual(testCase,saved.classiObj.trainingParam.modelName,'trained_v002');
verifyEqual(testCase,saved.classiObj.executionParam.backend, ...
    'causal_composite');
verifyEqual(testCase,report.executionDefaultsFile,sidecar);
verifyEqual(testCase,defaults.executionDefaults.backend, ...
    'causal_composite');
end

function testSuccessfulTrainingSnapshotPersistsDeployableState(testCase)
folder = tempname;
mkdir(folder);
cleanup = onCleanup(@()rmdir(folder, 's'));
classifier = struct( ...
    'trainingParam', struct('frameIntervalMinutes', 5), ...
    'executionParam', struct( ...
        'backend', 'continuous_cell_state', ...
        'frameIntervalMinutes', 5, ...
        'modelSource', 'trained', ...
        'modelPath', fullfile('models','trained','continuous_cell_state.pt'), ...
        'outputFamilyName', 'do_not_freeze_output'), ...
    'classifierPkg', 'cellLatentModel', 'trainingFun', '', ...
    'path', folder, 'strid', 'latent_1');

file = classifierPersistTrainingExecutionDefaults(classifier);
payload = jsondecode(fileread(file));

verifyEqual(testCase, payload.executionDefaults.backend, ...
    'continuous_cell_state');
verifyEqual(testCase, payload.executionDefaults.modelSource, 'trained');
verifyEqual(testCase, payload.executionDefaults.outputFamilyName, ...
    'do_not_freeze_output');
end

function testValidationRoisAreFilteredByConfiguredContractInputs(testCase)
rois = [makeRoiFixture('one', {'tracked_mask','brightfield'}), ...
    makeRoiFixture('two', {'brightfield'}), ...
    makeRoiFixture('three', {'tracked_mask','brightfield'})];
node = struct( ...
    'type', 'classifier', 'pkg', 'cellLatentModel', ...
    'func', 'cellLatentModel.classify', ...
    'params', struct( ...
        'backend', 'continuous_cell_state', ...
        'trackChannelName', 'tracked_mask', ...
        'brightfieldChannelName', 'brightfield', ...
        'nucleusChannelName', '', 'budneckChannelName', ''));

[compatible, missing, channels] = ...
    classifierFilterValidationRois(rois, 1:3, node);

verifyEqual(testCase, compatible, [1 3]);
verifyEqual(testCase, missing, 2);
verifyEqual(testCase, channels, {'tracked_mask','brightfield'});
end

function testLocalOnlyClassifierDefaultsToLocal(testCase)
hub = localHubMapping();
actual = classifierDefaultExecutionTarget( ...
    'C:\Users\Gilles\SynologyDrive\Data\classifier', hub);
verifyEqual(testCase, actual, 'local');
end

function testMappedWindowsClassifierDefaultsToHub(testCase)
hub = localHubMapping();
actual = classifierDefaultExecutionTarget( ...
    'X:\ClassiRepository\latent_model_1', hub);
verifyEqual(testCase, actual, 'hub');
end

function testServerClassifierDefaultsToHub(testCase)
actual = classifierDefaultExecutionTarget( ...
    '/data/ClassiRepository/latent_model_1', struct());
verifyEqual(testCase, actual, 'hub');
end

function hub = localHubMapping()
hub = struct();
hub.defaultLocalProjectRoot = '';
hub.defaultRemoteProjectRoot = '';
hub.pathMappings = struct('localRoot', 'X:\', 'remoteRoot', '/data');
end

function contract = channelContract(selectorKeys, requiredKeys)
contract = struct();
contract.binding = struct('selectorKeys', {selectorKeys});
resources = repmat(struct( ...
    'type', 'channel', 'required', false, 'param', '', 'nameParam', ''), ...
    1, numel(selectorKeys));
for i = 1:numel(selectorKeys)
    resources(i).param = selectorKeys{i};
    resources(i).nameParam = selectorKeys{i};
    resources(i).required = any(strcmp(requiredKeys, selectorKeys{i}));
end
contract.resources = struct('in', resources);
end

function keys = requiredContractChannelKeys(contract)
keys = {};
resources = contract.resources.in;
for i = 1:numel(resources)
    if strcmpi(char(string(resources(i).type)), 'channel') && ...
            logical(resources(i).required)
        key = char(string(resources(i).param));
        if ~isempty(key)
            keys{end+1} = key; %#ok<AGROW>
        end
    end
end
keys = unique(keys, 'stable');
end

function r = makeRoiFixture(id, channels)
r = roi(id, [1 1 2 2]);
r.display.channel = channels;
end
