function tests = testClassifierTrainingPipelineDefaults
tests = functiontests(localfunctions);
end

function testTrainingBindingsOverrideInferenceDefaults(testCase)
params = struct( ...
    'trackChannelName', '', ...
    'gfpChannelName', 'stale_gfp', ...
    'brightfieldChannelName', 'stale_bf', ...
    'outputFamilyName', 'keep_me');
training = struct( ...
    'trackChannelName', 'latent_model_1_cell', ...
    'gfpChannelName', '', ...
    'brightfieldChannelName', 'Channel1_z2', ...
    'notAnInput', 'ignored');

actual = classifierApplyTrainingInputBindings(params, training, ...
    {'trackChannelName','gfpChannelName','brightfieldChannelName'});

verifyEqual(testCase, actual.trackChannelName, 'latent_model_1_cell');
verifyEqual(testCase, actual.gfpChannelName, '');
verifyEqual(testCase, actual.brightfieldChannelName, 'Channel1_z2');
verifyEqual(testCase, actual.outputFamilyName, 'keep_me');
verifyFalse(testCase, isfield(actual, 'notAnInput'));
end

function testTrainingBindingAcceptsLegacyChoiceEncoding(testCase)
actual = classifierApplyTrainingInputBindings(struct(), ...
    struct('trackChannelName', {{'first_mask','reviewed_mask'}}), ...
    {'trackChannelName'});

verifyEqual(testCase, actual.trackChannelName, 'reviewed_mask');
end

function testValidationRestoresTrainingChannelWhenExecutionChoiceIsEmpty(testCase)
contract = channelContract( ...
    {'trackChannelName','nucleusChannelName'}, {'trackChannelName'});
classifier = struct( ...
    'trainingParam', struct( ...
        'trackChannelName', 'reviewed_mask', ...
        'nucleusChannelName', 'training_nucleus'), ...
    'executionParam', struct( ...
        'trackChannelName', '', ...
        'nucleusChannelName', 'validation_nucleus'), ...
    'channelName', {{'fallback_mask','generic_gfp'}}, ...
    'channelName2', '', ...
    'dataset', struct('channels', {{}}));

actual = classifierApplyPipelineInputBindings( ...
    struct('trackChannelName', '', 'nucleusChannelName', ''), ...
    classifier, contract, 'validate', '');

verifyEqual(testCase, actual.trackChannelName, 'reviewed_mask');
verifyEqual(testCase, actual.nucleusChannelName, 'validation_nucleus');
end

function testTrainingSelectorsRemainAuthoritative(testCase)
contract = channelContract( ...
    {'trackChannelName','brightfieldChannelName'}, {'trackChannelName'});
classifier = struct( ...
    'trainingParam', struct( ...
        'trackChannelName', 'ground_truth_mask', ...
        'brightfieldChannelName', ''), ...
    'executionParam', struct( ...
        'trackChannelName', 'inference_mask', ...
        'brightfieldChannelName', 'inference_bf'), ...
    'channelName', {{'fallback_mask'}}, ...
    'channelName2', '', ...
    'dataset', struct('channels', {{}}));

actual = classifierApplyPipelineInputBindings( ...
    struct(), classifier, contract, 'train', '');

verifyEqual(testCase, actual.trackChannelName, 'ground_truth_mask');
verifyEqual(testCase, actual.brightfieldChannelName, '');
end

function testRequiredSlotsUseClassifierChannelsForAnyPackage(testCase)
contract = channelContract( ...
    {'imageChannelName','instanceChannelName'}, ...
    {'imageChannelName','instanceChannelName'});
classifier = struct( ...
    'trainingParam', struct(), 'executionParam', struct(), ...
    'channelName', {{'brightfield','cellpose_mask'}}, ...
    'channelName2', '', 'dataset', struct('channels', {{}}));

actual = classifierApplyPipelineInputBindings( ...
    struct(), classifier, contract, 'validate', '');

verifyEqual(testCase, actual.imageChannelName, 'brightfield');
verifyEqual(testCase, actual.instanceChannelName, 'cellpose_mask');
end

function testOptionalTypedSlotsAreNotInferredPositionally(testCase)
contract = channelContract( ...
    {'trackChannelName','nucleusChannelName','budneckChannelName'}, ...
    {'trackChannelName'});
classifier = struct( ...
    'trainingParam', struct(), 'executionParam', struct(), ...
    'channelName', {{'tracked_mask','generic_gfp','another_channel'}}, ...
    'channelName2', '', 'dataset', struct('channels', {{}}));

actual = classifierApplyPipelineInputBindings( ...
    struct(), classifier, contract, 'validate', '');

verifyEqual(testCase, actual.trackChannelName, 'tracked_mask');
verifyFalse(testCase, isfield(actual, 'nucleusChannelName'));
verifyFalse(testCase, isfield(actual, 'budneckChannelName'));
end

function testExplicitRunChannelsOverrideRequiredSlots(testCase)
contract = channelContract( ...
    {'imageChannelName','instanceChannelName'}, ...
    {'imageChannelName','instanceChannelName'});
classifier = struct( ...
    'trainingParam', struct(), ...
    'executionParam', struct( ...
        'imageChannelName', 'saved_image', ...
        'instanceChannelName', 'saved_mask'), ...
    'channelName', {{'fallback_image','fallback_mask'}}, ...
    'channelName2', '', 'dataset', struct('channels', {{}}));

actual = classifierApplyPipelineInputBindings( ...
    struct(), classifier, contract, 'validate', 'run_image,run_mask');

verifyEqual(testCase, actual.imageChannelName, 'run_image');
verifyEqual(testCase, actual.instanceChannelName, 'run_mask');
end

function testAllPackagedClassifierContractsReceiveRequiredChannels(testCase)
packages = {'budMotherLinker','cellLatentModel','cellposesam','cnn_lstm', ...
    'deeplab_pixel_classification','sam31','trackastra'};
for p = 1:numel(packages)
    pkg = packages{p};
    params = struct('pkg', pkg);
    if strcmp(pkg, 'cellLatentModel')
        params.backend = 'continuous_cell_state';
    end
    contract = pipelineNodeContract(struct( ...
        'type', 'classifier', 'pkg', pkg, ...
        'func', [pkg '.classify'], 'params', params));
    requiredKeys = requiredContractChannelKeys(contract);
    stored = arrayfun(@(i)sprintf('%s_input_%d', pkg, i), ...
        1:max(1, numel(requiredKeys)), 'UniformOutput', false);
    classifier = struct( ...
        'trainingParam', struct(), 'executionParam', struct(), ...
        'channelName', {stored}, 'channelName2', '', ...
        'dataset', struct('channels', {{}}));

    actual = classifierApplyPipelineInputBindings( ...
        struct(), classifier, contract, 'validate', '');

    for k = 1:numel(requiredKeys)
        key = requiredKeys{k};
        verifyTrue(testCase, isfield(actual, key), ...
            sprintf('%s did not configure required selector %s.', pkg, key));
        verifyNotEmpty(testCase, actual.(key), ...
            sprintf('%s left required selector %s empty.', pkg, key));
    end
end
end

function testLocalOnlyClassifierDefaultsToLocal(testCase)
hub = localHubMapping();
actual = classifierDefaultExecutionTarget( ...
    'C:\Users\Gilles\SynologyDrive\Data\classifier', hub);
verifyEqual(testCase, actual, 'local');
end

function testMappedWindowsClassifierDefaultsToHub(testCase)
hub = localHubMapping();
actual = classifierDefaultExecutionTarget( ...
    'X:\ClassiRepository\latent_model_1', hub);
verifyEqual(testCase, actual, 'hub');
end

function testServerClassifierDefaultsToHub(testCase)
actual = classifierDefaultExecutionTarget( ...
    '/data/ClassiRepository/latent_model_1', struct());
verifyEqual(testCase, actual, 'hub');
end

function hub = localHubMapping()
hub = struct();
hub.defaultLocalProjectRoot = '';
hub.defaultRemoteProjectRoot = '';
hub.pathMappings = struct('localRoot', 'X:\', 'remoteRoot', '/data');
end

function contract = channelContract(selectorKeys, requiredKeys)
contract = struct();
contract.binding = struct('selectorKeys', {selectorKeys});
resources = repmat(struct( ...
    'type', 'channel', 'required', false, 'param', '', 'nameParam', ''), ...
    1, numel(selectorKeys));
for i = 1:numel(selectorKeys)
    resources(i).param = selectorKeys{i};
    resources(i).nameParam = selectorKeys{i};
    resources(i).required = any(strcmp(requiredKeys, selectorKeys{i}));
end
contract.resources = struct('in', resources);
end

function keys = requiredContractChannelKeys(contract)
keys = {};
resources = contract.resources.in;
for i = 1:numel(resources)
    if strcmpi(char(string(resources(i).type)), 'channel') && ...
            logical(resources(i).required)
        key = char(string(resources(i).param));
        if ~isempty(key)
            keys{end+1} = key; %#ok<AGROW>
        end
    end
end
keys = unique(keys, 'stable');
end
