function convention = relationTemporalConvention()
%CELLMODEL.RELATIONTEMPORALCONVENTION Canonical parent-event timing.
% Parent links are stored at the child's first visible frame, regardless of
% when a reviewer created the link. A coherent annotation requires parent
% and child at the birth frame. The
% temporal training head has a stricter, head-specific eligibility rule: the
% parent must also be materialized on birth-1. Static or left-censored links
% remain valid GT. Legacy click timestamps are migrated during explicit
% managed-GT validation; read-only consumers canonicalize a local copy.

convention = struct( ...
    'name', 'child_birth_v2', ...
    'canonical_event', 'child_birth', ...
    'accepted_event_minus_birth', 0, ...
    'required_annotation_parent_frame_relative_to_event', 0, ...
    'temporal_training_parent_frames_relative_to_event', [0 -1], ...
    'accepted_presence_frames_relative_to_event', [0 -1]);
end
