function entry = newEntry(spec, totalFrames)
%ANNOTATIONMANAGER.NEWENTRY Create lifecycle metadata for one annotation bundle.

if nargin < 1 || isempty(spec)
    annotationId = '';
    classifierId = '';
    components = repmat(annotationManager.newComponent(), 0, 1);
else
    annotationId = char(string(spec.id));
    classifierId = char(string(spec.classifierId));
    components = spec.components;
end
if nargin < 2 || isempty(totalFrames), totalFrames = 0; end

reviewTemplate = struct('component_id', '', 'unit', 'frame', ...
    'frames', false(1, max(0, round(double(totalFrames)))), ...
    'complete', false);
review = repmat(reviewTemplate, numel(components), 1);
for i = 1:numel(components)
    review(i).component_id = char(string(components(i).id));
    review(i).unit = char(string(components(i).coverageUnit));
    if strcmp(review(i).unit, 'roi')
        review(i).frames = false(1, 0);
    end
end

entry = struct( ...
    'annotation_id', annotationId, ...
    'classifier_id', classifierId, ...
    'status', 'missing', ...
    'revision', uint32(0), ...
    'updated_at', '', ...
    'approved_at', '', ...
    'approved_hash', '', ...
    'validation_status', 'not_run', ...
    'validated_at', '', ...
    'validated_hash', '', ...
    'validation_message', '', ...
    'validated_revision', uint32(0), ...
    'source_type', '', ...
    'source_id', '', ...
    'source_run_id', '', ...
    'source_manifest_path', '', ...
    'source_manifest_sha256', '', ...
    'source_bundle_sha256', '', ...
    'label_authority', '', ...
    'import_notes', '', ...
    'import_exclusions', {cell(0,1)}, ...
    'review', review);
end
