function issue = newValidationIssue(varargin)
%ANNOTATIONMANAGER.NEWVALIDATIONISSUE Canonical navigable validation issue.

issue = struct( ...
    'code', '', ...
    'severity', 'error', ...
    'component', 'Validation', ...
    'summary', '', ...
    'message', '', ...
    'role', '', ...
    'relation_id', uint64(0), ...
    'family_id', uint32(0), ...
    'event_frame', uint32(0), ...
    'missing_track_id', uint64(0), ...
    'parent_track_id', uint64(0), ...
    'child_track_id', uint64(0), ...
    'focus_track_id', uint64(0), ...
    'focus_frame', uint32(0), ...
    'from_frame', uint32(0), ...
    'to_frame', uint32(0), ...
    'area_before', NaN, ...
    'area_after', NaN, ...
    'area_ratio', NaN, ...
    'centroid_displacement_px', NaN, ...
    'normalized_centroid_jump', NaN, ...
    'threshold_name', '', ...
    'threshold_value', NaN, ...
    'repairable', false);

if mod(numel(varargin), 2) ~= 0
    error('annotationManager:InvalidValidationIssue', ...
        'Validation issue options must be name/value pairs.');
end
for i = 1:2:numel(varargin)
    name = char(string(varargin{i}));
    if ~isfield(issue, name)
        error('annotationManager:InvalidValidationIssueField', ...
            'Unknown validation issue field "%s".', name);
    end
    issue.(name) = varargin{i+1};
end
end
