function report = validateParentage(model, family, varargin)
%ANNOTATIONMANAGER.VALIDATEPARENTAGE Validate parent relations for one family.

p = inputParser;
p.addParameter('Throw', false, @(x) islogical(x) && isscalar(x));
p.addParameter('Frames', [], @isnumeric);
p.parse(varargin{:});

% event_frame is derived from the child trajectory. Canonicalize a local
% copy so legacy Score click timestamps never become biological errors.
model = cellModel.normalize(model);
[model, ~] = cellModel.canonicalizeParentageEvents(model);

errors = strings(0,1);
issues = annotationManager.emptyValidationIssues();
[familyIndex, familyId] = cellModel.familyIndex(model, family);
if isempty(familyIndex)
    errors(end+1,1) = "Ground-truth object family is missing.";
else
    relationRows = model.relations.family_id == familyId & ...
        model.relations.type_id == uint8(1);
    if ~isempty(p.Results.Frames)
        relationRows = relationRows & ismember( ...
            double(model.relations.event_frame),double(p.Results.Frames));
    end
    parents = model.relations.parent_track_id(relationRows);
    children = model.relations.child_track_id(relationRows);

    if any(parents == 0 | children == 0 | parents == children)
        errors(end+1,1) = ...
            "Parentage contains an invalid parent/child identity.";
    end
    if numel(unique(children)) ~= numel(children)
        errors(end+1,1) = "A child track has more than one parent.";
    end

    familyTracks = unique(model.instances.track_id( ...
        model.instances.family_id == familyId));
    familyTracks = familyTracks(familyTracks > 0);
    relationIndices = find(relationRows);
    missingParent = ~ismember(parents, familyTracks);
    missingChild = ~ismember(children, familyTracks);
    for i = find(missingParent(:)).'
        issues(end+1,1) = missingTrackIssue(model, familyId, ... %#ok<AGROW>
            relationIndices(i), 'parent', parents(i), children(i));
    end
    for i = find(missingChild(:)).'
        issues(end+1,1) = missingTrackIssue(model, familyId, ... %#ok<AGROW>
            relationIndices(i), 'child', children(i), parents(i));
    end
    convention = annotationManager.relationTemporalConvention();
    [evidence, model] = cellModel.parentageEvidence( ...
        model, familyId, 'Frames', p.Results.Frames);
    for i = 1:numel(relationIndices)
        if missingParent(i) || missingChild(i) || parents(i) == 0 || ...
                children(i) == 0 || parents(i) == children(i)
            continue;
        end
        relationId = model.relations.relation_id(relationIndices(i));
        evidenceIndex = find([evidence.relation_id] == relationId, 1);
        if isempty(evidenceIndex), continue; end
        if cellModel.isCensored(model, familyId, children(i), ...
                double(evidence(evidenceIndex).event_frame), 'parentage')
            issues(end+1,1) = censoredParentageIssue( ... %#ok<AGROW>
                model, evidence(evidenceIndex));
            continue;
        end
        relationIssues = evidenceIssues(evidence(evidenceIndex), convention);
        if ~isempty(relationIssues)
            issues = [issues; relationIssues]; %#ok<AGROW>
        end
    end
    if ~isempty(issues)
        errorIssues = issues(strcmpi(string({issues.severity}), 'error'));
        previewCount = min(8, numel(errorIssues));
        errors = [errors; string({errorIssues(1:previewCount).message}).'];
        if numel(errorIssues) > previewCount
            errors(end+1,1) = sprintf( ...
                '%d additional invalid parentage reference(s) were omitted.', ...
                numel(errorIssues) - previewCount);
        end
    end

    if ~isempty(parents)
        graphValue = digraph(double(parents), double(children));
        if ~isdag(graphValue)
            errors(end+1,1) = "Parentage contains a cycle.";
        end
    end
end

report = struct('valid', isempty(errors), 'errors', errors, ...
    'familyId', familyId, 'issues', issues);
if p.Results.Throw && ~report.valid
    error('annotationManager:InvalidParentage', '%s', ...
        strjoin(report.errors, ' '));
end

function issue = censoredParentageIssue(model, item)
reason = censorReason(model, item.family_id, item.child_track_id, ...
    item.event_frame, cellModel.censorScope('parentage'));
message = sprintf([ ...
    'Advisory only: parentage for child Track %u at frame %u is explicitly ' ...
    'censored (%s). It is retained for audit but excluded from parentage ' ...
    'training and scoring.'], item.child_track_id, item.event_frame, reason);
issue = annotationManager.newValidationIssue( ...
    'code', 'explicitly_censored_parentage', ...
    'severity', 'warning', ...
    'component', 'Parentage', ...
    'summary', 'Explicitly censored parentage', ...
    'message', message, ...
    'role', 'child', ...
    'relation_id', item.relation_id, ...
    'family_id', item.family_id, ...
    'event_frame', item.event_frame, ...
    'parent_track_id', item.parent_track_id, ...
    'child_track_id', item.child_track_id, ...
    'focus_track_id', item.child_track_id, ...
    'focus_frame', item.event_frame, ...
    'repairable', false);
end

function name = censorReason(model, familyId, trackId, frame, scopeFlag)
rows = model.censoring.family_id == familyId & ...
    model.censoring.track_id == trackId & ...
    model.censoring.frame_start <= uint32(frame) & ...
    model.censoring.frame_end >= uint32(frame) & ...
    bitand(model.censoring.scope_flags, scopeFlag) ~= 0;
index = find(rows, 1, 'first');
name = 'documented reason';
if isempty(index), return; end
reasonId = model.censoring.reason_id(index);
reasonIndex = find(uint16([model.censor_reasons.reason_id]) == reasonId, 1);
if ~isempty(reasonIndex), name = model.censor_reasons(reasonIndex).name; end
end

function issue = missingTrackIssue(model, familyId, relationIndex, role, ...
        missingTrackId, counterpartTrackId)
eventFrame = double(model.relations.event_frame(relationIndex));
focusFrame = nearestTrackFrame(model, familyId, counterpartTrackId, eventFrame);
counterpartRole = 'child';
repairHint = 'remove or reassign its parent';
if strcmp(role, 'child')
    counterpartRole = 'parent';
    repairHint = 'remove the stale relation or restore its child';
end

if focusFrame > 0
    location = sprintf('Open frame %u and inspect %s Track %u', ...
        uint32(focusFrame), counterpartRole, uint64(counterpartTrackId));
else
    location = sprintf('Inspect %s Track %u', ...
        counterpartRole, uint64(counterpartTrackId));
end
message = sprintf([ ...
    'Missing %s Track %u: %s Track %u references it at parentage event ' ...
    'frame %u, but Track %u has no object in this GT family. %s, then %s.'], ...
    role, uint64(missingTrackId), counterpartRole, ...
    uint64(counterpartTrackId), uint32(eventFrame), ...
    uint64(missingTrackId), location, repairHint);

issue = annotationManager.newValidationIssue( ...
    'code', 'missing_track_reference', ...
    'severity', 'error', ...
    'component', 'Parentage', ...
    'summary', sprintf('Missing %s track', role), ...
    'message', message, ...
    'role', role, ...
    'relation_id', model.relations.relation_id(relationIndex), ...
    'family_id', familyId, ...
    'event_frame', uint32(eventFrame), ...
    'missing_track_id', uint64(missingTrackId), ...
    'parent_track_id', model.relations.parent_track_id(relationIndex), ...
    'child_track_id', model.relations.child_track_id(relationIndex), ...
    'focus_track_id', uint64(counterpartTrackId), ...
    'focus_frame', uint32(max(0, focusFrame)), ...
    'repairable', true);
end

function issues = evidenceIssues(item, convention)
issues = annotationManager.emptyValidationIssues();
eventFrame = double(item.event_frame);
parentId = item.parent_track_id;
childId = item.child_track_id;
if ~item.child_present_at_event
    message = sprintf([ ...
        'Child Track %u is absent at its canonical parentage event frame ' ...
        '%u under convention %s. Correct the child identity or remove the ' ...
        'stale relation.'], childId, uint32(eventFrame), convention.name);
    issues(end+1,1) = annotationManager.newValidationIssue( ... %#ok<AGROW>
        'code', 'relation_child_temporally_incompatible', ...
        'severity', 'error', ...
        'component', 'Parentage', ...
        'summary', 'Child absent at relation event', ...
        'message', message, ...
        'role', 'child', ...
        'relation_id', item.relation_id, ...
        'family_id', item.family_id, ...
        'event_frame', uint32(eventFrame), ...
        'parent_track_id', parentId, ...
        'child_track_id', childId, ...
        'focus_track_id', parentId, ...
        'focus_frame', uint32(eventFrame), ...
        'from_frame', item.child_first_frame, ...
        'to_frame', uint32(eventFrame), ...
        'repairable', false);
    return;
end

if ~item.parent_present_at_event
    message = sprintf([ ...
        'Parent Track %u is absent when child Track %u first appears at ' ...
        'frame %u. A parentage annotation requires both tracks on the ' ...
        'canonical event frame under convention %s. Correct the track ' ...
        'identity or remove the impossible relation.'], ...
        parentId, childId, uint32(eventFrame), convention.name);
    issues(end+1,1) = annotationManager.newValidationIssue( ... %#ok<AGROW>
        'code', 'relation_parent_temporally_incompatible', ...
        'severity', 'error', ...
        'component', 'Parentage', ...
        'summary', 'Parent absent at child birth', ...
        'message', message, ...
        'role', 'parent', ...
        'relation_id', item.relation_id, ...
        'family_id', item.family_id, ...
        'event_frame', uint32(eventFrame), ...
        'parent_track_id', parentId, ...
        'child_track_id', childId, ...
        'focus_track_id', childId, ...
        'focus_frame', uint32(eventFrame), ...
        'from_frame', item.parent_last_frame, ...
        'to_frame', uint32(eventFrame), ...
        'repairable', false);
    return;
end

if ~item.temporal_parentage_eligible
    message = sprintf([ ...
        'Advisory only (does not block validation or dataset ' ...
        'formatting): Parent ' ...
        'Track %u and child Track %u are jointly visible at frame %u, so ' ...
        'the parentage GT is valid. Evidence mode %s has no usable parent ' ...
        'history on frame %u; the temporal-birth head will exclude this ' ...
        'relation, while static parentage retains it.'], ...
        parentId, childId, uint32(eventFrame), item.evidence_mode, ...
        uint32(max(1, eventFrame - 1)));
    issues(end+1,1) = annotationManager.newValidationIssue( ... %#ok<AGROW>
        'code', 'relation_static_only_parentage', ...
        'severity', 'warning', ...
        'component', 'Parentage', ...
        'summary', 'Valid static-only parentage', ...
        'message', message, ...
        'role', 'parent', ...
        'relation_id', item.relation_id, ...
        'family_id', item.family_id, ...
        'event_frame', uint32(eventFrame), ...
        'parent_track_id', parentId, ...
        'child_track_id', childId, ...
        'focus_track_id', childId, ...
        'focus_frame', uint32(eventFrame), ...
        'from_frame', uint32(max(1, eventFrame - 1)), ...
        'to_frame', uint32(eventFrame), ...
        'repairable', false);
end
end

function frame = nearestTrackFrame(model, familyId, trackId, eventFrame)
rows = model.instances.family_id == familyId & ...
    model.instances.track_id == uint64(trackId);
frames = double(model.instances.frame(rows));
if isempty(frames)
    frame = 0;
    return;
end
[~, index] = min(abs(frames - eventFrame));
frame = frames(index);
end

end
