function spec = annotationSpec(classif)
%CELLPOSESAM.ANNOTATIONSPEC Instance-mask GT contract.

spec = annotationManager.newSpec(classif);
execution = cellposesam.executionSpec(classif);
outputName = char(string(execution.defaults.outputName));
gtName = annotationManager.annotationChannelName(classif, 'cell');
prediction = ['results_' outputName '_cell'];
fallback = ['results_' outputName];

component = annotationManager.newComponent( ...
    'id', 'instances', ...
    'kind', 'instance_mask', ...
    'storage', 'channel', ...
    'coverageUnit', 'frame', ...
    'editor', 'instance_mask', ...
    'bootstrap', 'copy_channel', ...
    'classes', {'cell'}, ...
    'groundTruth', annotationManager.newAsset('channel', gtName), ...
    'prediction', annotationManager.newAsset( ...
        'channel', prediction, ...
        'channelCandidates', {prediction, fallback}));

spec.displayName = 'Cell instances';
spec.components = component;
spec.defaultEditor = 'instance_mask';
end
