function spec = annotationSpec(classif)
%CELLPOSESAM.ANNOTATIONSPEC Instance-mask GT contract.

spec = annotationManager.newSpec(classif);
execution = cellposesam.executionSpec(classif);
outputName = char(string(execution.defaults.outputName));
gtName = cellposesam.annotationChannelName(classif);
prediction = ['results_' outputName '_cell'];
fallback = ['results_' outputName];

component = annotationManager.newComponent( ...
    'id', 'instances', ...
    'kind', 'instance_mask', ...
    'storage', 'channel', ...
    'coverageUnit', 'frame', ...
    'editor', 'instance_mask', ...
    'bootstrap', 'copy_channel', ...
    'classes', {'cell'}, ...
    'groundTruth', annotationManager.newAsset('channel', gtName, ...
        'quality','gt','producer','human_review', ...
        'semantic','frame_local_instances'), ...
    'prediction', annotationManager.newAsset( ...
        'channel', prediction, ...
        'channelCandidates', {prediction, fallback}, ...
        'quality','pred','producer','cellposesam', ...
        'semantic','frame_local_instances'));

spec.displayName = 'Cell instances';
spec.components = component;
spec.defaultEditor = 'instance_mask';
% Frame-local instance masks have no temporal dependency.  Score may
% therefore approve a non-empty reviewed subset; the formatter resolves
% that subset from the annotation manifest instead of treating untouched
% frames as negative examples.
spec.allowPartialApproval = true;
end
