function scope = trainingScopeSpec(~)
%CELLPOSESAM.TRAININGSCOPESPEC User-facing ownership contract.
scope=classifierBinding.newTrainingScope( ...
    'module','cellposesam', ...
    'displayName','CellposeSAM — frame-local instance segmentation', ...
    'objective','Predict one instance mask for every detected cell in each frame.', ...
    'trainedComponents',{'CellposeSAM segmentation weights'}, ...
    'frozenComponents',{'Trackastra','latent EDGE/APPEAR/END tracker','mother/NULL lineage linker'}, ...
    'datasetUnit','Microscopy frames paired with reviewed instance-mask GT.', ...
    'splitPolicy','CellposeSAM formatter train/validation split; test data are excluded.', ...
    'outputParameter','outputName','outputQuality','pred', ...
    'outputSemantic','frame-local cell instances', ...
    'outputTemplate','results_<outputName>_cell', ...
    'canonicalOutput','results_pred_cellposesam_cell');
end
