function spec = trainingSpec(~)
%CELLPOSESAM.TRAININGSPEC Image input and managed instance-mask GT.

spec = [ ...
    classifierBinding.newBinding( ...
        'param','inputChannelName', 'type','channel', 'role','roi_image', ...
        'label','Training image', 'required',true, ...
        'storage','classifierInputChannels', 'cardinality','one', ...
        'tip','Image channel used to train and run CellposeSAM.'), ...
    classifierBinding.newBinding( ...
        'param','groundTruthChannelName', 'type','channel', ...
        'role','instance_mask_ground_truth', 'label','Instance-mask GT', ...
        'required',true, 'storage','annotation', 'editable',false, ...
        'componentId','instances', ...
        'tip','Managed <classifier id>_cell annotation channel used by formatting.') ...
    ];
end
