function spec = trainingParameterSpec(~)
%CELLPOSESAM.TRAININGPARAMETERSPEC Clear CellposeSAM-only training scope.
spec = [ ...
    item('diameter','Expected cell diameter','Segmentation geometry', ...
        'Average object diameter used by CellposeSAM.'), ...
    item('min_size','Minimum object size','Segmentation filtering', ...
        'Objects below this pixel count are removed.'), ...
    item('flow_threshold','Flow consistency threshold','Segmentation filtering', ...
        'Cellpose flow-error acceptance threshold.'), ...
    item('cell_prob_threshold','Cell probability threshold','Segmentation filtering', ...
        'Cellpose foreground probability threshold.'), ...
    item('n_epochs','CellposeSAM training epochs','Optimization', ...
        'Trains CellposeSAM segmentation only; no tracking head is changed.'), ...
    item('learning_rate','Learning rate','Optimization','Optimizer learning rate.'), ...
    item('weight_decay','Weight decay','Optimization','L2 regularization.'), ...
    item('batch_size','Training batch size','Optimization','Images per batch.'), ...
    item('min_train_masks','Minimum masks per training image','Formatting', ...
        'Images below this count are excluded during formatting.'), ...
    item('min_train_pixels','Minimum foreground pixels','Formatting', ...
        'Images below this foreground coverage are excluded.'), ...
    item('use_pretrained','Initialize from pretrained CellposeSAM','Initialization', ...
        'Copies pretrained segmentation weights before fine-tuning.'), ...
    item('MaxTrainImages','Maximum training images','Sampling', ...
        'Caps the number of formatted training images.'), ...
    item('NegDownsampleTrainRatio','Negative-image downsampling','Sampling', ...
        'Controls the number of empty images relative to positive images.'), ...
    item('CPSAM_ValFraction','Validation fraction','Validation', ...
        'Fraction held out by the CellposeSAM formatter.'), ...
    item('Seed','Random seed','Reproducibility','Sampling and optimization seed.'), ...
    item('verbose','Verbose training log','Runtime','Show CellposeSAM progress details.') ...
    ];
end
function out=item(param,label,group,tip)
out=struct('param',param,'label',label,'group',group,'tip',tip, ...
    'choiceLabels',{{}});
end
