function spec = trainingSpec(~)
%CELLPOSESAM.TRAININGSPEC Image input and managed instance-mask GT.

spec = [ ...
    classifierBinding.newBinding( ...
        'param','inputChannelName', 'type','channel', 'role','roi_image', ...
        'quality','input', 'semantic','microscopy_image', ...
        'label','[INPUT] Microscopy image', 'required',true, ...
        'storage','classifierInputChannels', 'cardinality','one', ...
        'tip','Image channel used to train and run CellposeSAM.'), ...
    classifierBinding.newBinding( ...
        'param','groundTruthChannelName', 'type','channel', ...
        'role','instance_mask_ground_truth', 'quality','gt', ...
        'semantic','frame_local_instances', ...
        'label','[GT] Reviewed instance masks', ...
        'required',true, 'storage','annotation', 'editable',false, ...
        'componentId','instances', ...
        'tip',['Managed gt_<classifier>_instances annotation channel used by ' ...
        'formatting. Existing legacy <classifier>_cell channels are preserved.']) ...
    ];
end
