function info = inspectPythonAppControlFailure(status,output)
%INSPECTPYTHONAPPCONTROLFAILURE Identify a retry-safe Python startup block.
% A retry is safe only for the narrow Windows Smart App Control signature
% observed while importing the package CLI itself. Runtime/scientific errors
% and ordinary missing/broken DLL errors deliberately do not match.

text = char(string(output));
lowerText = lower(text);
info = struct( ...
    'retryable',false, ...
    'isDllImportFailure',false, ...
    'isAppControlBlock',false, ...
    'isBeforeCli',false, ...
    'blockedModule','', ...
    'blockedFile','');

info.isDllImportFailure = contains(lowerText,'importerror:') && ...
    contains(lowerText,'dll load failed while importing');
info.isAppControlBlock = contains(lowerText,'0xc0e90002') || ...
    contains(lowerText, ...
        'application control policy has blocked this file') || ...
    ~isempty(regexpi(text,[ ...
        'strat\S*gie\s+de\s+contr\S*le\s+d\S*application\s+' ...
        'a\s+bloqu\S*\s+ce\s+fichier'],'once'));

% With `python -m cell_latent_model`, Python first imports the package to
% locate __main__. A heavy dependency can therefore be blocked either while
% importing package __init__ or while importing cli from __main__. Neither
% path has entered main(), and both are distinguishable from a command error.
mainImportPattern = [ ...
    '__main__\.py["'']?,\s+line\s+\d+,\s+in\s+<module>\s+' ...
    'from\s+\.cli\s+import\s+main'];
packageImportPattern = [ ...
    'runpy\.py["'']?,\s+line\s+\d+,\s+in\s+_get_module_details\s+' ...
    '__import__\(pkg_name\)'];
importsPackageInit = ...
    ~isempty(regexpi(text,packageImportPattern,'once')) && ...
    ~isempty(regexpi(text, ...
        'cell_latent_model[\\/]__init__\.py["'']?,\s+line\s+\d+', ...
        'once'));
enteredCli = contains(lowerText,'@@detecdiv_progress@@') || ...
    ~isempty(regexpi(text, ...
        'cli\.py["'']?,\s+line\s+\d+,\s+in\s+main', 'once')) || ...
    ~isempty(regexpi(text, ...
        '__main__\.py["'']?,\s+line\s+\d+,\s+in\s+<module>\s+main\(\)', ...
        'once'));
info.isBeforeCli = (~isempty(regexpi(text,mainImportPattern,'once')) || ...
    importsPackageInit) && ~enteredCli;

moduleToken = regexpi(text, ...
    'dll load failed while importing\s+([a-z0-9_.-]+)', ...
    'tokens','once');
if ~isempty(moduleToken), info.blockedModule = moduleToken{1}; end
fileToken = regexpi(text, ...
    '([a-z]:\\[^\r\n"]+\.(?:pyd|dll))', ...
    'tokens','once');
if ~isempty(fileToken), info.blockedFile = fileToken{1}; end

info.retryable = isscalar(status) && isnumeric(status) && ...
    isfinite(status) && status ~= 0 && ...
    info.isDllImportFailure && info.isAppControlBlock && info.isBeforeCli;
end
