function report = pipelinePathMappingSmokeTest()
% pipelinePathMappingSmokeTest  Verify Hub mappings reach module resolution.

    hub = struct();
    hub.pathMappings = [ ...
        struct('localRoot', 'X:\', 'remoteRoot', '/data'), ...
        struct('localRoot', 'Z:\', 'remoteRoot', '/data')];
    mappingCtx = struct('hub', hub);

    payloadMappings = detecdiv_paths_run_payload_mappings(mappingCtx);
    payloadMappings = jsondecode(jsonencode(payloadMappings));
    assert(localHasMapping(payloadMappings, 'X:\', '/data'), ...
        'The X: client mapping was not preserved in the run payload.');
    assert(localHasMapping(payloadMappings, 'Z:\', '/data'), ...
        'The Z: client mapping was not preserved in the run payload.');

    workerCtx = struct('run', struct('paths', struct( ...
        'path_mappings', payloadMappings)));
    payload = struct('paths', struct('path_mappings', payloadMappings));
    detecdiv_paths_assert_hub_payload_safe(payload, 'run_request');

    unsafePayload = payload;
    unsafePayload.modulePath = 'Z:\matlab\ClassiRepository\div_1\';
    blockedUnsafePath = false;
    try
        detecdiv_paths_assert_hub_payload_safe(unsafePayload, 'run_request');
    catch ME
        blockedUnsafePath = strcmp(ME.identifier, ...
            'detecdiv_hub_submit_pipeline_run:LocalPathInHubPayload');
    end
    assert(blockedUnsafePath, ...
        'A client path outside path_mappings.localRoot was not rejected.');

    [classifierPath, classifierMapped] = detecdiv_paths_map_module_path( ...
        'Z:\matlab\ClassiRepository\div_1\', workerCtx, 'server');
    [processorPath, processorMapped] = detecdiv_paths_map_module_path( ...
        'X:\matlab\ProcessRepository\metrics_1\', workerCtx, 'server');

    assert(classifierMapped && strcmp(classifierPath, ...
        '/data/matlab/ClassiRepository/div_1'), ...
        'The worker did not map the Z: classifier modulePath.');
    assert(processorMapped && strcmp(processorPath, ...
        '/data/matlab/ProcessRepository/metrics_1'), ...
        'The worker did not map the X: processor modulePath.');

    report = struct( ...
        'ok', true, ...
        'mappingCount', numel(payloadMappings), ...
        'classifierPath', classifierPath, ...
        'processorPath', processorPath);
end

function tf = localHasMapping(mappings, localRoot, remoteRoot)
    tf = false;
    for i = 1:numel(mappings)
        localValue = regexprep(strrep(char(string(mappings(i).localRoot)), ...
            '/', '\'), '[\\/]+$', '');
        remoteValue = regexprep(strrep(char(string(mappings(i).remoteRoot)), ...
            '\', '/'), '[\/]+$', '');
        expectedLocal = regexprep(strrep(char(string(localRoot)), ...
            '/', '\'), '[\\/]+$', '');
        expectedRemote = regexprep(strrep(char(string(remoteRoot)), ...
            '\', '/'), '[\/]+$', '');
        if strcmpi(localValue, expectedLocal) && strcmp(remoteValue, expectedRemote)
            tf = true;
            return;
        end
    end
end
