function report = roiPartialSaveRegressionTest()
% roiPartialSaveRegressionTest  Ensure partial ROI saves preserve H5 channels.

testRoot = tempname;
mkdir(testRoot);
cleanup = onCleanup(@() localCleanup(testRoot)); %#ok<NASGU>

r = roi('partial_save_test', [1 1 9 8]);
r.path = testRoot;

H = 8;
W = 9;
T = 3;
firstValues = uint16(100 + reshape(1:(H*W*T), H, W, 1, T));
r.image = firstValues;
r.channelid = 1;
r.display.channel = {'ch1'};
r.display.intensity = [1 1 1];
r.display.rgb = [1 1 1];
r.display.indexed = false;
r.display.alpha = 1;
r.display.contour = false;
r.display.width = 1;
r.display.selectedchannel = 1;

for iChannel = 2:5
    values = uint16(100 * iChannel + reshape(1:(H*W*T), H, W, 1, T));
    if iChannel == 3
        % Exercise a multi-plane logical channel like CombinedChannel.
        values = cat(3, values, values + 1, values + 2);
    end
    r.addChannel(values, sprintf('ch%d', iChannel), [1 1 1], [1 1 1]);
end
r.normalizeDisplayCache();
r.display.valueTransform(1) = struct( ...
    'mode', 'physical', ...
    'unit', 'old_calibration_unit', ...
    'physicalRange', [0 1], ...
    'encodedRange', [0 65535], ...
    'transform', 'linear');
r.save([], false);

h5File = fullfile(testRoot, ['im_' r.id '.h5']);
gfpBefore = h5read(h5File, '/ch2');
ch1IndexedBefore = h5readatt(h5File, '/ch1', 'display_indexed');
ch1AlphaBefore = h5readatt(h5File, '/ch1', 'display_alpha');
assert(strcmp(char(string(h5readatt(h5File, '/ch1', ...
        'physical_unit'))), 'old_calibration_unit'), ...
    'roiPartialSaveRegressionTest:InitialPhysicalCalibrationMissing', ...
    'The initial physical calibration was not persisted.');

% A cleared image cache deliberately retains the complete display and
% channelid metadata, as happens for persisted classifier ROIs.
r.image = [];
r.load('Channel', {'ch1','ch5'}, 'Silent');
assert(size(r.image,3) == 2, ...
    'roiPartialSaveRegressionTest:NonCompactImage', ...
    'Partial load created placeholder image planes.');
assert(isequal(double(r.channelid), [1 5]), ...
    'roiPartialSaveRegressionTest:NonCompactMapping', ...
    'Partial load did not create the expected compact channel mapping.');

result = zeros(H, W, 1, T, 'uint16');
r.addChannel(result, 'results_partial_save_test', [1 1 1], [0 0 0]);
assert(isequal(double(r.channelid), [1 5 6]), ...
    'roiPartialSaveRegressionTest:BadAddedChannelMapping', ...
    'addChannel did not map the result to its display channel row.');
assert(isequal(r.findChannelID('results_partial_save_test'), 3), ...
    'roiPartialSaveRegressionTest:BadAddedChannelIndex', ...
    'The result channel does not map to its image plane.');

% Simulate a stale compact Score cache. A partial data save must not turn
% the existing continuous H5 channel into an indexed mask merely because
% its in-memory display row was temporarily misconfigured.
r.display.indexed(1) = true;
r.display.intensity(1,:) = [0 0 0];
r.display.alpha(1) = 0.25;
r.display.valueTransform(1) = struct( ...
    'mode', 'physical', ...
    'unit', 'updated_calibration_unit', ...
    'physicalRange', [-2 4], ...
    'encodedRange', [100 60000], ...
    'transform', 'linear');

r.save([], false);
gfpAfter = h5read(h5File, '/ch2');
assert(isequal(gfpBefore, gfpAfter), ...
    'roiPartialSaveRegressionTest:UntouchedChannelChanged', ...
    'A compact partial save changed an unloaded H5 channel.');
assert(isequal(h5readatt(h5File, '/ch1', 'display_indexed'), ...
        ch1IndexedBefore), ...
    'roiPartialSaveRegressionTest:ExistingDisplayTypeChanged', ...
    'A compact partial save rewrote an existing channel display type.');
assert(isequal(h5readatt(h5File, '/ch1', 'display_alpha'), ...
        ch1AlphaBefore), ...
    'roiPartialSaveRegressionTest:ExistingDisplayAlphaChanged', ...
    'A compact partial save rewrote existing channel display opacity.');
assert(strcmp(char(string(h5readatt(h5File, '/ch1', ...
        'value_mode'))), 'physical') && ...
        strcmp(char(string(h5readatt(h5File, '/ch1', ...
        'physical_unit'))), 'updated_calibration_unit'), ...
    'roiPartialSaveRegressionTest:PhysicalCalibrationUpdateReverted', ...
    'A compact partial save reverted the current value calibration.');
storedPhysicalRange = double([ ...
    h5readatt(h5File, '/ch1', 'physical_min'), ...
    h5readatt(h5File, '/ch1', 'physical_max')]);
storedEncodedRange = double([ ...
    h5readatt(h5File, '/ch1', 'encoded_min'), ...
    h5readatt(h5File, '/ch1', 'encoded_max')]);
assert(isequal(storedPhysicalRange, [-2 4]) && ...
        isequal(storedEncodedRange, [100 60000]), ...
    'roiPartialSaveRegressionTest:PhysicalCalibrationRangeUpdateReverted', ...
    'A compact partial save did not persist the updated calibration ranges.');
assert(h5readatt(h5File, '/results_partial_save_test', ...
        'display_indexed') == 1, ...
    'roiPartialSaveRegressionTest:NewMaskDisplayMissing', ...
    'A newly materialized mask did not receive indexed display metadata.');

expectedNames = {'ch1','ch2','ch3','ch4','ch5', ...
    'results_partial_save_test'};
expectedIndices = {1, 2, 3:5, 6, 7, 8};
expectedChannelId = [1 2 3 3 3 4 5 6];
for iChannel = 1:numel(expectedNames)
    h5Path = ['/' expectedNames{iChannel}];
    storedIndices = double(h5readatt(h5File, h5Path, ...
        'channel_indices'));
    assert(isequal(storedIndices(:).', expectedIndices{iChannel}), ...
        'roiPartialSaveRegressionTest:NonCanonicalChannelIndices', ...
        'Dataset %s retained a compact or colliding channel index.', h5Path);
    storedChannelId = double(h5readatt(h5File, h5Path, 'channelid'));
    assert(isequal(storedChannelId(:).', expectedChannelId), ...
        'roiPartialSaveRegressionTest:NonCanonicalChannelId', ...
        'Dataset %s does not describe the complete H5 channel map.', h5Path);
end

fresh = roi(r.id, r.value);
fresh.path = testRoot;
fresh.load('Silent');
assert(isequal(fresh.display.channel, expectedNames), ...
    'roiPartialSaveRegressionTest:FullReloadOrderChanged', ...
    'A full reload did not reconstruct the canonical logical channel order.');
assert(~logical(fresh.display.indexed(1)), ...
    'roiPartialSaveRegressionTest:ContinuousChannelReloadedAsMask', ...
    'The continuous channel reloaded as an indexed mask.');
assert(logical(fresh.display.indexed(end)), ...
    'roiPartialSaveRegressionTest:ResultMaskReloadedAsContinuous', ...
    'The new result mask lost its indexed display contract.');
assert(isequal(double(fresh.channelid), expectedChannelId), ...
    'roiPartialSaveRegressionTest:FullReloadChannelIdChanged', ...
    'A full reload did not reconstruct multi-plane logical channel ids.');

% Also protect objects created by the old loader: their channelid length
% exceeded the image C dimension and the intermediate image planes were
% zero placeholders. Such a mapping must result in no image write.
compact = r.image;
stale = zeros(H, W, 5, T, 'like', compact);
stale(:,:,1,:) = compact(:,:,1,:);
stale(:,:,5,:) = compact(:,:,2,:);
r.image = stale;
r.channelid = 1:6;
didSave = r.save([], false);
gfpAfterStaleSave = h5read(h5File, '/ch2');
assert(~didSave, ...
    'roiPartialSaveRegressionTest:StaleMappingWasSaved', ...
    'save accepted an ambiguous stale partial-load mapping.');
assert(isequal(gfpBefore, gfpAfterStaleSave), ...
    'roiPartialSaveRegressionTest:StaleMappingChangedChannel', ...
    'A stale partial-load mapping changed an unloaded H5 channel.');

localAssertH5OnlyChannelOrderPreserved(testRoot, H, W, T);

report = struct( ...
    'compactChannelId', [1 5], ...
    'addedChannelId', [1 5 6], ...
    'untouchedChannelPreserved', true, ...
    'existingDisplayMetadataPreserved', true, ...
    'physicalCalibrationUpdated', true, ...
    'canonicalH5ChannelIdentity', true, ...
    'h5OnlyChannelOrderPreserved', true, ...
    'staleMappingRejected', true);
fprintf('roiPartialSaveRegressionTest: PASS\n');
end

function localAssertH5OnlyChannelOrderPreserved(testRoot, H, W, T)
% h5info may enumerate A,B,Z even though the persisted logical order is
% A,Z,B.  A compact cache containing only A must retain Z before B.
ordered = roi('partial_order_test', [1 1 W H]);
ordered.path = testRoot;
base = reshape(uint16(1:(H*W*T)), H, W, 1, T);
ordered.image = base;
ordered.channelid = 1;
ordered.display.channel = {'A'};
ordered.display.intensity = [1 1 1];
ordered.display.rgb = [1 1 1];
ordered.display.indexed = false;
ordered.display.alpha = 1;
ordered.display.contour = false;
ordered.display.width = 1;
ordered.display.selectedchannel = 1;
ordered.addChannel(base + 100, 'Z', [1 1 1], [1 1 1]);
ordered.addChannel(base + 200, 'B', [1 1 1], [1 1 1]);
ordered.save([], false);

orderFile = fullfile(testRoot, ['im_' ordered.id '.h5']);
compact = roi(ordered.id, ordered.value);
compact.path = testRoot;
compact.image = reshape(h5read(orderFile, '/A'), H, W, 1, T);
compact.channelid = 1;
compact.display = ordered.display;
compact.display.channel = {'A'};
compact.display.selectedchannel = 1;
compact.save([], false);

expectedNames = {'A','Z','B'};
for i = 1:numel(expectedNames)
    h5Path = ['/' expectedNames{i}];
    storedIndex = double(h5readatt(orderFile, h5Path, ...
        'channel_indices'));
    assert(isequal(storedIndex(:).', i), ...
        'roiPartialSaveRegressionTest:H5OnlyChannelOrderChanged', ...
        'H5-only channel %s moved when saving a cache containing only A.', ...
        expectedNames{i});
end

fresh = roi(ordered.id, ordered.value);
fresh.path = testRoot;
fresh.load('Silent');
assert(isequal(fresh.display.channel, expectedNames), ...
    'roiPartialSaveRegressionTest:H5OnlyReloadOrderChanged', ...
    'Full reload changed the prior A,Z,B logical channel order.');
end

function localCleanup(testRoot)
try
    root = char(string(testRoot));
    tempBase = char(string(tempdir));
    if isfolder(root) && startsWith(root, tempBase, 'IgnoreCase', true) && ...
            ~strcmpi(root, tempBase)
        rmdir(root, 's');
    end
catch
end
end
