function item = newBinding(varargin)
%CLASSIFIERBINDING.NEWBINDING Create a normalized training-resource binding.

% Bindings shown by classifierGUI may be persisted in trainingParam, backed
% by the legacy classi input-channel fields, or derived read-only from the
% annotation contract.  Keeping storage explicit lets old classifiers use
% the new table without changing their on-disk schema or training code.

p = inputParser;
p.addParameter('param', '', @(x)ischar(x)||isstring(x));
p.addParameter('type', 'channel', @(x)ischar(x)||isstring(x));
p.addParameter('role', 'roi_image', @(x)ischar(x)||isstring(x));
p.addParameter('label', '', @(x)ischar(x)||isstring(x));
p.addParameter('tip', '', @(x)ischar(x)||isstring(x));
p.addParameter('required', false, @(x)islogical(x)||isnumeric(x));
p.addParameter('allowAuto', false, @(x)islogical(x)||isnumeric(x));
p.addParameter('allowNone', false, @(x)islogical(x)||isnumeric(x));
p.addParameter('group', 'Data bindings', @(x)ischar(x)||isstring(x));
p.addParameter('storage', 'trainingParam', @(x)ischar(x)||isstring(x));
p.addParameter('cardinality', 'one', @(x)ischar(x)||isstring(x));
p.addParameter('editable', true, @(x)islogical(x)||isnumeric(x));
p.addParameter('componentId', '', @(x)ischar(x)||isstring(x));
p.addParameter('legacyFallback', '', @(x)ischar(x)||isstring(x));
p.addParameter('autoValue', '', @(x)ischar(x)||isstring(x));
p.addParameter('quality', 'input', @(x)ischar(x)||isstring(x));
p.addParameter('semantic', '', @(x)ischar(x)||isstring(x));
p.parse(varargin{:});
r = p.Results;

item = struct( ...
    'param', char(string(r.param)), ...
    'type', char(string(r.type)), ...
    'role', char(string(r.role)), ...
    'label', char(string(r.label)), ...
    'tip', char(string(r.tip)), ...
    'required', logical(r.required), ...
    'allowAuto', logical(r.allowAuto), ...
    'allowNone', logical(r.allowNone), ...
    'group', char(string(r.group)), ...
    'storage', char(string(r.storage)), ...
    'cardinality', char(string(r.cardinality)), ...
    'editable', logical(r.editable), ...
    'componentId', char(string(r.componentId)), ...
    'legacyFallback', char(string(r.legacyFallback)), ...
    'autoValue', char(string(r.autoValue)), ...
    'quality', lower(char(string(r.quality))), ...
    'semantic', char(string(r.semantic)));
end
