function scope = newTrainingScope(varargin)
%CLASSIFIERBINDING.NEWTRAININGSCOPE Explicit module-training ownership.

p = inputParser;
p.addParameter('module','',@(x)ischar(x)||isstring(x));
p.addParameter('displayName','',@(x)ischar(x)||isstring(x));
p.addParameter('objective','',@(x)ischar(x)||isstring(x));
p.addParameter('trainedComponents',{},@(x)iscell(x)||ischar(x)||isstring(x));
p.addParameter('frozenComponents',{},@(x)iscell(x)||ischar(x)||isstring(x));
p.addParameter('datasetUnit','',@(x)ischar(x)||isstring(x));
p.addParameter('splitPolicy','',@(x)ischar(x)||isstring(x));
p.addParameter('outputParameter','',@(x)ischar(x)||isstring(x));
p.addParameter('outputQuality','pred',@(x)ischar(x)||isstring(x));
p.addParameter('outputSemantic','',@(x)ischar(x)||isstring(x));
p.addParameter('outputTemplate','',@(x)ischar(x)||isstring(x));
p.addParameter('canonicalOutput','',@(x)ischar(x)||isstring(x));
p.addParameter('notes',{},@(x)iscell(x)||ischar(x)||isstring(x));
p.parse(varargin{:});
r=p.Results;
scope=struct( ...
    'schemaVersion',uint16(1), ...
    'module',text(r.module), ...
    'displayName',text(r.displayName), ...
    'objective',text(r.objective), ...
    'trainedComponents',{texts(r.trainedComponents)}, ...
    'frozenComponents',{texts(r.frozenComponents)}, ...
    'datasetUnit',text(r.datasetUnit), ...
    'splitPolicy',text(r.splitPolicy), ...
    'outputParameter',text(r.outputParameter), ...
    'outputQuality',lower(text(r.outputQuality)), ...
    'outputSemantic',text(r.outputSemantic), ...
    'outputTemplate',text(r.outputTemplate), ...
    'canonicalOutput',text(r.canonicalOutput), ...
    'notes',{texts(r.notes)});
end

function value=text(value),value=strtrim(char(string(value)));end
function values=texts(value)
if isempty(value),values={};elseif ischar(value)||isstring(value),values=cellstr(string(value));else,values=cellfun(@(x)char(string(x)),value,'UniformOutput',false);end
values=values(~cellfun(@isempty,values));
end
