function tp = defaultTrainingParam()
% deeplab_pixel_classification.utils.defaultTrainingParam
% Defaults mirrored from trainPixelDeeplabNetFun parameter initialization.

tip = {'Choose the training method', ...
    'Choose the DeepLab v3+ backbone', ...
    'Choose the size of the mini batch; higher values require more memory', ...
    'Enter the number of epochs', ...
    'Enter the initial learning rate', ...
    'Choose whether and how training and validation data should be shuffled during training', ...
    'Enter fraction of the data to be used for training vs validation during training', ...
    'Check if random crossvalidation is to be performed', ...
    'Enter the magnitude of translation for data augmentation in pixels', ...
    'Enter the magnitude of rotation for data augmentation in degrees', ...
    'Specify value for L2 regularization', ...
    'Choose execution environment', ...
    'Select initial version of network to start training with; default: ImageNet'};

tp = struct( ...
    'CNN_training_method', {{'adam','sgdm','adam'}}, ...
    'CNN_network', {{'resnet18','resnet50','resnet50'}}, ...
    'CNN_mini_batch_size', 8, ...
    'CNN_max_epochs', 20, ...
    'CNN_initial_learning_rate', 0.001, ...
    'CNN_data_shuffling', {{'once','every-epoch','never','every-epoch'}}, ...
    'CNN_data_splitting_factor', 0.9, ...
    'CNN_crossvalidation', false, ...
    'CNN_translation_augmentation', [-5 5], ...
    'CNN_rotation_augmentation', [-20 20], ...
    'CNN_l2_regularization', 0.00001, ...
    'execution_environment', {{'auto','parallel','cpu','gpu','multi-gpu','auto'}}, ...
    'transfer_learning', {{'ImageNet','ImageNet'}}, ...
    'tip', {tip});
end
