function spec = annotationSpec(classif)
%CNN_LSTM.ANNOTATIONSPEC Frame-label ground-truth contract.

spec = annotationManager.newSpec(classif);
execution = cnn_lstm.executionSpec(classif);
predictionGroup = spec.classifierId;
if isfield(execution, 'defaults') && isfield(execution.defaults, 'outputName')
    predictionGroup = char(string(execution.defaults.outputName));
end

component = annotationManager.newComponent( ...
    'id', 'labels', ...
    'kind', 'frame_labels', ...
    'storage', 'dataseries', ...
    'coverageUnit', 'frame', ...
    'editor', 'class_palette', ...
    'bootstrap', 'copy_fields', ...
    'classes', spec.classes, ...
    'groundTruth', annotationManager.newAsset( ...
        'groupId', spec.classifierId, ...
        'valueField', 'labels_training', ...
        'idField', 'id_training'), ...
    'prediction', annotationManager.newAsset( ...
        'groupId', predictionGroup, ...
        'valueField', 'labels', ...
        'idField', 'id'));

spec.displayName = 'Frame labels';
spec.components = component;
spec.defaultEditor = 'class_palette';
end
