function spec = trainingSpec(~)
%CNN_LSTM.TRAININGSPEC Image stack and frame-label bindings.

spec = [ ...
    classifierBinding.newBinding( ...
        'param','inputChannelNames', 'type','channel', 'role','roi_image', ...
        'label','Training image channels', 'required',true, ...
        'storage','classifierInputChannels', 'cardinality','many', ...
        'tip','Ordered ROI channels assembled as the CNN/LSTM image input.'), ...
    classifierBinding.newBinding( ...
        'param','groundTruthLabels', 'type','dataseries', ...
        'role','frame_label_ground_truth', 'label','Frame-label GT', ...
        'required',true, 'storage','annotation', 'editable',false, ...
        'componentId','labels', ...
        'tip','Managed labels_training dataseries edited with the class palette.') ...
    ];
end
