function c = contract(node)
% Declarative IO survives saves through params, not derived node fields.
p = customModule.setparam();
if isfield(node, 'params') && isstruct(node.params), p = node.params; end
c = struct('in', struct('name',{},'type',{},'required',{},'source',{}), ...
    'out', struct('name',{},'type',{},'required',{},'source',{}));
% Malformed configuration is reported by validate, including in the GUI.
try
    cfg = customModule.configuration(p);
    c.in = cfg.in;
    c.out = cfg.out;
catch
end
c.parameters = struct('template', {{'entryPoint','codeFolder','callMode', ...
    'inputPorts','outputPorts','argumentsJson','parametersJson'}}, ...
    'static', {{'entryPoint','codeFolder','callMode','inputPorts','outputPorts','argumentsJson','parametersJson'}}, ...
    'run', {{'parametersJson'}}, 'paths', {{'codeFolder'}});
c.requirements.params.required = {'entryPoint'};
c.capabilities = struct('outputsMasks', any(strcmp({c.out.name}, 'masks')), ...
    'outputsDataSeries', any(strcmp({c.out.name}, 'dataSeries')), ...
    'outputsChannels', any(strcmp({c.out.name}, 'channels')), ...
    'outputsImages', any(strcmp({c.out.name}, 'images')), ...
    'createsRoiList', any(strcmp({c.out.name}, 'roiList')));
c.summary = 'Calls a user MATLAB function with declared parameters and context inputs/outputs.';
end
