function spec = annotationSpec(definition)
%CELLLATENTMODEL.SIGNAL.ANNOTATIONSPEC UI-neutral GT editor contract.
% A GUI, script, or import tool can use the same selectors and storage
% bindings. Scalar targets are keyed by object_id; subcellular targets are
% stored as a semantic label channel and linked by frame/mask overlap.

def=validateDefinition(definition);
if strcmp(def.task,'segmentation')
    storage=struct('kind','channel','channel',def.ground_truth_channel, ...
        'background_label',uint16(0),'class_labels',uint16(1:numel(def.classes)), ...
        'review_group',def.ground_truth_group,'review_field','Reviewed');
    editor=struct('kind','semantic_mask','selectors',{{'frame','object_id'}}, ...
        'value_control','paint_palette');
else
    storage=struct('kind','dataseries','group_id',def.ground_truth_group, ...
        'key_fields',{{'ObjectId','Frame','TrackId','MaskLabel'}}, ...
        'value_field',def.value_field);
    if strcmp(def.task,'classification'), control='class_palette'; else, control='numeric'; end
    editor=struct('kind','object_target','selectors',{{'frame','object_id','track_id'}}, ...
        'value_control',control);
end
spec=struct( ...
    'format','detecdiv_latent_signal_annotation_spec', ...
    'schema_version',uint16(1), ...
    'signal_name',def.name, ...
    'task',def.task, ...
    'target_unit',def.target_unit, ...
    'family',def.family, ...
    'classes',{def.classes}, ...
    'value_range',def.value_range, ...
    'storage',storage, ...
    'editor',editor, ...
    'raw_access_api','cellMetrics.readRaw', ...
    'temporal_context',def.temporal_context);
end

function def=validateDefinition(def)
if ~isstruct(def)||~isfield(def,'format')||~strcmp(def.format,'detecdiv_latent_signal_definition')
    error('cellLatentModel:InvalidSignalDefinition','Use cellLatentModel.signal.definition to create the definition.');
end
end
