function spec = annotationSpec(classif)
%CELLLATENTSIGNAL.ANNOTATIONSPEC Managed Score GT for a custom signal head.
def=cellLatentSignal.definitionForClassifier(classif);
spec=annotationManager.newSpec(classif);
family=char(string(def.family));
assetArgs={'family',family,'maskProvider',def.mask_provider, ...
    'quality','gt','producer','human_review', ...
    'semantic','latent_custom_signal','signalDefinition',def};
switch def.task
    case {'classification','regression'}
        gt=annotationManager.newAsset(assetArgs{:}, ...
            'groupId',def.ground_truth_group,'valueField',def.value_field, ...
            'idField','ObjectId');
        kind=['object_' def.task];
        component=annotationManager.newComponent( ...
            'id','signal_target','kind',kind,'storage','dataseries', ...
            'coverageUnit','frame','editor',kind,'bootstrap','none', ...
            'classes',def.classes,'groundTruth',gt);
        spec.defaultEditor=kind;
    case 'segmentation'
        gt=annotationManager.newAsset(assetArgs{:}, ...
            'channel',def.ground_truth_channel);
        component=annotationManager.newComponent( ...
            'id','signal_segmentation','kind','semantic_mask', ...
            'storage','channel','coverageUnit','frame', ...
            'editor','semantic_mask','bootstrap','none', ...
            'classes',def.classes,'groundTruth',gt);
        spec.defaultEditor='semantic_mask';
end
spec.displayName=['Latent signal: ' def.name];
spec.components=component;
spec.allowPartialApproval=true;
end
