function paramout = setparam(ctx)
%SELECTCAVITYTRAJECTORY.SETPARAM Defaults for cavity-role selection.

if nargin < 1 || isempty(ctx), ctx = struct(); end

paramout = struct();
paramout.pkg = 'selectCavityTrajectory';
paramout.inputFamily = {'<auto>','<auto>'};
paramout.mode = {'mother_resident','daughter_tip','mother_resident'};
paramout.outputName = 'cavity_trajectory';
paramout.outputChannelBase = 'cavity_target';
paramout.trapAxisX = 0;
paramout.trapAxisY = 1;
paramout.tipDirection = 1;
paramout.anchorXNormalized = 0.5;
paramout.anchorYNormalized = 0.5;
paramout.positionWeight = 2.0;
paramout.areaWeight = 0.15;
paramout.stayBonus = 2.5;
paramout.appearancePenalty = 1.5;
paramout.gapPenalty = 2.0;
paramout.replacementPenalty = 8.0;
paramout.lineageHandoverPenalty = 1.5;
paramout.handoverTipGainWeight = 3.0;
paramout.minHandoverAgeFrames = 3;
paramout.minHandoverTipGain = 0.03;
paramout.maxVirtualGapFrames = 2;
paramout.maxCompanionAgeFrames = 120;
paramout.abstainScore = -3.0;
paramout.confidenceTemperature = 1.0;
paramout.allowLineageHandover = true;
paramout.allowUnrelatedReplacement = true;
paramout.writeArtifact = true;
paramout.existingPolicy = 'replace';
paramout.debug = false;

if isfield(ctx,'outputName') && ~isempty(ctx.outputName)
    paramout.outputName = char(string(ctx.outputName));
end
if isfield(ctx,'names') && isstruct(ctx.names) && ...
        isfield(ctx.names,'outputName') && ~isempty(ctx.names.outputName)
    paramout.outputName = char(string(ctx.names.outputName));
end

paramout.tip = { ...
    'Input cell-model family; <auto> prefers the latest latent prediction.', ...
    'Role policy: mother_resident or daughter_tip.', ...
    'Temporal dataseries and audit-artifact name.', ...
    'Base name for _cell, _bud and _object compatibility channels.', ...
    'Cavity-axis x component.', ...
    'Cavity-axis y component.', ...
    'Direction toward the cavity tip: +1 or -1.', ...
    'Resident-mother anchor x in normalized ROI coordinates.', ...
    'Resident-mother anchor y in normalized ROI coordinates.', ...
    'Cavity-position emission weight.', ...
    'Relative-area emission weight.', ...
    'Reward for preserving the same latent TrackID.', ...
    'Cost for entering a visible TrackID from NULL.', ...
    'Per-frame cost for an absent/NULL target.', ...
    'Cost for a switch without parent-child support.', ...
    'Base cost for a parent-to-child tip handover.', ...
    'Weight of the child tip-position improvement.', ...
    'Minimum frames after child birth before handover.', ...
    'Minimum normalized tip-position gain for handover.', ...
    'Maximum internal invisible gap retained as one TrackID.', ...
    'Maximum child age exposed as a companion bud.', ...
    'NULL-state emission score.', ...
    'Temperature of the uncalibrated path-margin confidence.', ...
    'Allow parent-to-child handovers in daughter_tip mode.', ...
    'Allow unrelated cavity replacements as new episodes.', ...
    'Write a JSON audit artifact.', ...
    'Existing-output policy.', ...
    'Verbose diagnostic logging.'};
end
